### ISSUE TITLE
Dots pictures.

### ISSUE THREAD

**Issue by sfinexer** [vlachoudis/bCNC#1002]
When I make pictures with dots, I had a clear positioning. I made a transformation for the random arrangement of points in a given interval from the initial one.
So the picture looks alive.
https://github.com/Sfinexer/bCNC/tree/sfinexer-NEW
http://cnc.tiven.ru/ssr-2018-10-14_16.07.12.mp4

**Comment by Harvie** [comment]
So what's the issue?

**Comment by sfinexer** [comment]
@Harvie No problem, this is a new option.

**Comment by Harvie** [comment]
So why you create new issue for something that is not issue for you? :-)

**Comment by sfinexer** [comment]
@Harvie I want to know how relevant this opportunity is.

**Comment by Harvie** [comment]
I am not sure how many people will use this. However there's no reason to not include it. Maybe put it in "artistic" cathegory, so it gets hidden deeper into the menu.
