### ISSUE TITLE
homing pull-off for X/Y/Z

### ISSUE THREAD

**Issue by sfinexer** [vlachoudis/bCNC#1003]
If you know where the workpiece is, then it is convenient to have different homing pull-off values for each of the axes (X, Y, Z).
The $H team immediately positions the required "homing pull-off".
@MARIOBASZ That is what I meant.
Video:
http://cnc.tiven.ru/ssr-2018-10-14_16.21.04.mp4

https://github.com/gnea/grbl/issues/523

**Comment by MARIOBASZ** [comment]
I still do not understand the advantage: I can place at the start: 1- Homing 2-Go to x0 y0 3-go to z0

**Comment by sfinexer** [comment]
less action.

**Comment by sfinexer** [comment]
I pointed at the video.
I wrote earlier that the homing pull-off is the same, it may be too small for a single axis, but great for the other.
In my case, I suggest different homing pull-off values for different coordinates.
