### ISSUE TITLE
Modifying Z safe

### ISSUE THREAD

**Issue by Zjcc56** [vlachoudis/bCNC#1009]
where did you modify the z safe value? i tried putting in safe_z = 3 in the .bCNC file as instructed in the wiki but nothing changes. its also not an option in the CNC config in the program.

**Comment by MARIOBASZ** [comment]
I'm not in the machine. You put the value in Stock, (if it was not there in Material)

**Comment by Zjcc56** [comment]
Ah, Thanks that's Exactly what i was looking for!
