### ISSUE TITLE
I have the letter [P] 

### ISSUE THREAD

**Issue by sfinexer** [vlachoudis/bCNC#1011]
I have the letter [P] what does it mean ???? how to fix it?
![screenshot_20181020_101358](https://user-images.githubusercontent.com/13809436/47252660-066c4b00-d451-11e8-804f-6940ff6f4534.png)

**Comment by Harvie** [comment]
It's new feature and it's there on purpose. This means probe pin on your GRBL board is active.
If you don't have probe or your probe, you can disconnect wiring from that pin.
If you have probe, but it's not active, you can set grbl to invert probe pin.

**Comment by Harvie** [comment]
Maybe this will get better UI later, but for now it is what it is. It does not affect other functionality in any way.
