### ISSUE TITLE
how does alignment in Probing work?

### ISSUE THREAD

**Issue by c031917** [vlachoudis/bCNC#1023]
Hi,
after successfully milling the first pockets, I can't figure out now how to use the alignment option in probing. I always get "Resulting System is too skew".
I assume that I have to mark two points on my stock which might be not aligned to X-Y axis.
bCnC would then correct the gcode to compensate for that tilt.
But why do I have to first move the gantry to a point and then click with the mouse into the preview at that point which is not precise at all ?
And where do the two reference points have to be so I don't get above error ?
And last question: why can I enter more than two ref. points ? 
No documentation seems available, or did I miss it ? I would volunteer to make one if somebody explains the function to me.

I use version 0.9.14 on Windows10.

Regards
Peter

**Comment by Harvie** [comment]
I think 2 points are not enough, you need 3 or 4:
https://github.com/vlachoudis/bCNC/wiki/Orientation-of-gcode

too skew means you try to bend the g-code too much. eg. fit square into triangle

i will close the ticket, but you can still ask here
