### ISSUE TITLE
bCNC is not running

### ISSUE THREAD

**Issue by hapav** [vlachoudis/bCNC#1026]
Hello,

I have a problem with starting my bCNC. I install program how its on this video https://www.youtube.com/watch?v=zedZmYIpGKM
Everything go fine until I start it. window of cmd and Python opens and half sec later close and nothing happen. I tryed to use the same versions of programs which re at the video and i also tryed to use latest versions. Still the same problem. 
Can you help me please?

**Comment by Harvie** [comment]
Latest version of bCNC needs not only pyserial, but also numpy to be installed.﻿

**Comment by hapav** [comment]
Thanks for that, but I'm maybe stupid. Can you tell me please what should i do to instal only pyserial and that start bCNC?

**Comment by Harvie** [comment]
You can't run recent bCNC with only pyserial. You also need numpy.

**Comment by Harvie** [comment]
There's all-in-one installer in progress, you can watch #437

**Comment by hapav** [comment]
Thank you. It's running :)
