### ISSUE TITLE
Disabling antialiasing 

### ISSUE THREAD

**Issue by Guenni75** [vlachoudis/bCNC#1028]
How can i disable antialiasing?
It slows down the canvas a lot.

Is it enough to set ANTIALIAS_CHEAP to false?

**Comment by Harvie** [comment]
> Is it enough to set ANTIALIAS_CHEAP to false?

yes.

btw i think about disabling it completely anyway. i am not really happy with how it turned out.

**Comment by Guenni75** [comment]
OK. that works a little bit better.
