### ISSUE TITLE
Tweaked Fusion360 GRBL Post Processor for bCNC

### ISSUE THREAD

**Issue by Bologrew** [vlachoudis/bCNC#1030]
Not an issue but some people might find this useful.
I have modified the latest Fusion 360 GRBL Post Processor so that it automatically creates blocks in the bCNC style.  (Remove the ".txt" extension from the attached file.)
I have also made it create a block when using the "M0" command (stop which can be resumed) so that you can disable this block easily in repeated runs.
Just search for "bCNC" in the file to find the additions.
No warranty expressed or implied and it's definitely a work in progress.

[grbl-bCNC.cps.txt](https://github.com/vlachoudis/bCNC/files/2546418/grbl-bCNC.cps.txt)

**Comment by Harvie** [comment]
Nice! Thanks for your work. Does fusion have some way for users to contribute postprocessors?
I think it will be best if you try to convince them to include this directly in the fusion.
Also if you only added the (comments) they might use this with any GRBL sender, because comments in braces are ignored. So maybe this can replace default GRBL postprocessor.

**Comment by Bologrew** [comment]
Brief answer to your first question - don't know.

Longer answer - Autodesk publish an API for the Post Processor and other people have created alternative versions:
https://github.com/Strooom/GRBL-Post-Processor
Personally I haven't had a problem with the original Autodesk one as long as I don't use the "Use G28 for safe retracts" (causes mayhem on my router).
You would probably have more joy getting changes into Stroom's PP than you would the Autodesk one but in the end, perhaps only bCNC uses blocks like this and there are a lot of other GRBL-based controllers/senders not using bCNC.
Perhaps a version of the PP could be added to the bCNC github so that people could try it and tweak it as they see fit?  It shouldn't be difficult to keep it aligned with the official released version which I doubt it's going to change radically anyway.
If anyone has any ideas or suggestions then please comment.

**Comment by Harvie** [comment]
yes, i think that we can include such post-processor in this repository.

but i am not really sure about this:

```
  Copyright (C) 2012-2018 by Autodesk, Inc.
  All rights reserved.
```

There's no mention about license that would explicitly allow us to redistribute the cps code...

**Comment by Bologrew** [comment]
Yes I saw that copyright notice.
When I looked at the "Stroom" Post Processor referenced above, it also says:
"legal = "Copyright (C) 2012-2018 by Autodesk, Inc.";"

So I did a search and came up with this:

https://forums.autodesk.com/t5/fusion-360-support/edit-postprocessor-legal/td-p/7377967

which basically says they are open source and, I quote, "you can edit them and save them however you'd like! "
Looks legal to me. :-)

**Comment by Harvie** [comment]
i don't think it's that easy. quoting someone somewhere on forum is not a license.

we need original author and all contributors of that file to agree on license terms and add that info to the file next to the copyright notice.

or at least find some statement on autodesk website saying exact terms under which you can "edit them and save them however you'd like!"

**Comment by Bologrew** [comment]
Well the guy making the statement was the Autodesk Product Support Specialist but perhaps this additional link will help:

https://forums.autodesk.com/t5/hsm-post-processor-forum/hsm-post-adjustments-needed-find-your-right-contact-here/td-p/6652728

where the Autodesk senior software engineer states:

"After searching for a post online you may find that our stock posts do not meet your needs or that we don’t have the post you are looking for.  The good news is, all of the post are open source, you can use them without limitation to create one for your own needs."

No I haven't found what the explicit open source license is but again, page 11 Section 1.5 of the Autodesk CAM Post Processor Guide:

https://cam.autodesk.com/posts/posts/guides/Post%20Processor%20Training%20Guide.pdf

says:
"The good news is, all of posts are open source and can be modified without limitation to create the post you need."
Hope that helps.

**Comment by Harvie** [comment]
>  The good news is, all of posts are open source and can be modified without limitation to create the post you need.

I can't see anything regarding "redistribution" i can only see that it can be modified. I believe this is OK to redistribute. But to stay out of trouble we still need such code to come with "license". Especialy when big closed source company like Autodesk is in the game.

**Comment by Bologrew** [comment]
I agree it is wise to be cautious and an explicit notice of licence (like BSD) would have removed all doubt.
Now I'm not a lawyer but they do say that if you haven't got the technical ability to modify the post processor yourself, you can give it to someone else to do the edits for you.  The only way you can legally do that is if you have been granted redistribution rights.
I have nothing further to add to this discussion at this time.

**Comment by Harvie** [comment]
Ok. i think i've found compromise. I've put the postprocessor to official bCNC wiki:
https://github.com/vlachoudis/bCNC/wiki/Fusion-360

Which is even better, because it's currently editable by public, so you can continue to improve it and share the latest progress with everyone.
