### ISSUE TITLE
Status bar not working when a code runs a second time

### ISSUE THREAD

**Issue by einencool** [vlachoudis/bCNC#1031]
(Copied from issue #885)

I've got one question, but I didn't know, if it is a new "issue" or not.
But with a Version from August I was working on till now, that issue wasn't there.

The first time I start a program everything is fine, but the next parts, the status bar won't work any more.

This is the status bar when the program is running the first time
![mit statusleiste](https://user-images.githubusercontent.com/37541729/47934725-6f83a200-ded8-11e8-9e09-bdc504193570.JPG)

after the first job, it shows me how long the program was running etc..
![nach 1 durchlauf](https://user-images.githubusercontent.com/37541729/47934762-8fb36100-ded8-11e8-9947-ebcaaaa2504a.JPG)

but when I start the next program, the status bar doesn't show anything
![start 2 durchlauf](https://user-images.githubusercontent.com/37541729/47934792-ace82f80-ded8-11e8-8845-477ef29646b4.JPG)
nothing about the buffer, or how long the program will run etc...

can you help me in this case?

This is a message when I close bCNC
![bcnc error](https://user-images.githubusercontent.com/37541729/47934856-dd2fce00-ded8-11e8-832b-2d849cc99f5a.JPG)

Thank you in advance
Greets Chris

_Originally posted by @einencool in https://github.com/vlachoudis/bCNC/issues/885#issuecomment-435475329_

**Comment by Harvie** [comment]
try now

**Comment by einencool** [comment]
Hi @Harvie,

Tried today with Python 2.7.15 but this issue is still alive ...
![running without status bar](https://user-images.githubusercontent.com/37541729/48146301-ee9c2000-e2b4-11e8-8bb5-2328fe12f559.jpg)

**Comment by Harvie** [comment]
Do you still have that "monitorserial" error message in cmd window?

**Comment by einencool** [comment]
No, the cmd Box shows nothing like that. 

![cmd box](https://user-images.githubusercontent.com/37541729/48222043-e961d280-e393-11e8-8675-cfdc12b2c4e2.JPG)

This was the cmd Box from yesterday. It was 3x the same small g-code

**Comment by einencool** [comment]
So it seems to be an issue only happening when using the hardware buttons...

**Comment by Harvie** [comment]
Lets wait until #1032 gets resolved. I think this might be already fixed once we figure out what's going on in #1032...

**Comment by einencool** [comment]
I think you might be right 👍
