### ISSUE TITLE
Unable to see "Config", "Controller", "Shortcut", etc. under the Tools tab

### ISSUE THREAD

**Issue by Lester444** [vlachoudis/bCNC#1033]
After loading a newer version of bCNC with the hardware "Run" button ........... 

@Harvie , dunno why but I can no longer see "Config", "Controller", "Shortcut", etc. These used to be under the "Tools" tab.

Is it because I am using "Double Size Icon"? (I need big icons for my touchscreen monitor...... & my stubby fingers)

I had to go back to a previous version of bCNC which I have been using June 2018 (sorry but I can't see the bCNC version number on my screen).  I hope you can fix this since the hardware "Run" button is working great for me.

I am using Raspberry Pi 3, Arduino Uno clone (CH340G), GRBL 1.1f 

reference: Issue #885

**Comment by Lester444** [comment]
I am not able to disable the "double size icon"  because I can't see "Config".

**Comment by Harvie** [comment]
You can disable that in bCNC.ini file

**Comment by Harvie** [comment]
However for me it works in both modes. Are you sure that you have latest bcnc master from git, and you run python2 with numpy module installed?

![image](https://user-images.githubusercontent.com/276504/48063857-8a9b2e00-e1c6-11e8-9f46-32a101dcd2bb.png)

![image](https://user-images.githubusercontent.com/276504/48063827-73f4d700-e1c6-11e8-8672-234764a5d69b.png)

**Comment by Harvie** [comment]
I think i know what is going on. I guess that your screen is too smal... Right?

**Comment by Lester444** [comment]
I am using 1024 x 768 resolution.

Here are some pics:
![double 2](https://user-images.githubusercontent.com/23709087/48095412-a1d22e00-e24f-11e8-8f0d-6f4774b350b6.jpg)
![double 3](https://user-images.githubusercontent.com/23709087/48095422-a696e200-e24f-11e8-83a5-573e6ec8e547.jpg)

I'd rather stick with the double-sized icons to minimize inadvertent mis-pressed icons.  Just trying to avoid a crash. I am using a touchscreen monitor.

**Comment by Harvie** [comment]
This is not really bug. Your screen is just too small :-)
I don't know how to handle this. If i optimize to 1024px There can always be someone with smaller screen who will start complaining. Maybe we can add some kind of scrolling mechanism to ribbon.

But to be honest i don't think that these buttons you have troubles with should be in "tools" tab. I think i will move it to "file" or "control", which is less populated, so that should solve your problem.

**Comment by Lester444** [comment]
I guess I will have to stick to the older version then. It is simple, less bells and whistles, more robust.

Having a reliable g-code sender is much more important to me than one with more features. So far I have machined more than 2,500 individual pieces on my 2x CNC machines and I think that speaks a lot for the robustness of this combination (GRBL & bCNC). And the low resolution display is great for touchscreen applications.... and feeble eyesights.

Thank you @Harvie for your efforts, much appreciated.

@sfinexer, I don't use a keyboard on my CNC machines, so I don't have access to Alt key. The touchscreen serves my needs 99.9% of the time.

**Comment by Lester444** [comment]
>  If i optimize to 1024px There can always be someone with smaller screen who will start complaining.

Look at it from a different light: If you keep on adding buttons then sometime in the future a lot of people will complain.  Not all users will have the same resolution as what you have.

**Comment by Harvie** [comment]
Maybe in meantime you can add some page and photos to wiki about hardware you use in such setup. That might be interresting.

**Comment by Lester444** [comment]
>  cheap raspi lcd

I have this display but gave up on it after 2 days of use. The bCNC icons are terribly small even on double-size, necessitating the use of a stylus pen...... but which didn't work at all because the screen is capacitive-type (it needs some surface area in close proximity to the spot on the screen). So with oily fingers (cutting fluid) trying to press a tiny spot....... that took a lot of attempts and inadvertent runs (the shortcuts I made) before finally hitting the right icon. Very frustrating.

What I'm using now is 15" and it fits the need.

**Comment by Harvie** [comment]
I leave this open, so i know i should look at this before releasing next version.

**Comment by Harvie** [comment]
Can you please test the latest git version? @vlachoudis did some great work and UI should be more compact now!

**Comment by Lester444** [comment]
Acknowledged, @Harvie. Will try it ASAP and report my findings here.

**Comment by Lester444** [comment]
Tried it. Now the "Tools" tab is gone. Can't use this version.  :'(

**Comment by Harvie** [comment]
"Tools" tab is not gone. It was renamed to "CAM" and stuff that wasn't CAM related was moved to another tabs. We did this in order to fit into your little screen.

**Comment by Harvie** [comment]
Also note, that currently there is bug. so if you click on any of these buttons:
![image](https://user-images.githubusercontent.com/276504/50872459-23654a00-13c0-11e9-9682-21afbabfaa5b.png)

you have then to switch to "CAM" tab. we will fix this before release.

**Comment by Lester444** [comment]
OK I see it....... now under "FILE" tab. So I switched off double size icon, exited from bCNC, re-launched bCNC, but now the "Config", "Controller" buttons do not work.

**Comment by Harvie** [comment]
As i said... you have to click "config" and then immediately switch to "CAM" tab. it's a bug.

**Comment by Lester444** [comment]
I don't understand what you wanted me to test....... since you already know there is a bug. Anyway, there's your confirmation that indeed there is a bug.

> Can you please test the latest git version? @vlachoudis did some great work and UI should be more compact now!

**Comment by vlachoudis** [comment]
I've restored the Config inside the "CAM". Unfortunately is not straight forward to move it
to the more logical place of "File" tab

**Comment by sfinexer** [comment]
Well, there is simply no logic.
Tab named as:
```
	__doc__ = _("GCode manipulation tools and user plugins")
	_name_  = N_("CAM")
```

Therefore, it is necessary to remove the controller parameters from it, you need to create a new tab, and there ONLY settings should be placed.

**Comment by Harvie** [comment]
> Therefore, it is necessary to remove the controller parameters from it, you need to create a new tab, and there ONLY settings should be placed.

Thanks for clarification. PR welcome!

**Comment by sfinexer** [comment]
> > Therefore, it is necessary to remove the controller parameters from it, you need to create a new tab, and there ONLY settings should be placed.
> 
> Thanks for clarification. PR welcome!

Because it is necessary to use "rapid application development". And do ALL visual manipulations using the CURSOR, and not write something there in a text file. Now 21st century.

Maybe someone wants to help, but cannot (((You have to rewrite everything using wxWidgets, for example, if you need to cross-platform.

After all, this is a GUI and not a console program for various calculations.

**Comment by Harvie** [comment]
> You have to rewrite everything using wxWidgets, for example, if you need to cross-platform.

No need to discuss this here, there are already other issues on this topic.
I've even tried to build new UI using GTK3 builder. I think it's nice solution, because you have separate UI definition in XML file and you have UI independent code in python. So if you want to change the UI, you just modify the XML without having to modify python (there's "Glade" software do modify it visualy by drag and drop).

**Comment by wilderf353** [comment]
Is there a desire to go to wxPython?

**Comment by Harvie** [comment]
> Is there a desire to go to wxPython?

No. Why? I think GTK3 builder is much better concept.

**Comment by lyatesbme** [comment]
HI Harvie
Thanks for the include to this thread. I thought that others would have experienced this issue. I noticed on the Wiki for bCNC a Video from a daSamo123 on Youtube that shows a 5 inch LCD display with the bCNC fitted and with a right side and bottom side scroll bar. Was this an earlier version or have I missed something in my setup.

Many Thanks

**Comment by art-x** [comment]
I needed to have bCNC on a 3.5 inch RPI display (on my Raspberry Pi 3a) with touchscreen. After alot of tweaking in the GUI I managed to get all main components within the confines of 480 x 320 (landscape) TFT.
A lot of the configuration worked out as expected, except for the DRO and Ribbons (I wanted the icons without text as much as possible due to space restrictions).
It required me to change some of the source code to make things fit.
When started with -f (fullscreen), all common functionality is accessible.


This is the final result: (3.5 inch 480 x 320 TFT RPI touch screen)
![20200406_112011](https://user-images.githubusercontent.com/6962116/78543808-7f07c880-77f9-11ea-903e-a5128541a435.jpg)
![20200406_112110](https://user-images.githubusercontent.com/6962116/78543840-8a5af400-77f9-11ea-9458-e40feacb57c1.jpg)
![20200406_112150](https://user-images.githubusercontent.com/6962116/78543852-8f1fa800-77f9-11ea-947a-42da65c94507.jpg)


If anyone is interested, I'll commit the changes I made. 
Harvie, it is crude code for now, but I feel it might be feasable to incorporate this in the config?

**Comment by Harvie** [comment]
> Harvie, it is crude code for now, but I feel it might be feasable to incorporate this in the config?

But that would limit functionality for users with regular sized monitors right?

And the config/controller buttons are still unavailable. But i have some ideas how to improve this situation... I will commit it later...

**Comment by Harvie** [comment]
I've fixed the original problem of @Lester444 so i closed this issue.
@art-x if you have some other problem, please open separate issue.

**Comment by BjarneJensen** [comment]
@art-x I am trying to do the same as you but cannot seem to find the right settings to edit. I changed some font settings and tried looking at the control page code but could not figure it out. Sorry I know this is closed but hopefully it was recent enough that you remember. Thanks!

**Comment by RemyFr** [comment]
> 
> 
> I needed to have bCNC on a 3.5 inch RPI display (on my Raspberry Pi 3a) with touchscreen. After alot of tweaking in the GUI I managed to get all main components within the confines of 480 x 320 (landscape) TFT.
> A lot of the configuration worked out as expected, except for the DRO and Ribbons (I wanted the icons without text as much as possible due to space restrictions).
> It required me to change some of the source code to make things fit.
> When started with -f (fullscreen), all common functionality is accessible.
> 
> This is the final result: (3.5 inch 480 x 320 TFT RPI touch screen)
> ![20200406_112011](https://user-images.githubusercontent.com/6962116/78543808-7f07c880-77f9-11ea-903e-a5128541a435.jpg)
> ![20200406_112110](https://user-images.githubusercontent.com/6962116/78543840-8a5af400-77f9-11ea-9458-e40feacb57c1.jpg)
> ![20200406_112150](https://user-images.githubusercontent.com/6962116/78543852-8f1fa800-77f9-11ea-947a-42da65c94507.jpg)
> ![20200406_113532](https://user-images.githubusercontent.com/6962116/78544769-f1c57380-77fa-11ea-9eb9-6b229c4e419d.jpg)
> 
> If anyone is interested, I'll commit the changes I made.
> Harvie, it is crude code for now, but I feel it might be feasable to incorporate this in the config?

Hello art-x,

Your configuration is exactlly what i am looking for my home made CNC, could you give us your config/protocol to have this result ?

You will save me, it is so frustrating to be blocked in this step.

Remy

**Comment by kd6vpe** [comment]
Wish this setup could be shown. It is what I could use also. At the moment I just use a wireless keyboard and the arrow keys to control my jogging. Not able to control the movement distance this way though like setting to .1 inches.

**Comment by intelka-net** [comment]
> 

Hi! Could you please share your config file? Or where exactly did you change the layout. Thank you
