### ISSUE TITLE
g-code file updated outside of bCNC

### ISSUE THREAD

**Issue by kfmut** [vlachoudis/bCNC#1034]
If g-code file was updated outside of bCNC, app asks for it's reload and if I press 'No' it's asks again and again and again, looks like 'No' isn't right answer here :-)

bCNC version is from 21st of October.

**Comment by Harvie** [comment]
What platform do you use?

**Comment by kfmut** [comment]
> What platform do you use?

It's RPI with raspbian/debian-jessie

**Comment by Harvie** [comment]
should be fixed now
