### ISSUE TITLE
Correct Z machine Safe button

### ISSUE THREAD

**Issue by MARIOBASZ** [vlachoudis/bCNC#1039]
Good improvement to add the buttons.
In Z machine Safe eliminate line G54, it is dangerous!
Without that line it remains in current W Pos.
Suggested improvement:
To be able to visualize the current Parameters of End mil, Z safe, surface, etc

**Comment by Harvie** [comment]
Currently we have this:

```
name.2 = Safe Z
icon.2 = rapid
tooltip.2 = Go to Safe Z
command.2 = G90G0Z[safe]
```

If i add G54 it might be dangerous, because you might not have G54 properly zeroed when you work in different offset.

**Comment by MARIOBASZ** [comment]
I have downloaded the new version
Loaded with Z Safe button:
G53 g0 Z-2
G54
we talk about the same thing: Delete line G54

**Comment by Harvie** [comment]
I have no G54

![image](https://user-images.githubusercontent.com/276504/48271801-76ad3180-e43d-11e8-9a41-069569c93789.png)

**Comment by Harvie** [comment]
Maybe it's just in your bCNC.ini

**Comment by MARIOBASZ** [comment]
Thanks. 
Also look at the go to z safe machine button. Hugs.

**Comment by Harvie** [comment]
don't know what do you mean.

**Comment by MARIOBASZ** [comment]
This button
![image](https://user-images.githubusercontent.com/11743403/48273794-8e29f180-e420-11e8-8b81-3635359ab4af.png)
