### ISSUE TITLE
Linearize: Ignore linearize straight lines

### ISSUE THREAD

**Issue by MARIOBASZ** [vlachoudis/bCNC#1041]
Linearize subvidivide all the lines of the block,including the straight lines.
It would be good to work as in the Drill plugin: the routes come without curved segments, but do not modify in the straight ones.
I have not been able to realize where this plugin performs this task (someone helps me so I keep learning?). Result: many fewer lines in the block.

**Comment by Harvie** [comment]
![image](https://user-images.githubusercontent.com/276504/48414503-3a364a00-e74b-11e8-8d02-2848f758e962.png)
