### ISSUE TITLE
Danger: Error in Pocket operation within profile

### ISSUE THREAD

**Issue by MARIOBASZ** [vlachoudis/bCNC#1046]
First time I have an error in pocket operation. !!!
A segment is outside the shape!
I never had this problem before.
(I have been able to clean it with difference plugin, but this error calls my attention)

![image](https://user-images.githubusercontent.com/11743403/48633385-f8eba780-e9a1-11e8-9003-b9e05b53e250.png)

I upload the example.of the problem
End mil 0.10
[pocket_problem.txt](https://github.com/vlachoudis/bCNC/files/2590019/pocket_problem.txt)

**Comment by MARIOBASZ** [comment]
Sorry, Sorry, the error occurs with pocket in profile plugin

**Comment by Harvie** [comment]
I will rewrite the pocket and profile completely.
