### ISSUE TITLE
Raspberry bCNC hangs

### ISSUE THREAD

**Issue by jarnoburger** [vlachoudis/bCNC#1048]
I try to start bCNC again , but it will not start.
If i start in terminal it shows this in terminal: 
GRBK1
grbl1 loaded
SMOOTHIE
smoothie loaded
GRBL0
grbl0 loaded
test super
test super
etc
ctrlist
test super.

And i get a empty userinterface that hangs.
If i download a other one , i get the same.
Pls help me :)

**Comment by Harvie** [comment]
Do you have numpy installed?

**Comment by jarnoburger** [comment]
I solved it !
The problem was the config file in directory /home/pi/.bCNC .
This file was  hidden , so you should show hidden files in that folder (Ctrl-H).
And then remove or fix it.

**Comment by Harvie** [comment]
> And then remove or fix it.

What kind of bug was in that file?

**Comment by jarnoburger** [comment]
I dont know , i think i checked 'connect at startup'. Not sure...

**Comment by Harvie** [comment]
Oh yes. This feature can be problematic :-(
