### ISSUE TITLE
Connection problem and possible fix

### ISSUE THREAD

**Issue by carlosgs** [vlachoudis/bCNC#105]
Hi, I've had the following problem: when connecting to GRBL from bCNC the connection succeeded but the machine did not responded to any command. I'm using Fedora.  

After a bit of trial and error I ended up changing Sender.py:~368  
from:  
```
		self.serial.flushInput()
		self.serial.setDTR(1)
		self.serial.write(b"\r\n\r\n")
```
to:  
```
		self.serial.flushInput()
		self.serial.setDTR(1)
		time.sleep(1)
		self.serial.write("\n")
```

Now it works fine. I want to think that the delay is what helps, but I forgot to test this more thoroughly (whether b"\r\n\r\n" vs "\n" makes any difference, smaller delay...). Will write back tomorrow after more tests.
Cheers,
Carlos

PS: Thank you for making bCNC, it is a wonderful tool!!

**Comment by vlachoudis** [comment]
Thanks I've added the additional delay of 1s. Originally I had 2s delay but at some point was reduced to 1s and was working, maybe it was on the limit.
