### ISSUE TITLE
Operations Cut, profile, pocket, repeat the route twice.

### ISSUE THREAD

**Issue by MARIOBASZ** [vlachoudis/bCNC#1052]
I can not understand the reason, but if I want to do any operation in the example of #1047, repeat the route in each height of Z twice

**Comment by Harvie** [comment]
It's already twice in the file:

![image](https://user-images.githubusercontent.com/276504/48774151-b1c72480-ecc9-11e8-8219-5bef98a82282.png)

**Comment by Harvie** [comment]
#1081
