### ISSUE TITLE
pip install Error

### ISSUE THREAD

**Issue by colinluthier** [vlachoudis/bCNC#1066]
I was trying out the new pip install feature as it makes it easier to upgrade. I am using a rPi 3+ with Debian 9.4. I get this output after typing:

sudo pip install bCNC

Collecting bCNC
  Downloading https://files.pythonhosted.org/packages/35/ad/1e81e777d29e3d3725b368ecc98d97482a12a3dcd07a893b916bc71a13b2/bCNC-0.9.14.42.tar.gz (1.1MB)
    100% |████████████████████████████████| 1.1MB 201kB/s 
Requirement already satisfied: Pillow>=4.0 in /usr/lib/python2.7/dist-packages (from bCNC)
Requirement already satisfied: numpy>=1.12 in /usr/lib/python2.7/dist-packages (from bCNC)
Collecting opencv-python>=2.4 (from bCNC)
  Could not find a version that satisfies the requirement opencv-python>=2.4 (from bCNC) (from versions: )
No matching distribution found for opencv-python>=2.4 (from bCNC)

Typing:

~ $ python
Python 2.7.13 (default, Nov 24 2017, 17:33:09) 
[GCC 6.3.0 20170516] on linux2

**Comment by Harvie** [comment]
See #1063
