### ISSUE TITLE
G-code is not loading correctly

### ISSUE THREAD

**Issue by copierboy** [vlachoudis/bCNC#1075]
When I load a g-code file to drill a grid pattern for my bed, I get a file that shows a small rectangle in front of each letter or number in the code rendering the code unusable. I am set up to use bCNC on my Raspberry Pi. I am currently running grbl 1.1. The g-code file was generated from an excel spreadsheet from the Root 3 site. I can load the g-code file into Candle and it appears to load correctly. I used this g-code several years ago to drill my original bed using Repitier and ramps 1.4
;X Axis Step = 90.3333333333333
;Y Axis Step = 101.285714285714
G1 X60.33 Y51.29 Z25 F500
G1 X60.33 Y51.29 Z-19.5 F381
G1 X60.33 Y51.29 Z25 F500
G1 X60.33 Y152.57 Z25 F500
G1 X60.33 Y152.57 Z-19.5 F381
G1 X60.33 Y152.57 Z25 F500
G1 X60.33 Y253.86 Z25 F500
G1 X60.33 Y253.86 Z-19.5 F381
G1 X60.33 Y253.86 Z25 F500
G1 X60.33 Y355.14 Z25 F500
G1 X60.33 Y355.14 Z-19.5 F381
G1 X60.33 Y355.14 Z25 F500
G1 X60.33 Y456.43 Z25 F500
G1 X60.33 Y456.43 Z-19.5 F381
G1 X60.33 Y456.43 Z25 F500
G1 X60.33 Y557.71 Z25 F500
G1 X60.33 Y557.71 Z-19.5 F381
G1 X60.33 Y557.71 Z25 F500
G1 X150.67 Y51.29 Z25 F500
G1 X150.67 Y51.29 Z-19.5 F381
G1 X150.67 Y51.29 Z25 F500
G1 X150.67 Y152.57 Z25 F500
G1 X150.67 Y152.57 Z-19.5 F381
G1 X150.67 Y152.57 Z25 F500
G1 X150.67 Y253.86 Z25 F500
G1 X150.67 Y253.86 Z-19.5 F381
G1 X150.67 Y253.86 Z25 F500
G1 X150.67 Y355.14 Z25 F500
G1 X150.67 Y355.14 Z-19.5 F381
G1 X150.67 Y355.14 Z25 F500
G1 X150.67 Y456.43 Z25 F500
G1 X150.67 Y456.43 Z-19.5 F381
G1 X150.67 Y456.43 Z25 F500
G1 X150.67 Y557.71 Z25 F500
G1 X150.67 Y557.71 Z-19.5 F381
G1 X150.67 Y557.71 Z25 F500
G1 X241.00 Y51.29 Z25 F500
G1 X241.00 Y51.29 Z-19.5 F381
G1 X241.00 Y51.29 Z25 F500
G1 X241.00 Y152.57 Z25 F500
G1 X241.00 Y152.57 Z-19.5 F381
G1 X241.00 Y152.57 Z25 F500
G1 X241.00 Y253.86 Z25 F500
G1 X241.00 Y253.86 Z-19.5 F381
G1 X241.00 Y253.86 Z25 F500
G1 X241.00 Y355.14 Z25 F500
G1 X241.00 Y355.14 Z-19.5 F381
G1 X241.00 Y355.14 Z25 F500
G1 X241.00 Y456.43 Z25 F500
G1 X241.00 Y456.43 Z-19.5 F381
G1 X241.00 Y456.43 Z25 F500
G1 X241.00 Y557.71 Z25 F500
G1 X241.00 Y557.71 Z-19.5 F381
G1 X241.00 Y557.71 Z25 F500
G1 X331.33 Y51.29 Z25 F500
G1 X331.33 Y51.29 Z-19.5 F381
G1 X331.33 Y51.29 Z25 F500
G1 X331.33 Y152.57 Z25 F500
G1 X331.33 Y152.57 Z-19.5 F381
G1 X331.33 Y152.57 Z25 F500
G1 X331.33 Y253.86 Z25 F500
G1 X331.33 Y253.86 Z-19.5 F381
G1 X331.33 Y253.86 Z25 F500
G1 X331.33 Y355.14 Z25 F500
G1 X331.33 Y355.14 Z-19.5 F381
G1 X331.33 Y355.14 Z25 F500
G1 X331.33 Y456.43 Z25 F500
G1 X331.33 Y456.43 Z-19.5 F381
G1 X331.33 Y456.43 Z25 F500
G1 X331.33 Y557.71 Z25 F500
G1 X331.33 Y557.71 Z-19.5 F381
G1 X331.33 Y557.71 Z25 F500
G1 X421.67 Y51.29 Z25 F500
G1 X421.67 Y51.29 Z-19.5 F381
G1 X421.67 Y51.29 Z25 F500
G1 X421.67 Y152.57 Z25 F500
G1 X421.67 Y152.57 Z-19.5 F381
G1 X421.67 Y152.57 Z25 F500
G1 X421.67 Y253.86 Z25 F500
G1 X421.67 Y253.86 Z-19.5 F381
G1 X421.67 Y253.86 Z25 F500
G1 X421.67 Y355.14 Z25 F500
G1 X421.67 Y355.14 Z-19.5 F381
G1 X421.67 Y355.14 Z25 F500
G1 X421.67 Y456.43 Z25 F500
G1 X421.67 Y456.43 Z-19.5 F381
G1 X421.67 Y456.43 Z25 F500
G1 X421.67 Y557.71 Z25 F500
G1 X421.67 Y557.71 Z-19.5 F381
G1 X421.67 Y557.71 Z25 F500

**Comment by Harvie** [comment]
> When I load a g-code file to...

How can we debug this, unless you upload the file for us?

**Comment by copierboy** [comment]
I attached the g-code to my original post.

**Comment by Harvie** [comment]
@copierboy so what you did to fix the problem?
