### ISSUE TITLE
Make bCNC MIDI2gcode again!

### ISSUE THREAD

**Issue by Harvie** [vlachoudis/bCNC#1078]
Midi2CNC feature (#132) of bCNC was removed (8ddbadc8814994e5b8d6b14b0d7aa1054c305b1a), because i was not GPLv2, but original author @michthom is willing to dual license it as GPLv2 for us. We should work this out.

I guess i will create pull request to update to GPLv2/3
https://github.com/michthom/MIDI-to-CNC/blob/master/COPYING

**Comment by michthom** [comment]
Look forward to the pull request - sorry I'm being lazy but too much going on at the moment.
