### ISSUE TITLE
Add bindings for numeric keypad - lets you use USB numeric keypad as a pendant

### ISSUE THREAD

**Issue by PhilSalkie** [vlachoudis/bCNC#108]
Hello,

No idea if this is the proper way to submit a patch, but this little change to bCNC.py:

---

310a311
> 		self.bind('<KP_Up>',		self.control.moveYup)
311a313
> 		self.bind('<KP_Down>',		self.control.moveYdown)
312a315
> 		self.bind('<KP_Right>',		self.control.moveXup)
313a317
> 		self.bind('<KP_Left>',		self.control.moveXdown)
314a319
> 		self.bind('<KP_Prior>',		self.control.moveZup)
315a321
> 		self.bind('<KP_Next>',		self.control.moveZdown)

---

lets you use a USB numeric keypad as a pendant.

Thanks!

**Comment by vlachoudis** [comment]
Thank you I've just added them in the master branch

**Comment by PhilSalkie** [comment]
Thanks, glad to help (even in such a small way).


On Sat, Sep 19, 2015 at 12:33:13PM -0700, Vasilis Vlachoudis wrote:
> Thank you I've just added them in the master branch
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/vlachoudis/bCNC/issues/108#issuecomment-141700761

-- 

"The Linux philosophy is 'Laugh in the face of danger'...
Oops, wrong one.  'Do it yourself'...  Yes, that's it."
	- Linus Torvalds
