### ISSUE TITLE
Problem in multiple figures in profile with pockets

### ISSUE THREAD

**Issue by MARIOBASZ** [vlachoudis/bCNC#1082]
If I choose more than one block, with profile only there is no conflict, but if pocket is also chosen, after the first block, the cut is erroneous
Remark: Perform In the correct cut, the output correctly marks 
name; name: 02 
In wrong:
name; name

In the following example, I made a profile out bit 6mm, then profile in + pocket bit 6mm

[PRUEBA union_5.zip](https://github.com/vlachoudis/bCNC/files/2653230/PRUEBA.union_5.zip)

**Comment by Harvie** [comment]
I don't accept issues for pocket/profile problems, because this code will be completely replaced.
