### ISSUE TITLE
Steppers should be locked during tool change

### ISSUE THREAD

**Issue by BernardG** [vlachoudis/bCNC#1144]
I tried tool changing, and it's nice. BUT, during tool change, Steppers motors are not locked. I guess this is not a problem on a machine with leadscrews, but on mine, with belt for X and Y (guess it would be the same with rack and pinions, or chains), motors are basically free wheeling, and it's too easy to move the gantry while changing tools, so the precise position is lost when work resume.

I would believe this is not a big code change, so it would be nice to do it!

**Comment by MARIOBASZ** [comment]
Good idea to implement, in my previous machine with belt, used configuration with the motors always energized

**Comment by Harvie** [comment]
This is most likely HW problem. You should set your GRBL like this: `$1=255`. Otherwise it will always disable motors when not in motion. Not related to bCNC.

https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration#1---step-idle-delay-milliseconds

**Comment by BernardG** [comment]
Ha, OK thanks!
