### ISSUE TITLE
Version 0.9.10 or 0.9.11?

### ISSUE THREAD

**Issue by Andy-ABTec** [vlachoudis/bCNC#1167]
Hi, apologies if I'm being thick here...

Just downloaded 0.9.11 as the "Latest release" but when I run it I'm seeing: -

![image](https://user-images.githubusercontent.com/5175695/52969725-3e58b000-33a9-11e9-9c89-6333bb3d02ce.png)

Really confused now!

**Comment by Harvie** [comment]
Where did you downloaded that from? Maybe try latest git master, there's lot of new stuff and we are heading to release it soon anyway...

**Comment by Andy-ABTec** [comment]
Got it from https://github.com/vlachoudis/bCNC/releases/latest - which is why I was really confused...

I'll try the master

**Comment by Harvie** [comment]
Anyway... I think this update check mechanism can be replaced in future using `pip install --upgrade` command. You can already use it when installing bCNC using `pip`. #1130

**Comment by Andy-ABTec** [comment]
OK Thanks...
