### ISSUE TITLE
Autolevel does not use rapid moves

### ISSUE THREAD

**Issue by FrenkK** [vlachoudis/bCNC#1169]
In 0.9.14, when I do grid levelling, all the moves are performed with the same low probe speed. This makes the levelling take longer than it needs to.
The program should use G0 Xx Yy Fsss for x-y direction moves after each probe (and possibly for lifting the probe too?). As speed value, the "Fast Probe Feed" value in the probing menu should be used. This would save a lot of time and would be more intutive.
A big thank you to everybody working on this awesome project! :)

**Comment by Harvie** [comment]
Can you please provide pull request for this one? Sounds easy to fix...

**Comment by FrenkK** [comment]
I'm a newbie at git and Python, but I'll try.

**Comment by Harvie** [comment]
> I'm a newbie at git and Python

I also was when i first started contributing to bCNC few months ago :-) We need more developers :)

**Comment by FrenkK** [comment]
Ok, this took way too much time, but at least it seems to work. I added the pull request and I now even have a basic idea how Github works :)
