### ISSUE TITLE
Is it possible to read analog values for distance from the probe?

### ISSUE THREAD

**Issue by MARIOBASZ** [vlachoudis/bCNC#1188]
Performing autolevel normally takes a long time for the sequence of operations:
1-go down slowly until touching
    1.1-Enter value to autolevel matrix
2-fast upload
3-move quickly to next point
Repeat from 1

If it could be done in the following way:
0- Go down to operating distance
1-Read distance
    1.1-Enter value to autolevel matrix
2-move at established speed to next point
3-Repeat from 1 (no uploads, no downloads)
It would make the operation much faster.
The reading could be done with an infrared distance sensor (or from the sensor). Is it viable to acquire the values in some way?

**Comment by Harvie** [comment]
I've been thinking about this a lot last year, but i couldn't find any sensor precise enough for my high-res 3D scanning use case. For general autoleveling you might use lidar sensor, but GRBL does not support this, so you will need to modify GRBL yourself.
