### ISSUE TITLE
Slice mesh Issue

### ISSUE THREAD

**Issue by wheemzy1** [vlachoudis/bCNC#1195]
I'm new. I tried to import an .stl file but it says I need to go to Tools ----> Plugin

Problem is: I don't have a tools tab. 

The only tabs I can view are: File, Control, Probe, CAM, Editor

I have version 9.14-dev

I tried expanding the screen size, I have a 32" monitor so this should not be the issue. 

Also, I am using the gnea grbl/mega firmware. Before I go down this road, is this going to be an issue?

Please help.

**Comment by Harvie** [comment]
"Tools" tab was recently renamed to "CAM".
That warning popup haven't reflected that yet...

**Comment by MARIOBASZ** [comment]
@Wheemzy1, @Harvie, I never used slice mesh, I thought it was for 3D milling.
What does it do to import the contours in 3d? Then I guess you can mill (only with the option on) using trochoid 3d, I can add option "normal cut without trochoids" (trocoid diameter = tool diameter). I do not know how to make compensation for 3d tools and I do not have time to investigate.

**Comment by MARIOBASZ** [comment]
@Harvie, I could not import .stl files, my error, from the file? can you send me some file that works to try it?
Another issue: Trochoid 3D can follow a 3d route, I would like to see if it can be applied.

**Comment by Harvie** [comment]
@MARIOBASZ see #1223

**Comment by Harvie** [comment]
These should work:

[sphere.stl.zip](https://github.com/vlachoudis/bCNC/files/3148789/sphere.stl.zip)
[chaos-cam.ply.zip](https://github.com/vlachoudis/bCNC/files/3148790/chaos-cam.ply.zip)
[chaos-cam.stl.zip](https://github.com/vlachoudis/bCNC/files/3148791/chaos-cam.stl.zip)
