### ISSUE TITLE
Drag Knife post processor not working with some toolpaths

### ISSUE THREAD

**Issue by Rhysun** [vlachoudis/bCNC#1199]
The drag Knife post processor throws a math domain error with one of my gCode files. But if I enclose...

`angle = degrees(acos(TA.dot(TB)))`

in a `try: except` block, thus...

```
try:
    angle = degrees(acos(TA.dot(TB)))
except:
    continue
```

... the problem goes away. I have absolutely no idea what is going on with this toolpath so the above solution is probably a bit 'hacky'. Anyway, here is the problematic file:

[yrOrsaf3.ngc.zip](https://github.com/vlachoudis/bCNC/files/2999939/yrOrsaf3.ngc.zip)

**Comment by Harvie** [comment]
There was error in math library, fixed that. Thanks for reporting.

**Comment by Harvie** [comment]
BTW would you mind doing some pictures or youtube video about your bCNC dragknife use? I'd love to see how this is usefull to other people and maybe promote the feature a bit :-)

**Comment by MARIOBASZ** [comment]
could you add a site on github or on wiki or slgo, to upload examples, tips, trivia, phytos, videos, experiences, curiosities of bcnc / plugins?

**Comment by Harvie** [comment]
@MARIOBASZ everybody can edit bCNC wiki. Go ahead if you wish. I am going to make some tutorial videos after 0.9.15 release.
