### ISSUE TITLE
Doing "cut" on simple non-closed path will close the path on the bottoming pass

### ISSUE THREAD

**Issue by MrSurly** [vlachoudis/bCNC#1204]
Doing a simple cut of a non-closed path from an SVG:

![image](https://user-images.githubusercontent.com/395016/55048229-b0ee2880-5004-11e9-9be2-e0033833c528.png)

Gives unexpected results in Camotics -- essentially the path is inadvertently closed just before the final bottoming pass:

![image](https://user-images.githubusercontent.com/395016/55048397-425d9a80-5005-11e9-9f5e-04e44f77983d.png)

Looking at [CNC.py:3532](https://github.com/vlachoudis/bCNC/blob/master/bCNC/CNC.py#L3532): `if splitpass: path.invert() #Fixes split ramp case`, commenting out this line fixes the issue.  

I _think_ that since `path.invert()` is called at [line 3515](https://github.com/vlachoudis/bCNC/blob/master/bCNC/CNC.py#L3515) _and_ [line 3518](https://github.com/vlachoudis/bCNC/blob/master/bCNC/CNC.py#L3518) before entering the bottoming block, then this final `path.invert()` shouldn't be necessary, but I'm not entirely sure.

**Comment by Harvie** [comment]
Unfortunately this happend to me out few days ago while doing actual cut. But wasn't sure what happend. Thanks for catching this.

**Comment by MrSurly** [comment]
No problem, would have submitted a PR, but I'm not familiar enough with the code to know for sure if removing line 3532 would cause other problems.

**Comment by Harvie** [comment]
Don't worry, i'll soon take a look myself...

**Comment by Harvie** [comment]
> I'm not familiar enough with the code to know for sure if removing line 3532 would cause other problems.

This was actually the case, but i've managed to untangle the problem and it should be OK in the latest git version...
