### ISSUE TITLE
Network file support

### ISSUE THREAD

**Issue by atrueresistance** [vlachoudis/bCNC#122]
Would it be possible to have network drive support? 

Currently the open menu looks like this:
![capture1](https://cloud.githubusercontent.com/assets/7239809/10336203/b481f208-6cbc-11e5-8308-068eeaacd67f.PNG)

I could be just a dumb user, but I can't seem to get it to change from C: drive. Currently I have my nas attached to the Z: drive. I just can't figure out how to traverse in bCNC. Otherwise great software!

**Comment by Effer** [comment]
Hi @atrueresistance .
I've just made this test in Windows: 
mount a remote disc with net use in Z:

![net use](https://cloud.githubusercontent.com/assets/1007007/10338661/926f40ee-6d07-11e5-9083-fe37e69d841a.png)

then input z: in the "File Name" text box

![zpath](https://cloud.githubusercontent.com/assets/1007007/10338774/1b22c1fe-6d08-11e5-959c-116ae23890ec.png)

Indeed not so user friendly, a list of local disk would be useful.

**Comment by atrueresistance** [comment]
Awesome thanks, silly user error on my part. I kept clicking on the C: next to the directory thinking there would be a dropdown to select another drive.

**Comment by Effer** [comment]
@atrueresistance to be honest, was exactly what I've done the first time ;)

**Comment by vlachoudis** [comment]
I've found on the web that I can get the logical drives with the win32api.
if it works i could add it in the dialog box to propose them

import win32api
drives = win32api.GetLogicalDriveStrings()
drives = drives.split('\000')[:-1]
print drives

**Comment by Effer** [comment]
It works but it seems that win32api is not installed as default.
Dependandy for dependancy, what about psutil?

import psutil
psutil.disk_partitions()

Anyway it's a minor issue IMO.

**Comment by atrueresistance** [comment]
Thank you!
