### ISSUE TITLE
Port selection

### ISSUE THREAD

**Issue by sfinexer** [vlachoudis/bCNC#1220]
There used to be a normal selection of a maximum of two ports.
Now is nonsense. If you don’t know, you don’t know what to choose !!!.
![Screenshot_20190425_182350](https://user-images.githubusercontent.com/13809436/56747955-9506af80-6787-11e9-977f-f1de05eaa0bc.png)

**Comment by Harvie** [comment]
The list of ports is ordered in way, that the most useful ones are on top in the first group.
Be assured, that the other ports in the list also have good use... For example:

If you have multiple arduinos, you can use "hwgrep" with serial id, so you will always connect to the right machine (ttyUSB0,1,2,... numbering can change if you reboot / disconnect the arduinos). But not every usb serial chip provides serial number. But genuine FTDI chips do provide it. There are even hwgrep options that identify arduinos based on other variables (eg. based on which physical usb socket you plugged it into).

If you have some issues with serial communication, you can use "spy" options to enable serial debug.

The "socket" is good for connecting to remote GRBL controllers attached using terminal server (eg. raspberry or mikrotik router with usb or serial port) or GRBL ports to wifi enabled esp32 controller.

If you don't know how to use these features, just stick to the first group.
