### ISSUE TITLE
enlarge buttons

### ISSUE THREAD

**Issue by vair327** [vlachoudis/bCNC#1222]
Would it be possible to enlarge the buttons for each function i.e. zero axies and motion control, this would make much easier to use a touch screen.

**Comment by Harvie** [comment]
Are you aware of this feature?

![image](https://user-images.githubusercontent.com/276504/57105509-3f07ae00-6d2b-11e9-9d9c-b7ca71b70c38.png)

**Comment by vair327** [comment]
This command does not increase the size of the control buttons only the icon for home and exit and such. I was asking about the buttons for setting zero and directional control they are small for touch screen.

**Comment by Harvie** [comment]
![image](https://user-images.githubusercontent.com/276504/57182140-397da580-6e9c-11e9-9fc6-e5f0762312ed.png)

**Comment by vair327** [comment]
Perfect!

Thank You
