### ISSUE TITLE
WIth "Dark" theme,MAIN MENU BAR is Light GRAY with the TEXT in WHITE!!

### ISSUE THREAD

**Issue by lumanga** [vlachoudis/bCNC#1238]
Using a "Dark" theme, the MAIN MENU BAR is "Light GRAY" coloured  with the TEXT in WHITE.
In this case is impossible to read the text!

I have found a similar issue here:
https://github.com/vlachoudis/bCNC/issues/450

but witout a solution.. Can be now solved with version bCNC 0.9.14

**Comment by ptvoinfo** [comment]
I've migrated to Ubuntu 18.04 and got the exactly the same problem :(.

**Comment by Harvie** [comment]
Duplicate of #511
