### ISSUE TITLE
bCNC not connected to CNC but Connection is establish with Grbl

### ISSUE THREAD

**Issue by excury** [vlachoudis/bCNC#1241]
Hi I am unable to connect my controller to bCNC. I open the serial port but the status stay on Not connected with the orange background. It also said Connection is establish with Grbl, see screen shot.
> 
> ![screen shot 2018-05-10 at 17 58 27](https://user-images.githubusercontent.com/39164711/39882463-c83e81c2-547b-11e8-8028-f6e3863019b9.png)

The control module does not work, I cannot control the motor. When I send a command, noting happen.
Can anyone help?

I'm using a Rasberry Pi.
Ive tried turning on and off the serial port.
I have tried the $10=1 that was propose earlier.
I have tried to do a software reset  of the controller and the hard reset but it does not seem to complete.
V 0.9.14 8th Jan.
 
I am using a usb to connect to Eleksmaker Mana Briver Board.
I am using TTYusb0

If anyone could help me to solve this issue that would be awesome!

**Comment by tarbard** [comment]
I had the same problem until I set $10=3, now it's fine again 

I'm on GRBL 0.9, The docs seem to suggest $10=1 as the safe default for this version of GRBL but I get the same connection problem as you do when set to that.

**Comment by excury** [comment]
I change the set $10=3 but the status did not change. 
The motor knob are now hard, that is a change, so I suppose there is communication. But I cannot control the motor from the control panel. When I press on the arrow to move the laser, nothing happen.

**Comment by Harvie** [comment]
Please try latest pip version. Also maybe upgrade python to latest 2.7

**Comment by BlakusSenior** [comment]
It's not connected but Ihave bCNC installed and working but I cannot call up the configuration menu ie. entereing $$ does nothing. Anyone help please?

**Comment by Harvie** [comment]
@BlakusSenior please open separate issue.

**Comment by Harvie** [comment]
@excury have you resolved the problem?

**Comment by BlakusSenior** [comment]
Yes thanks Harvie all good.

**Comment by BlakusSenior** [comment]
Whoops !!

**Comment by Harvie** [comment]
> Yes thanks Harvie all good.

And bCNC still says "Not connected"? Can you please use bCNC spy:// feateure to capture serial communication to see what's going on?

**Comment by excury** [comment]
Yes, thank for asking,  the micro-USB connector on the controller was broken. I fix it and now it work.

**Comment by Harvie** [comment]
LOL

**Comment by kd6vpe** [comment]
I just installed pip install bCNC on a rpi 3+. I can not get it to show connected status. It runs g-code files but does not show updates to bit location on the grids nor the files image. Anyone have any insite to this problem. It used to work on my old pi2.

**Comment by AlvaroRey** [comment]
Comment from 2022 with the same topic, This problems happens to me from time to time, what I do is to Upload an Epprom clear code using the arduino IDE to my Arduino UNO ( in my case, I'm using a CNC shield)) and then reinstall GRBL. Usually this works for me. Just in case, someone is dealing with this problem, and modify de $10 doesn't help at all.

**Comment by Carmah565** [comment]
i have this problem for a couple of days now, i reinstalled bcnc, python ,pip , arduino grbl, i tried to change the status 10$, but bcnc does not accept any command in the terminal and continues as not connected. Does anyone have any other suggestions?

**Comment by luckypickle1** [comment]
I already had this problem, I solved it by replacing the Arduino IC chip with another one.

**Comment by Carmah565** [comment]
I solved my problem at the time, I was using a valve to activate a cylinder in my machine, and this valve was creating a counter electromotive current and affecting the USB input communication. I put a diode in the valve and it solved it easily, but it took me a while to figure it out.
