### ISSUE TITLE
AttributeError: DROFrame instance has no attribute 'wcsSet' using Set WPOS

### ISSUE THREAD

**Issue by frado65** [vlachoudis/bCNC#1245]
Hi, I've updated the bCNC (0.9.14-dev) on my ubuntu 18.04 but now Set WPOS seems do not work, if I click it bCNC freeze and the only solution is to kill it.
The console write message "AttributeError: DROFrame instance has no attribute 'wcsSet'".

**Comment by Harvie** [comment]
Just checked and i can confirm this. We need to fix this.

**Comment by Harvie** [comment]
Can you check agian pls?

**Comment by frado65** [comment]
Hi, I've added a screenshot about the new test.
![Screenshot from 2019-07-01 14-59-10](https://user-images.githubusercontent.com/52099854/60438374-d6488f00-9c10-11e9-818e-a88a23e93e55.png)

**Comment by frado65** [comment]
Now I've applied the patch and it seem to work! :) :+1: 
![Screenshot from 2019-07-01 15-11-59](https://user-images.githubusercontent.com/52099854/60439188-a5695980-9c12-11e9-8860-336a975c3e5e.png)
