### ISSUE TITLE
CNC 2417 MILLING Z AXIS AND PROBE AND COMMAND PROBLEM

### ISSUE THREAD

**Issue by zaki554** [vlachoudis/bCNC#1246]
we want to know that how the z axis will be set and how we get the thickness by installing the probe and please tell about the command how should it be used in GRBL CONTROL 0.8

**Comment by Harvie** [comment]
1.) Please upgrade your firmware to latest GRBL (currently version 1.1f). Version 0.8 have some issues. You can download it here https://github.com/gnea/grbl also they have instructions on how to install.

2.) Some instructions on autoleveling are here:

https://github.com/vlachoudis/bCNC/wiki/AutoLevel
https://www.youtube.com/results?search_query=bcnc+autolevel

**Comment by zaki554** [comment]
Thanks..kindly tell me how can we set the depth and find the distance by
probe and what is hard limit error.I am using the B CNC software.

**Comment by Harvie** [comment]
Do you have hardware ready for this? Probe correctly connected to arduino with grbl?

These are relevant controls in bCNC to start experimenting:

![image](https://user-images.githubusercontent.com/276504/60814634-3f428080-a196-11e9-8af1-efc5cbc017ed.png)
