### ISSUE TITLE
Difference: anomalous behavior

### ISSUE THREAD

**Issue by MARIOBASZ** [vlachoudis/bCNC#1251]
Difference presents problems with curved segments and more than one block to process. If I modify "island" with linearize, it works correctly.
 
isolate
![image](https://user-images.githubusercontent.com/11743403/61174315-b9974a00-a574-11e9-9563-b0dd9af42e89.png)

correct in the first figure analyzed, error below
![image](https://user-images.githubusercontent.com/11743403/61174336-05e28a00-a575-11e9-89ad-52d0a45f03ca.png)

linearized: works correctly
![image](https://user-images.githubusercontent.com/11743403/61174320-c7e56600-a574-11e9-9975-d1ba256bac9a.png)

**Comment by Harvie** [comment]
Difference is not real feature... At least not yet. It's just tiny step that i do in developing larger feature. It's development code not really meant for end users.
