### ISSUE TITLE
"Profile" raises exception when being applied to simple (closed) circle

### ISSUE THREAD

**Issue by ZhukovAN** [vlachoudis/bCNC#126]
For example, take this sketch: https://dl.dropboxusercontent.com/u/37109457/Untitled1.dxf and try to profile inner circle. Because of segment.start and segment.end are the same, resulting opath = path.offset(D*offset, newname) is empty. This results to exception in further opath.removeExcluded(path, D*offset) call

**Comment by vlachoudis** [comment]
Thank you @ZhukovAN I missed to check on simple circles. Now it should work.
