### ISSUE TITLE
Raspberry Pi/ bCNC for X Carve - autostart program?

### ISSUE THREAD

**Issue by metb40** [vlachoudis/bCNC#1267]

**Comment by metb40** [comment]
I would like the program to auto-start/boot-up directly to bCNC without having to launch it from the desktop { python -m bCNC }. Most of the ways I have seen posted for other programs to auto-start were a bit dated and I have had no luck getting them to work with bCNC. Any suggestions?

**Comment by Harvie** [comment]
This is unrelated to bCNC and you would be much better discussing this with support of desktop environment that you are currently using. I suppose that you want to start bCNC everytime your raspberry boots Linux. It goes like this:

1.) You need your system to be configured to automaticaly login on boot
2.) You need to add bCNC to autostart of your desktop environment

This can be done by putting `.desktop` file to `~/.config/autostart`. If you manage to do this, please describe the process on our wiki: https://github.com/vlachoudis/bCNC/wiki other users might appreciate it.  Thanks :)
