### ISSUE TITLE
Saving probe data

### ISSUE THREAD

**Issue by pommen** [vlachoudis/bCNC#127]
Hi,

First off: Awesome piece of software, I use it all the time for PCB milling.
I updated yesterday to lastest version and cant see where to save the probe data.

Usually i probe the whole PCB, save the probedata and then mill the text layer. Then I load the top side file and load the probedata and continue milling.

Is the functionallity to save the probefile gone, or am I searching in the wrong places?

Kepp up the good work!

/Peter

**Comment by vlachoudis** [comment]
In the effort to reduce buttons in the interface the saving/loading of the probe data is done with the same save/load button for the gcode. Simply change the extension to probe

**Comment by pommen** [comment]
Ahh I see, thanks!

/Peter
