### ISSUE TITLE
bCNC blocks when spindle motor turns on

### ISSUE THREAD

**Issue by Toscano2019** [vlachoudis/bCNC#1271]
Hello
my cnc works perfectly when the spindle motor is off. When I turn it on and start the execution of the g-code, bCNC stops immediately or at most after a few seconds.
This is what Python reports:

Controller state changed to: Idle (Running: False)
Exception in thread Thread-2:
Traceback (most recent call last):
  File "c:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "c:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "c:\Python27\lib\site-packages\bCNC\Sender.py", line 657, in serialIO
    self.mcontrol.viewStatusReport()
  File "c:\Python27\lib\site-packages\bCNC\controllers\_GenericController.py", line 87, in viewStatusReport
    self.master.serial.write(b"?")
  File "c:\Python27\lib\site-packages\serial\serialwin32.py", line 313, in write
    raise writeTimeoutError
SerialTimeoutException: Write timeout

Will clean after this operation

Does anyone know what happens?
Thanks

**Comment by Harvie** [comment]
This sounds pretty much like EMI issue. What kind of spindle do you have? What kind of cables do you use? Send some photos of your machine :-)

**Comment by MARIOBASZ** [comment]
Most likely, between electrical noise through the usb cable, it should be as short as possible, away from noise sources, and not parallel (not a bcnc problem)

**Comment by Toscano2019** [comment]
Thanks for the answers.
some additional information:
Self-made CNC
shielded cable 4 wires awg26, shield not connected..
spindle motor https://it.aliexpress.com/item/32962395557.html?spm=a2g0o.placeorder.0.0.1b36580aOr8l52
I tried to separate the motor cable, which passed with the others, but does not change anything.
I enclose some photos of my masterpiece :-)

![20190830_091601](https://user-images.githubusercontent.com/46495609/64001755-cbbf4e80-cb08-11e9-9b2f-7375df2130d3.jpg)
![20190830_091612](https://user-images.githubusercontent.com/46495609/64001829-edb8d100-cb08-11e9-9540-24603bf940b7.jpg)
![20190830_091617](https://user-images.githubusercontent.com/46495609/64001866-0de89000-cb09-11e9-909a-36c83b1df72c.jpg)
![20190830_091631](https://user-images.githubusercontent.com/46495609/64001914-29539b00-cb09-11e9-8bc9-c0b5193e651f.jpg)

Be understanding .. it's the first one I make..

**Comment by Toscano2019** [comment]
last thing..
Uno and CNC shield   https://it.aliexpress.com/item/32950052187.html?spm=a2g0s.9042311.0.0.27424c4dZPcZYP

**Comment by Harvie** [comment]
Use shielded cable for spindle. I had this exact problem until i used shielded cable for spindle (shielded stepper cables didn't worked). Also switched to shorter USB cable and shorter cables in general. But shielded spindle cable did the trick.
Always connect the shields of shielded cables! There is very little that shielded cable can do if it's not properly grounded.

You need to setup your machine in a way that it has one central grounding point and all shields and grounds meet there:

![image](https://user-images.githubusercontent.com/276504/64003460-9288dd80-cb0c-11e9-9f8b-1b39c590272c.png)

![image](https://user-images.githubusercontent.com/276504/64003518-b3513300-cb0c-11e9-81ed-cbf5805c3c75.png)

![image](https://user-images.githubusercontent.com/276504/64003536-bd733180-cb0c-11e9-8a80-48409159e679.png)

![image](https://user-images.githubusercontent.com/276504/64003566-c9f78a00-cb0c-11e9-9798-437d58d1849d.png)


It might be preferable not to connect shields on the other hand, so you never create ground loop, which might act as coil picking up EMI.

Google "cnc shielding" or "cnc star ground" and stuff like that, you will find lots of info.

**Comment by MARIOBASZ** [comment]
At the end of the race, noise may also appear: try to disable hard limits, use soft limits enabled for safety, the end of the race is useful for homing.
Control the grounding issue

**Comment by Toscano2019** [comment]
Thank you all. I set to work to put into practice what was recommended.
I will let you know the results

**Comment by bobbynohairs** [comment]
Sounds like spindle motor EMF interference to me.

**Comment by Toscano2019** [comment]
I used a shielded cable for spindle motor. Now works fine. thanks all

**Comment by tavolito** [comment]
Hola Toscano tengo el mismo problema , me podrias mandar foros del tipo de cable que usastes , puede ser a mi mail o wattsapp 0054 1149796722     buengueroffgustavo@hotmail.com  desde ya muchas gracias

**Comment by Harvie** [comment]
@tavolito I use **helukabel JZ-HF-CY 4G1** for spindle

**Comment by tavolito** [comment]
Gracias en la semana comienzo a buscarlos
