### ISSUE TITLE
Wiki Autolevel Notes

### ISSUE THREAD

**Issue by Guenni75** [vlachoudis/bCNC#1277]
Hello.
I don't understand a thing in the Autolevel Wiki.

Notes 4.:
The probe.......  data, no need to click "Autolevel". _**If you click the "Autolevel" button**_, the gcode is modified with the leveling data before sending to the controller, so if you have the measured data saved, the correction is then applied twice and you will ruin your board!

Which Autolevel-Button??? 
There is the Probe Tab, where i can switch to Autolevel. 
But this Button doesn't modify Gcode.
And the scan Button doesn't change anyhing too.
When does bCNC changes the GCode?
I never saw bCNC modifying my Gcode, especially not at AutoLevel.

**Comment by Guenni75** [comment]
AHhh ok

**Comment by Harvie** [comment]
If you have ideas how to make information in wiki more clear for newbies, please don't hesitate and update it. You should have access to do so.
