### ISSUE TITLE
Not work in raspberry

### ISSUE THREAD

**Issue by artedecor** [vlachoudis/bCNC#129]
Hello. This latest version 19-10-2015 not working on this raspberry. 
Great jog
Thank you

**Comment by Effer** [comment]
Neither in windows. There's a problem while loading the menu. I suppose @vlachoudis  missed to upload the icons "disable.gif" and "enable.gif" in the last commit.

**Comment by vlachoudis** [comment]
@artedecor indeed @Effer is right. I forgot to commit the two new icons.
Now are there

**Comment by Effer** [comment]
For me is now fixed @vlachoudis
