### ISSUE TITLE
Manual Mesh Bed Leveling?

### ISSUE THREAD

**Issue by GradeSchool** [vlachoudis/bCNC#1291]
I have built a simple 3 axis drawing robot. Without a Z probe (or BL Touch, etc.), is it possible to use bCNC to manually create a mesh bed leveling offset map?

I want to do this entirely manually- move the X and Y to specific grid offsets, lower the Z until touching, enter the Z values, continue until the map is complete. I've scoured the docs and google, can't find any data on whether this is possible. Thanks!

**Comment by Harvie** [comment]
Well... You can manualy craft the `.probe` file and import it to bCNC (it's plaintext file with some coordinates, nothing that you couldn't write manualy).

On the other hand i would greatly reccomend you to go with some simple automatic probe design. It's not that hard to do. It can be as simple as glueing electrical switch to your machine and wiring it to arduino. If you've built 3 axis drawing robot, this will be simplest part, unless you require to probe some intricate shape with lots of features.

If you need some help with the mechanical design of probe, don't hesitate to ask, i am myself in process of making a quite complex probe setup, so i can give you some hints!

Maybe check this video. Two wires, switch and some glue:

https://www.youtube.com/watch?v=dgqRBbZXwIA

**Comment by GradeSchool** [comment]
Harvie-

Thanks so much for the response. I indeed am taking your advice and building a switch. I'll post some updates. And yes, a note to anyone who reads this in the future- just go ahead and build a switch setup, it's so much easier than doing things manually!

**Comment by Harvie** [comment]
Also note that if the object that you are probing against is conductive, then you can simply attach one wire to it and other wire to gantry (eg. put nail with wire attached to it). When the two wires touch, it will make contact and work as probe. if you want to probe against non-conductive object (eg. wooden wasteboard) then you still need some kind of switch.

However be very carefull about ground loops (eg. if there is already ground potential connected to some parts of your machine frame... etc... you can fry your arduino)
