### ISSUE TITLE
Split and Join Not Working / Giving Errors

### ISSUE THREAD

**Issue by rkburnside** [vlachoudis/bCNC#1293]
I get the following error when I try using split / join:

Traceback (most recent call last):
  File "C:\Users\richa\Anaconda2\lib\site-packages\bCNC\Utils.py", line 464, in __call__
    return self.func(*args)
  File "C:\Users\richa\Anaconda2\lib\site-packages\bCNC\CNCList.py", line 689, in splitBlocks
    bl = Block(self.gcode[bid].name())
  File "C:\Users\richa\Anaconda2\lib\site-packages\bCNC\CNC.py", line 2171, in __getitem__
    def __getitem__(self, item):                return self.blocks[item]
IndexError: list index out of range

My cnc file is attached. BTW, I am using the latest version installed through PIP. Thanks for the help!
[goat.txt](https://github.com/vlachoudis/bCNC/files/3710173/goat.txt)

**Comment by MARIOBASZ** [comment]
On my machine, joining works correctly with your example.

**Comment by Harvie** [comment]
Works for me too. However i use Linux.
Can you please do `pip install --upgrade bCNC` two or three times? I've noticed sometimes the old version gets cached and does not install at the first try... Current pip version should be 0.9.14.62.

However even at older versions i never had this problem. Maybe something is different on windows... What version of windows do you use?

**Comment by rkburnside** [comment]
- ran "pip install --upgrade --force-reinstall bCNC" and got the same result.
- installed it on another computer and got the same result.
- installed and ran using a fresh install of python and got the same result
- installed anaconda2 and got the same result.
- I'm running windows 10 on all my machines.

**Comment by MARIOBASZ** [comment]
I use Windows

**Comment by MARIOBASZ** [comment]
I use Windows 7

**Comment by Harvie** [comment]
@rkburnside Can you please share g-code which causes this (possibly with screenshots) ? Perhaps this is some edge case...

**Comment by Harvie** [comment]
Closing this, i will reopen if you will provide the g-code for testing.
