### ISSUE TITLE
how work bCNC ?

### ISSUE THREAD

**Issue by manojprasanga** [vlachoudis/bCNC#1295]
How work bCNC source code cnccanvas code?

**Comment by Harvie** [comment]
What exactly do you mean?

**Comment by manojprasanga** [comment]
I need to understand bCNC cnccanvas source code

**Comment by manojprasanga** [comment]
Is any explanation about source code of bCNC in the internet or other things ?

**Comment by Harvie** [comment]
> I need to understand bCNC cnccanvas source code

Why? Are you trying to improve the bCNC? If you tell me exactly what are you working on, we will be able to help you.

**Comment by manojprasanga** [comment]
Sir, Actually i am working on cnc simulation project .So, i need to develop Canvas like in bCNC canvas .So, try to take a idea about bCNC canvas

**Comment by Harvie** [comment]
OK. I would strongly reccomend you to NOT use CNC canvas from bCNC. It's VERY SLOW and i am very sad about it. For large g-code files it can take hundreds of seconds to refresh screen. It's the WORST part of bCNC and i am looking to replace it with some faster OpenGL based screen.

If you are looking into CNC simulation, take a look here:

https://camotics.org/
http://www.cncwebtools.com/Apps/GCode_Simulator/index.html
https://www.freecadweb.org/wiki/Path_Simulator

**Comment by manojprasanga** [comment]
Sir, i need to create my own simulator.

**Comment by Harvie** [comment]
I know, but don't use CNC Canvas from bCNC for this purpose. It will make your simulator slow and bad. Trust me, it's not a good idea.

**Comment by manojprasanga** [comment]
Thank you sir

**Comment by Harvie** [comment]
Maybe if you are looking for some 3D canvas in pyhton, take a look at something like this:

https://docs.enthought.com/mayavi/mayavi/

There are like 10 similar 3D canvases for use with python.
