### ISSUE TITLE
Problem with very very small values

### ISSUE THREAD

**Issue by MARIOBASZ** [vlachoudis/bCNC#1307]
If the value is close to zero, it may be that the result obtained leads us to a wrong location, for example:
x 7.9335 e-06, the machine will go to x-7.9335 instead of zero.
It would be good a general solution to serve for all cases and plugins

**Comment by MARIOBASZ** [comment]
in this case the value obtained was from the center plugin

**Comment by Harvie** [comment]
Maybe we need to round() the value in center plugin...

**Comment by MARIOBASZ** [comment]
Rounding does not solve the problem.
It is a problem of number format, avoid scientific notation.
As a solution instead of
str ("g1x") + str (x)
I have used
str ("g1x") + format (x, 'f')
however, I think cnc.gline already deals with the problem

**Comment by Harvie** [comment]
I've fixed the center plugin, is everything OK for you now?
