### ISSUE TITLE
Optimize function 

### ISSUE THREAD

**Issue by dodolbysuround** [vlachoudis/bCNC#1326]
Optimize funtion seems to fail.
![image](https://user-images.githubusercontent.com/15923700/71493682-fdd78780-2840-11ea-82e6-d0fb9f90cc41.png)

**Comment by DodoLaSaumure** [comment]
Hello
you can upgrade to the lastest version, where this issue is now corrected
`pip3 install --upgrade git+https://github.com/vlachoudis/bCNC`

**Comment by dodolbysuround** [comment]
Thank you so much! this is perfect.
I wish I could help debogging by myself but although I'm trying my hand to python, my level is still ridiculous...

**Comment by Harvie** [comment]
> I wish I could help debogging by myself but although I'm trying my hand to python, my level is still ridiculous...

haha. i've learned python by improving bCNC. didn't knew anything about python before :-)
