### ISSUE TITLE
copy / cut doesn't work

### ISSUE THREAD

**Issue by dodolbysuround** [vlachoudis/bCNC#1327]
Hi, it seems copy / cut functions doewm't work properly
that's chat I get:
![image](https://user-images.githubusercontent.com/15923700/71534431-13ab8200-28ff-11ea-8622-d4b3f239e071.png)

the abtou bottun also generates an error:
![image](https://user-images.githubusercontent.com/15923700/71534462-46ee1100-28ff-11ea-8397-d86da197db06.png)

**Comment by Harvie** [comment]
Try latest version pls, @DodoLaSaumure seems to have fixed that...

**Comment by Harvie** [comment]
Reportedly fixed in this PR. Please test and close this issue if everything is OK:
https://github.com/vlachoudis/bCNC/pull/1405#issuecomment-751580531

**Comment by dodolbysuround** [comment]
Thank you so much for all your work! issue solved!!
