### ISSUE TITLE
Definition CNC.vars["cutfeed"]

### ISSUE THREAD

**Issue by jophut** [vlachoudis/bCNC#1346]
Hi there,

OS: Windows 10
Machine: Proxxon MF70 with GRBL
I'm using bCNC 0.9.14-dev with the default "TEXT"-plugin via CAM-> Generator -> Text.
Now I'd like to set the cutting feedrate, but can't figure out where to set it.
I've found in the sourcecode that it is set from CNC.vars["cutfeed"], and it has a default value of 1200.

**Comment by Harvie** [comment]
This just means the settings of globaly selected material are used. The same will happen in other tools, when you leave the feedrate empty. This is where you set it:

![image](https://user-images.githubusercontent.com/276504/73441035-a56d3b80-4352-11ea-94f7-1bc2b1634cf5.png)

**Comment by jophut** [comment]
Ah thnx!

And just for anyone who's also having issues with this:
1) Select the "Material" type in the Stock
![image](https://user-images.githubusercontent.com/3954707/73451830-cd679980-4368-11ea-85b5-a743b523102e.png)

2) Set the feedrates in the material
![image](https://user-images.githubusercontent.com/276504/73441035-a56d3b80-4352-11ea-94f7-1bc2b1634cf5.png)
