### ISSUE TITLE
Python27 error

### ISSUE THREAD

**Issue by Tuga75** [vlachoudis/bCNC#135]
I have bcnc running on windows 7 i have python27 install and pyserial. i´m using ramp1.4 on cyclops pcb and the machine runs sometimes ok and order time bcnc frezes and program stop responding an i get this error i try other pc and the same thing hapens any one have a solution.

Best regards
Paulo
![python27 error](https://cloud.githubusercontent.com/assets/15239449/10652410/f580752e-7845-11e5-999c-97b3aa4688d4.jpg)

**Comment by vlachoudis** [comment]
This error messages point to a serial communication error. For some reason the line is dropped or never connected.

**Comment by Effer** [comment]
Hi @Tuga75
 is the error always the same? I mean, is always happening when bCNC is sending a status request:
self.serial.write(b"?")

Which grbl firmware are you using? You can see from terminal Tab during the boot of the controller.
Anyway a poor usb shielded cable can bring a lot of issue.

**Comment by Tuga75** [comment]
Tanks for the reply the grbl as from cyclone pcb factory https://github.com/carlosgs/grblForCyclone to use on mega2560 + ramps 1.4 , yes the terminal is present on lanch bcnc i am trying another usb cable.

Paulo
