### ISSUE TITLE
Jigsaw plugin generates too small radius.

### ISSUE THREAD

**Issue by kestassf** [vlachoudis/bCNC#1355]
Arcs generated by jigsaw plugin have too small radius - grbl fails with error:33 or error:34. [Workaround](https://github.com/kestassf/bCNC/commit/423bac4db95a2120753f32cfb3d8bd49f8b80a84#diff-420688194d2fe56134c7ec64ab6c8766) helped, but I'm not sure if it is correct/complete fix.

~/.bCNC:

    [Jigsaw]
    name = 
    width = 140.0
    height = 130.0
    piece_count = 40
    random_seed = 1
    threshold = 1.2
    tap_shape = basic

Failing line:

    g3 x8.5318 y16.4551 r3.4256
    ok
    g3 x15.0981 y16.9545 r3.1934
    error:34

**Comment by MARIOBASZ** [comment]
I guess it's adding some lines in the complement to round up the spokes
