### ISSUE TITLE
Resize the gcode en bCNC

### ISSUE THREAD

**Issue by gnurc** [vlachoudis/bCNC#1379]
Hello,

I'm using Inkscape and a plugin for raster but this plugin resize the object. It's possible to resize the gcode in bCNC?

It's possible to raster a .svg in bCNC in order to not use the Inkscape plugin?

Best regards

**Comment by MARIOBASZ** [comment]
scale plugin can resize

**Comment by gnurc** [comment]
Hi,

I want resize this circuit,
![Captura de pantalla de 2020-04-05 22-15-57](https://user-images.githubusercontent.com/58319639/78510180-652f9c80-778b-11ea-8a07-98e003d1d955.png)


But the result is this
![Captura de pantalla de 2020-04-05 22-16-12](https://user-images.githubusercontent.com/58319639/78510183-6cef4100-778b-11ea-8450-8ec7d343e604.png)

**Comment by MARIOBASZ** [comment]
I think the problem is all in one height Z:
Test first by making a cut (example cut -0.1 0.1) and then scale

**Comment by MARIOBASZ** [comment]
![3887704D-10B3-46E1-8153-337CB90BA3C0](https://user-images.githubusercontent.com/11743403/78511197-2d1b6000-7771-11ea-80ab-96e9b29e9708.jpeg)
Scaling 0.92 - 0.92

**Comment by gnurc** [comment]
Thank you, that works.

But, How can I get the surface back to 0?  When I try, the object disappears.

**Comment by MARIOBASZ** [comment]
If I remember correctly, it is related to the value of Z safe: if it is above Z safe, G0, below G1, you could modify the Z safe height, although I do not recommend it.
I don't know the practical value of taking Z0: a solution that might be useful to you is cut to Z-0.001.
I'm glad it's useful.
Greetings.

**Comment by MARIOBASZ** [comment]
Experience Flat Path plugin

**Comment by gnurc** [comment]
Yes, it's related with the Z, but by the moment I have done the scale with http://www.scorchworks.com/Gcoderipper/gcoderipper.html#download  and works without problems in bCNC.

Thank you

**Comment by gnurc** [comment]
I have solved added Z0.0 in the gcode.

Thank you.
