### ISSUE TITLE
Noob question

### ISSUE THREAD

**Issue by def420** [vlachoudis/bCNC#1382]
Been trying to get bCNC running on my Raspberry Pi - to my frustration, the "tools" option does not show, eg no tab for setting up various parameters. Im running a Raspberry pi 4 with latest OS. Is there an Easy to follow recipe for getting the tools tab to show??

**Comment by Harvie** [comment]
Did you installed bCNC through pip?
There is no "Tools" tab anymore. It was renamed to "CAM".
Can you please edit this in wiki here on github? You should have write access.
