### ISSUE TITLE
Show the area to be engraver

### ISSUE THREAD

**Issue by gnurc** [vlachoudis/bCNC#1386]
Hello,

This is possible with bCNC?

https://youtu.be/MoQx578lcv0?t=106

What I want is for you to do a few passes with the laser power very low (S5) before starting to rengraver the part.

Best regards

**Comment by MARIOBASZ** [comment]
there is a scan button, maybe that is the solution

**Comment by gnurc** [comment]
Thank you, works fine


Best regards
