### ISSUE TITLE
Profile tool does not respect/use stock thickness and material step down?

### ISSUE THREAD

**Issue by mandrav** [vlachoudis/bCNC#139]
I wanted to create a profile for a path and I have correctly setup my endmill, material and stock in bCNC.
But no matter what I try, it always generates a single path on Z=0 (my surface Z in stock).
What I would expect is to repeat the path in material-depth-increment steps until stock-thickness is reached.
Or am I not using the tool correctly?

PS: I think the same goes also for the pocket tool.

**Comment by carlosgs** [comment]
I had the exact same issue yesterday; it turns out what you need to use is the "cut" tool after running a pocket/profile operation :-)

**Comment by mandrav** [comment]
Ahh! Thanks Carlos, will check shortly :)

**Comment by vlachoudis** [comment]
Indeed. The profile and pocket only generates the path, then you have to apply a cut.
Maybe I should combine it in one.

**Comment by mandrav** [comment]
Confirmed!
A bit counter-intuitive at first but works fine :D

One thing I noted is that the cut provides its own surfaceZ and step-down values, ignoring the respective values from stock and material. I like the fact that it allows me to verify the values in one place before producing the cut but, maybe, it should also read the values from stock and material to use as a starting point?

@vlachoudis great job! This program always has something up its sleeve for me ;)

**Comment by vlachoudis** [comment]
When I first implement the profile/cut I didn't know what parameters to put, so I've split it in two. I believe that I could now safely add the cut parameters also in the profile, pocket etc.

In the "cut" tool what ever value you leave empty (not zero) it will use the one from the stock material.
