### ISSUE TITLE
No G03 codes in .SVG import.

### ISSUE THREAD

**Issue by paulvdhoeven** [vlachoudis/bCNC#1395]
When opening wings.svg in bCNC 0.9.14-dev: (With Python 3.6.9 on Linux Mint Xfce) all the arcs in a path are read as G02 codes, while 10 of them should be G03.
The file was exported from FreeCAD 0.18.16146
When the file is opened in Xviewer or Inkscape it looks as expected.
The coordinates are OK, When I manually change the G02 codes to G03 in bCNC the path is good.

[wings.svg.zip](https://github.com/vlachoudis/bCNC/files/4541945/wings.svg.zip)

**Comment by DodoLaSaumure** [comment]
@paulvdhoeven please let us know if this solved your problem.
Please do not close this issue until it is merged on the head.
Have fun
Pierre

**Comment by paulvdhoeven** [comment]
Short: Yes, it works for me.

Long version:
I have some trouble getting to grips with both Python and git. Even cloned the whole DodoLaSAumure fork, which did not work. (Compared with meld, it does not have the 6-axis stuff, some extra exceptions etc). Only then I saw the patch for svg_elements.py. and I added the "<0" on line 3607 with a text editor, and now the import of the .svg file looks as expected.

I am amazed by the amount of code for generating a "simple" arc and how you guys find the right spot to add such a seemingly simple fix.

**Comment by Harvie** [comment]
Hey don't close this. Nothing was fixed yet :-)

**Comment by Harvie** [comment]
@DodoLaSaumure can you plese make pullrequest? I am aware of #1333, but we need to split this down to multiple pieces and merge separately... It's too much stuff going on at once... especialy because some of the changes i do not agree with yet.

**Comment by DodoLaSaumure** [comment]
Thank you guys for your feedbacks, I appreciate it very much
Have fun with bCNC
Pierre

**Comment by Harvie** [comment]
Fixed by #1396 thanks
