### ISSUE TITLE
Change Language 

### ISSUE THREAD

**Issue by Martin3005** [vlachoudis/bCNC#1402]
Why I can't change the Language to German??? Thanx for your help

**Comment by DodoLaSaumure** [comment]
Halo Martin

In CAM Menu, select your language (upper left) and restart program after you are invited.
Works for me in German with the last release
Best regards
mit freundlichen grüßen
Pierre

![image](https://user-images.githubusercontent.com/58803300/81671619-75513080-9449-11ea-9511-db3f94fcf5c3.png)

**Comment by Martin3005** [comment]
Danke!!!!!!! Die Einladung ist zwar nicht erschienen, aber eine teilweise Übersetzung ist jetzt da, nicht alles, aber die wichtigsten Komponenten!!!

**Comment by DodoLaSaumure** [comment]
Thank you for your feedback Martin.
Could you please close this issue since it is resolved.
Thanks forwards.
Pierre

**Comment by Harvie** [comment]
Reportedly fixed in this PR. Please test and close this issue if everything is OK:
https://github.com/vlachoudis/bCNC/pull/1405#issuecomment-751580531
