### ISSUE TITLE
Make a documentation folder/repo for contributing to it

### ISSUE THREAD

**Issue by chepo92** [vlachoudis/bCNC#1420]
A folder or separate doc repo would be usefull to store images and stuff, also a web and wiki page can be automatically updated from there.

**Comment by Harvie** [comment]
We already have this.

https://github.com/vlachoudis/bCNC/wiki
https://github.com/vlachoudis/bCNC/tree/doc

**Comment by chepo92** [comment]
> 
> 
> We already have this.
> 
> https://github.com/vlachoudis/bCNC/wiki
> https://github.com/vlachoudis/bCNC/tree/doc

Thanks! 
I knew there was the wiki, didn't notice the doc branch, was it explicit somewhere? (if not, that should also be documented)
