### ISSUE TITLE
Tabs on Profiles

### ISSUE THREAD

**Issue by rainerschulte** [vlachoudis/bCNC#1439]
Hi Folks!

I have a problem creating Tabs on Parts with Profiles. Maybe my workflow is wrong... But what is it?

I have a rectangular with a circle inside. For the outer contour I chose Profile outside, then Cut. When adding Tabs The Tabs are shown on the top (0 mm), Material is 3 mm thick and ends in -3 mm. The Tabs are created not on the Profile line, but on the original part edge. 

Kind Regards
Rainer

**Comment by Harvie** [comment]
When creating the tabs, select the profile line instead of the original shape :-)

Workflow is like this:
Profile -> Tabs -> Cut

**Comment by rainerschulte** [comment]
This is they decribed way... [https://vimeo.com/444547780](url) unfortunately not working

**Comment by Harvie** [comment]
Can you send me the file that are you using and your bCNC.ini?

**Comment by Harvie** [comment]
What if you uncheck the "only leave selected islands uncut" in the cutting dialog???

**Comment by rainerschulte** [comment]
Hi! I found a solution. Once the Profile is created and the Pads then, in Editor I have to highlight both and cut then. 
The result now is the attached gcode-File. 
[bcnc.zip](https://github.com/vlachoudis/bCNC/files/5023643/bcnc.zip)

**Comment by Harvie** [comment]
I told you. You have "only leave selected islands uncut" enabled. That means it will only respect islands/tabs that are highlighted.
