### ISSUE TITLE
bCNC - backlash compensasion script?

### ISSUE THREAD

**Issue by Dougie12** [vlachoudis/bCNC#1455]
Hi everyone,

Just had a quick question for you.

I'll start by saying I am still in the process of building my machine. Currently I'm waiting on some over seas supplies.

Originally, my machine was going to be a PC with MACH4, and a controller card. Now it's going to be a Raspberry Pi with the Protoneer Hat.

While I'm waiting, I'm trying to work out the rest of the setup, so my question is: I have a script for Mach that will compensate for backlash, and I want to know if it will work with bCNC?

I didn't come up with this, and I got it from Peter Passuello (https://www.youtube.com/channel/UCQ3OtA ... jcaxkOfr6w).

It reads as follows:

Rem Backlash measurement For Mach3 Imperial
Rem Written by CNCnutz (Peter Passuello)
Rem Based On the Macro M1040 by John Revill
Rem V1.0

NewFeedRate = 10 ' 10mm/minute
Distance = 0.04 '0.04inch per movement
Pause = 500 'Delay between movement

Axis = InputBox("Enter Axis X , Y or Z that you wish to test for backlash. Remember to Zero all your axis before you start.")

message "G1" &Axis &Distance

Rem Prepare To move

Code "G91" 'Set to Relative position mode
Code "G61" 'Set Exact Stop mode
Code "F" &NewFeedRate

Rem First movement

Code "G1" &Axis &Distance
Sleep (Pause)
Code "G1" &Axis &Distance
Sleep (Pause)
Code "G1" &Axis &-Distance
Sleep (Pause)
Code "G1" &Axis &-Distance

message "Calibration Complete. Please Zero the dial gauge"
Moveon = InputBox("Please Zero dial gauage and press OK to continue")

Rem Repeatability Test
Code "G1" &Axis &Distance
Sleep (Pause)
Code "G1" &Axis &Distance
Sleep (Pause)
Code "G1" &Axis &-Distance
Sleep (Pause)
Code "G1" &Axis &-Distance

message "Check Dial Gauge still reads Zero"
Moveon = InputBox("Your dial gauge should still read 0. If not, you may be missing steps or some other mechanical problem. Press OK to start Backlash test.")

Rem Backlash Test

Code "G1" &Axis &Distance
Sleep (Pause)
Code "G1" &Axis &Distance
Sleep (Pause)
Code "G1" &Axis &-Distance
Sleep (Pause)
Code "G1" &Axis &-Distance
Sleep (Pause)
Code "G1" &Axis &-Distance
Sleep (Pause)
Code "G1" &Axis &-Distance
Sleep (Pause)
Code "G1" &Axis &Distance
Sleep (Pause)
Code "G1" &Axis &Distance

message "Check Dial Gauge reading for Backlash."
Continue = InputBox("Your dial gauge should now read the amount of backlash your axis has. Enter this value into Mach3 backlash field of this axis and run the test again.")
Code "G90" 'Reset to ABS position mode
End

**Comment by Mechanikerlegion511** [comment]
Очень было полезно   получить люфт компенсации

**Comment by Harvie** [comment]
To get backlash compensation please consider using grblHAL instead of GRBL. It will probably not run on atmega, but upgrade is cheap (less than $10). grblHAL can be compiled with backlash compensation support (as well as other improvements to original GRBL). It is now officialy supported by bCNC.

https://github.com/terjeio/grblHAL/
