### ISSUE TITLE
text generator

### ISSUE THREAD

**Issue by dodolbysuround** [vlachoudis/bCNC#1461]
Hi, I think there is a problem with text generator. 
I get a message saying:
"text abort: That's embarrassing, I can't read thin font file" 
whatever the file I try ti use
Any idea?

**Comment by dodolbysuround** [comment]
@Harvie , no idea by chance?

**Comment by dodolbysuround** [comment]
here is the message

**Comment by bosd** [comment]
Duplicate of #1444 .
Assume this is fixed now.
