### ISSUE TITLE
Can not start with Python3.9: NameError: name 'sys' is not defined

### ISSUE THREAD

**Issue by kvinwang** [vlachoudis/bCNC#1481]
```
$ python -m bCNC
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/kvin/codes/cnc/bCNC/bCNC/__main__.py", line 50, in <module>
    import Utils
  File "/home/kvin/codes/cnc/bCNC/bCNC/Utils.py", line 41, in <module>
    if getattr( sys, 'frozen', False ):
NameError: name 'sys' is not defined
```

**Comment by GitHubCaps** [comment]
Just a note to self: `Utils.py` already and has always had `import sys`

Where did this become a problem? 

If  "anybody is out there" and knows, please point it out!

**Comment by GitHubCaps** [comment]
Another note to self: I am not using `python3.9`
Did something change?

Is/was this a problem with Travis/github or merging from other sources? 

I am using 3.8 for testing (2.7, also) don't want to compile to the latest  py version (bleeding-edge)  every time there's a new release!

Side note: Releases have been more frequently lately, before version 4 (should we yield?)

There is definitely a fallacy here, if so!

Anyways, I don't have the time to track those changes. However, I know that some of these changes should not have taken place...

**Comment by kvinwang** [comment]
> Just a note to self: `Utils.py` already and has always had `import sys`

`Utils.py` did not import sys before #1483.
It works under python3.8, because we have `from tkinter import *`.

**Comment by cardosorapha** [comment]
I am getting this error in python 3.9.4
