### ISSUE TITLE
Handwheel / Encoder Plugin

### ISSUE THREAD

**Issue by rapzak** [vlachoudis/bCNC#1489]
Hi,

I have not been able to find info anywhere - but is there some options for connect to external encoder/handwheel?

I have example: https://www.aliexpress.com/item/4000211852040.html

Could be nice to use it 👍

**Comment by Harvie** [comment]
There are only two possibilities:

1.) EASY: Write your own driver, which will read the wheel and then send the commands to the bCNC HTTP API.

2.) HARD: Include the required modifications directly to grblHAL firmware, so machine can directly communicate with the jog wheel without communicating through PC.

**Comment by rennen11** [comment]
Hello,
have there anybody meanwhile a solution to use a handwheel with bcnc
