### ISSUE TITLE
configurable pendant port?

### ISSUE THREAD

**Issue by lordmundi** [vlachoudis/bCNC#15]
I'm new to bCNC... looks very interesting.  Is there a way to configure the port that the pendant web server is listening on?  I'm running on a raspberryPi 2 and I already have a web server on 8080.

**Comment by vlachoudis** [comment]
Until your comment it was hardcoded. Now I've modified it to be user configurable in the
~/.bCNC file section
[Connection]
variable
pendantport = 8080

You have to download the new SVN
