### ISSUE TITLE
fetching more data from json /state request

### ISSUE THREAD

**Issue by humneraudio** [vlachoudis/bCNC#1516]
Is it possible to add further information into the /state JSON request?

Currently we get the following

{"G": [], "color": "OrangeRed", "state": "Not connected", "msg": "", "wz": 0.0, "wy": 0.0, "wx": 0.0}

I was mainly looking to add in MPos if possible?

**Comment by Harvie** [comment]
Yes. It can be done. Also i would like to add API for overrides.
