### ISSUE TITLE
Anyone use a USB hand wheel (like ShuttleExpress)?

### ISSUE THREAD

**Issue by water-rhatt** [vlachoudis/bCNC#1554]
Jogging with the keyboard is slowing my workflow. I have to tap the key a dozen times, or change the increments and guess how far it is going to go, etc. I miss the jog wheel on a Haas machine that I used to have access to. There was a physical aspect to rotating the wheel that gave you a tactile sense of how far you have gone.

Is there an effective hand wheel that works with bCNC? For example, the ShuttleExpress? Anyone have a setup they would like to share or video of their setup?

**Comment by Harvie** [comment]
> I miss the jog wheel on a Haas machine

We are not exactly Haas, but getting closer every day :-)

There are two solutions:

1.) bCNC has HTTP API, so you can write script handling communication with the jog wheel and forwarding commands to bCNC over HTTP protocol.

2.) Ditch GRBL and use grblHAL with some plugin instead (you will have to discuss with grblHAL developers). That way it will work without relying on running PC. I would reccomend you to use grblHAL anyway, you will need to upgrade your arduino for newer 32b board in similar price range. https://github.com/terjeio/grblHAL/
