### ISSUE TITLE
DXF properties

### ISSUE THREAD

**Issue by dodolbysuround** [vlachoudis/bCNC#157]
Hi,
I would like to know how to configure my DFX files so that they can be imported into bCNC.
I manage to open the ones I draw with inskape but enconter problems trying to open the ones I generate with solidworks.
Thanks for your help

**Comment by vlachoudis** [comment]
Hi @dodolbysuround could you send me one of the dxfs that are not able to be imported to check.

**Comment by dodolbysuround** [comment]
hi, thank you for this quick answer.
you'll find in attachement a DXF file directly saved from solidworks.
I also join a picture of the differents available option in solidworks
the "version" scroll list include:
-R12
-R13
-R14
-2000-2002
-2004-2006
-2007-2009
-2010
Looking forward to read from you




Date: Thu, 19 Nov 2015 03:04:42 -0800

**Comment by vlachoudis** [comment]
Sorry but I cannot find the attachment

**Comment by vlachoudis** [comment]
it loads the dxf normally with no error. Is it correct?

![screenshot_2015-11-19_18-21-16](https://cloud.githubusercontent.com/assets/3834594/11278303/9b3ab74e-8eea-11e5-802e-c9e00fb90fc2.png)

**Comment by dodolbysuround** [comment]
It seems to be correct indeed on your picture but when I do open it, nothing display, execpt from 'c:\user\loic\descktop\Pièce1.DXF' loaded in the left bottom corner

Date: Thu, 19 Nov 2015 09:23:26 -0800

**Comment by vlachoudis** [comment]
Maybe is the e with accent in the filename

**Comment by dodolbysuround** [comment]
I tryed without the accent ant that's the same.
What's amazing is the that in your screenshot, only the name of the file appears. In my case, the whole path displays.

**Comment by dodolbysuround** [comment]
Ok, problem solved:
the extension must be written lower case and by default, solidworks write it upper case.
then Pièce1.DFX doesn't works but Pièce1.dfx is ok (-;

**Comment by vlachoudis** [comment]
Good to know. I will modify the code to accept upper and lower case extensions

**Comment by vlachoudis** [comment]
Ok now it is fixed. Accepting both lower and upper case extensions.
