### ISSUE TITLE
Measurement is off

### ISSUE THREAD

**Issue by mikeyd2673** [vlachoudis/bCNC#1575]
im using bcnc for my cnc router when i design a project the size is always way off in order to get it right i have to divide by 5.6 in the design for example if i need something 12 inches i have to design it on easle or fusion 360 at  2.14 inches can anyone help me fix this problem

**Comment by Harvie** [comment]
Do you have correctly calibrated steps per mm in GRBL?

**Comment by mikeyd2673** [comment]
I dont know 
How do you do that?

**Comment by robughblah** [comment]
review https://youtu.be/z3bUg9InVeA


Rob

**Comment by Harvie** [comment]
You need to calibrate your machine before you can use it:
https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration
