### ISSUE TITLE
Random HOLD triggers

### ISSUE THREAD

**Issue by probe3** [vlachoudis/bCNC#1576]
I've been running bCNC for about 2 years and haven't updated it on my Windows10 laptop. I have the latest Fusion360. Lately I've been getting random HOLD triggers during my programs. I have to babysit the machine because I have to manually resume the operation. During a simple ramped contour operation it triggered HOLD about 20 times. I tried to an adaptive operation and it kept happening so often that I shut the whole thing down.

**Comment by probe3** [comment]
(FIXED) - Replaced USB cable from laptop to controller.

**Comment by Harvie** [comment]
replacing USB cable might help, but i guess you should step up your shielding game anyway... especialy cables to motors and switches.
