### ISSUE TITLE
versioning funny business

### ISSUE THREAD

**Issue by greyltc** [vlachoudis/bCNC#1578]
The latest tag doesn't have numbers anymore, just called "pypi"? This makes packaging kinda tough.

**Comment by Harvie** [comment]
Please stop duplicating your own issues https://github.com/vlachoudis/bCNC/issues/1341

**Comment by greyltc** [comment]
This issue is about the appearance of a non-numerical tag, "pypi." #1341 is not about that.

So I can't really say I understand why you've marked this a duplicate and closed it since the pypi tag is still in the repo as far as I can tell. Was the "pypi" tag meant to address #1341 or something?
