### ISSUE TITLE
New Windows isntalation?

### ISSUE THREAD

**Issue by pedjas** [vlachoudis/bCNC#1588]
The latest Windows instalation in releases is from 21 Nov 2018.
It would be good to have updated one.

**Comment by Harvie** [comment]
use pip install.

**Comment by pedjas** [comment]
What is pip?

**Comment by Harvie** [comment]
Please read documentation: https://github.com/vlachoudis/bCNC/wiki/Installation

**Comment by pedjas** [comment]
Ok, I see. To be user of bCNC I first have to get a degree in Python programming.

**Comment by MARIOBASZ** [comment]
Jajaja. 
Courage, it is true, it is not automatic, but bCNC's performance is really very good.

**Comment by Harvie** [comment]
> To be user of bCNC I first have to get a degree in Python programming.

To install bCNC on windows you need to install python, and perhaps on some private school this alone might get you a degree in programming.
Also you need to install windows first, which does not make you CEO of microsoft :-)
