### ISSUE TITLE
Gcode Rendering Issue & Auto Leveling Issue

### ISSUE THREAD

**Issue by PaladinEnabling-Technologies** [vlachoudis/bCNC#1603]
Hello There, I've been using bCNC for a little while now to make PCBs and it is great. Recently though, I started seeing some strange behavior with the auto leveling. What seems to happen is that the probe triggers prior to actually touching the copper section:

![Probing](https://user-images.githubusercontent.com/6445711/126081278-4bdb884b-b5b9-40f9-94eb-2b78434ecf9a.png)

The number 1 picture shows where the probe is triggering the auto level without actually touching and sometimes the probe does travel all the way to touch the copper to get the auto level point. The tip on the copper is the light reflecting off the V bit, if the light reflection tip and the v-bit tip touches, then you know that the v-bit is making contact with the copper.

This can also be seen on the auto leveling data map where I don't have a ~2 mm fluctuation in the blank pcb copper layer:

![Auto Leveling Data](https://user-images.githubusercontent.com/6445711/126081321-23a03530-2249-40e9-ae32-c232a06c1c1f.jpg)

The spindle has been disconnected to try and rule out any 

Another follow-up question I had was related to the rendering. When uploading larger G-code files, then the job visualization area is not populated with the entire G-code file:

![Gcode File in bCNC](https://user-images.githubusercontent.com/6445711/126081363-624c8300-0fe1-4e21-be05-75b4ce761ef6.JPG)

A notification did appear once stipulating the following: "Rendering takes TOO Long. Interrupted..."

Example of the how the visualization should look:

![Gcode File in NCViewer com](https://user-images.githubusercontent.com/6445711/126081371-eac1c06a-b7f8-4bff-a309-d6beb27e8ad0.jpg)

I'm not really that worried about the visualization of the G-code file as the G-code is still executed completely even though the visualization is not complete.

The main concern is related to the auto leveling, looking for some insights here to try and resolve it. Thank you and looking forward to feedback on the matter.

**Comment by PaladinEnabling-Technologies** [comment]
Hello Everyone, 

I managed to resolve the issues that I logged here. 

**Issue 1 - Z-probe triggering prior to it actually touching the copper plate:**
**********************************************************************************
My spindle ground was not sufficient and would sometimes incorrectly trigger. I had added an additional grounding pin which is linked to the same grounding pin I attach to the spindle.

This additional grounding pin resolved the probing issue that I had so if you are experiencing this, then please try this.

**Issue 2 - Rendering not completing in the job viewer window:**
*********************************************************************
There is a timeout function which impacts the rendering which I was not aware of. Setting this setting higher allows for the job to render completely.

![Rendering Time Out](https://user-images.githubusercontent.com/6445711/126589861-4d6537a6-c272-4264-84b1-e8e223e6162a.JPG)

**Comment by Harvie** [comment]
> There is a timeout function which impacts the rendering which I was not aware of. 

Yes, this is problem. Python is extremely slow. We need to write OpenGL based python module in C language, compile it to native library and call that from python. Unfortunately it is not that easy. Perhaps we can use some library like coin3d (this is what FreeCAD uses for this exact reason). But it's not easy problem to solve, i've been looking for solution for some time already...
