### ISSUE TITLE
How to operate the Relay with coolant command automatically?

### ISSUE THREAD

**Issue by ImranKhan203** [vlachoudis/bCNC#1626]
Can you please tell me how can I operate the relay with coolant command (M8 & M9) automatically.
Like if I click on "Run" the relay should be ON and if I use "Pause" command the relay should be Off automatically not manually.
Is this possible?

I know the pin on CNC shield for coolant command that is pin A3 on Arduino Uno (GRBL 0.9).

Please suggest me that in which file of bCNC (v 0.9) I have to change in python program and what program I have to use for this?

Thank you.

**Comment by Harvie** [comment]
In bCNC config you can specify g-code header which will be sent before any g-code file:

https://github.com/vlachoudis/bCNC/issues/165#issuecomment-161929672

![image](https://user-images.githubusercontent.com/276504/136616310-630e6e93-5f55-4c0a-a0f6-81a1f25666c6.png)

**Comment by Carmah565** [comment]
@ImranKhan203 
I wonder if there was progress in this idea or if you managed to get around, because i was wanting to use the coolant that way

**Comment by MARIOBASZ** [comment]
It seems to me that the Door command turns off the coolant and the spindle.
