### ISSUE TITLE
Autolevel Issue

### ISSUE THREAD

**Issue by atrueresistance** [vlachoudis/bCNC#163]
Hello, I just installed limit switches on my SO3. I was able to complete a tool change just fine. When trying to autolevel I get this error. I'm not sure if you need the files... Guessing it is user error
![untitled](https://cloud.githubusercontent.com/assets/7239809/11453525/b735ed02-95d3-11e5-88a3-395e11c5ce41.png)

State: error: Invalid gcode ID:24
Last error: g43.1z-6
Two G-code commands that both require the use of the XYZ axis words were detected in the block.

Here is the output from the terminal

     G90
     ok
     G0Z5
     G0X24.668Y9.673
     G38.2Z-10.0000F10G0Z5
     G0X65.013Y9.673
     G38.2Z-10.0000F10G0Z5
     ok
     G0X105.358Y9.673
     ok
     G38.2Z-10.0000F10G0Z5
     G0X145.703Y9.673
     error: Invalid gcode ID:24
     ok
     error: Invalid gcode ID:24
     ok
     error: Invalid gcode ID:24

**Comment by vlachoudis** [comment]
Hi @atrueresistance if you click on the red "Status:" it will tell you which line caused the problem and also the explanation of it he ID:24

**Comment by vlachoudis** [comment]
@atrueresistance I've introduced a bug when I added the to accept unicode file names. The unicode strings in the gcode were ignored and concatenated with the next one. Therefore the two commands were together. Now it is corrected.

**Comment by atrueresistance** [comment]
Thank you! I can confirm autolevel working. Can you go into detail on the tool change options. I have setup a tool change area and a probing area. I chose the setting to pause before and after. When I hit the macro the machine moves to those areas, but does not actually pause. 

Currently if I load a project, do not autolevel, and hit go. The machine will move to home area, move to probe, probe, and then go directly to cutting without pausing. To me that isn't very safe as I have to remove the alligator clip and turn the router on while in motion. The first time this caught me really off guard as I wasn't expecting it to continue. 

Autoleveled, the machine will go straight to cutting.

**Comment by atrueresistance** [comment]
Also grbl throws an error when encountering a m6 command after an autolevel. Under Probe -> Tool I have the policy set to Manual Tool Change (TLO) and pause before/after.

**Comment by chamnit** [comment]
@vlachoudis : M6 is not a supported g-code by Grbl. So it will throw an error. bCNC will need to remove it from the stream unfortunately. I'm not quite sure how to otherwise to do it, at least within Grbl itself without mucking up things.

**Comment by atrueresistance** [comment]
I thought that bCNC intercepts the M6 before sending if you specify manual tool change. Ie running the macro. If there were any changes today to master I didn't download. The version I'm on is two days old, right after the Unicode fix.

**Comment by vlachoudis** [comment]
If you select the "Manual Tool Change" it should substitute the m6 with the appropriate sequence. If not there, then something broke there. I will try to find it.

**Comment by vlachoudis** [comment]
@atrueresistance I've made a few tests on my machine and a clean installation and I didn't find any problem. Could you send me your .bCNC file to see if some particular settings are causing the problem.

**Comment by atrueresistance** [comment]
Yes I can. When I get off work I can upload.

**Comment by atrueresistance** [comment]
[bCNC.txt](https://github.com/vlachoudis/bCNC/files/59998/bCNC.txt)

**Comment by vlachoudis** [comment]
What you've send me is the default bCNC.ini and not the .bCNC with your preferences.

**Comment by atrueresistance** [comment]
![untitled](https://cloud.githubusercontent.com/assets/7239809/11870601/bf74b632-a48e-11e5-8813-9d251ed495e5.png)

Otherwise I'm not sure what file to upload

**Comment by Effer** [comment]
Hi @atrueresistance I don't have an english copy of windows but the fast way to get there is to pop up command windows with the Windows Key + R
Then write this command %UserProfile% and hit enter.
It'll will show a folder where you can find the .bCNC file

![immagine](https://cloud.githubusercontent.com/assets/1007007/11871019/ced4feaa-a4cc-11e5-8501-71d02c32cedf.png)


Or if you want to go with explorer should be in
C:\Users\YourUser\

**Comment by mano1979** [comment]
I did fix the "not pausing" problem for grbl.

**In the bCNC folder, open the CNC.py file with a text editor.
goto line 1400 and change:**

if CNC.comment:
lines.append("%%pause Tool change T%02d (%s)"%(self.tool,CNC.comment))
else:
lines.append("%%pause Tool change T%02d"%(self.tool))

**to this:**

if CNC.comment:
lines.append("m0")
else:
lines.append("m0")

** Now pause is working. To "resume" rightclick on the info bar (run, idle, error, alarm) and click on Resume.**

**Comment by vlachoudis** [comment]
Can you try instead of sending chaning the CNC.py to change the Sender.py line 633 and replace the "!" with a "m0\n"

**Comment by mano1979** [comment]
Indeed! That works also. Not noticing any difference though, but i'm sure this is better as what i did.
Also i found that the grbl firmware can be used unchanged. No lines of code have to be added.

**Comment by vlachoudis** [comment]
This way it displays also a message on the status to change the tool, otherwise it will simply mention paused.

**Comment by mano1979** [comment]
I see. I am not sure if it is working though. Atleast the message is not displayed while in pause. It might have flashed by though...
