### ISSUE TITLE
Please ZERO any location of the probe before starting a run

### ISSUE THREAD

**Issue by atrueresistance** [vlachoudis/bCNC#164]
Hello, I don't seem to be getting this right. I ran the probe function, but still can't hit Start without this error. 
![untitled1](https://cloud.githubusercontent.com/assets/7239809/11453697/7e5b8800-95da-11e5-98f5-50ef280a3411.png)

![untitled](https://cloud.githubusercontent.com/assets/7239809/11453694/4835b87c-95da-11e5-806c-bb97c63fd81f.png)

**Comment by vlachoudis** [comment]
After the autolevel probing cycle you should zero the surface (z-coordinate) at any point you like and then click the "Zero" on the autolevel probe. Then the autoleveling information will be relative to this point.
It is a bit of redundant information as a safe measure, normally it is needed in the case that you load the probe from a file.

**Comment by atrueresistance** [comment]
Thanks! Added a note in the wiki for new people, as it wasn't clear at first to me.

**Comment by vlachoudis** [comment]
I have to make it more smart in the future. That if it was zeroed before the probing cycle to remember the information.
