### ISSUE TITLE
Can't make it work with Marlin 2.0.9.2 (bCNC 0.9.14.317)

### ISSUE THREAD

**Issue by sidecircle-dev** [vlachoudis/bCNC#1642]
Hi,
Sorry I don't know if it is supposed to work together:  Any attempt to jogg or send g-code returns "Unknown Command"

I have a Mega2560 with Ramps flashed with Marlin 2.0.9.2. When using the arduino IDE's builtin serial monitor, I can send g-code like G0 X12 to the board and the CNC moves as expected.

The two screenshots show my problem:

![unknown command](https://user-images.githubusercontent.com/73586140/140618186-5f4672b2-b4ab-45ca-8ec7-c2123897be2f.jpg)
![connection](https://user-images.githubusercontent.com/73586140/140618182-b2ffb964-cc51-41c5-a82b-df291506bbd6.jpg)

The status stays red ( Not connected ) although the state says "Connection is established". The Terminal shows that it was able to read the output from my board. But any commad sent to the board (like the G0 X12 I explicitly sent) generate errors.

Again: I'm not sure if these two are supposed to work together, but any help would greatly be appreciated!
Thanks in advance,
Pascal

**Comment by Harvie** [comment]
> Again: I'm not sure if these two are supposed to work together, but any help would greatly be appreciated!

i don't think so. list of currently included controller plugins can be found here:

https://github.com/vlachoudis/bCNC/tree/master/bCNC/controllers
