### ISSUE TITLE
Problem with single profile for b-spline curve imported form svg file

### ISSUE THREAD

**Issue by PribylV** [vlachoudis/bCNC#1643]
I'm not able to create single profile for any toolpath with at least one section which is not a simple geometry. bCNC seems to start generation, but it never ends and no profile is generated. Simple test file in attachement.
[curve.zip](https://github.com/vlachoudis/bCNC/files/7526464/curve.zip)
.

**Comment by Harvie** [comment]
There are several things i've noticed:

* shape is correctly converted to series of straight lines by bCNC, so it is no longer complex shape in bCNC.
* There is too much these line segments, which can bea extremely simplified by arcfit (highlighted in attached screenshot)
* Your shape is very small. eg. 9mm across. Is that right? Perhaps change your DPI a bit.
* For some reason the path is not closed. This might be problem of original SVG or problem in bCNC. I have closed it using highlighted tool and then i was able to generate profile for it. When i used arcfit i didn't needed to close the shape, so perhaps that is even better solution.

![image](https://user-images.githubusercontent.com/276504/141457090-479515e6-c61a-4ef9-b538-5242aecad5c3.png)

**Comment by PribylV** [comment]
Thank You
