### ISSUE TITLE
Wiki on how to do plugin.

### ISSUE THREAD

**Issue by asm7100** [vlachoudis/bCNC#169]
A wiki to do a simpel plugin, eks. go to X,Z, and drill a holl.
Just to get us startet to make plugin :-)

**Comment by vlachoudis** [comment]
Hi @asm7100. For the moment there is no documentation on how to write a plugin.
I would recommend to look the existing plugins, maybe bowl, spirograph and the check for the necessary functions in the CNC.py

**Comment by Effer** [comment]
Here a short example , far than complete:

https://github.com/vlachoudis/bCNC/wiki/How-to-create-a-plugin

![myplugin](https://cloud.githubusercontent.com/assets/1007007/11865040/ae836fea-a4a1-11e5-8564-df49fd9c3ae5.png)

**Comment by vlachoudis** [comment]
Thanks @Effer

**Comment by Effer** [comment]
you're welcome

**Comment by asm7100** [comment]
Thanks :-)
