### ISSUE TITLE
can possible Auto-level with average Arc

### ISSUE THREAD

**Issue by ashokavarthanan** [vlachoudis/bCNC#1739]
<img width="630" alt="probe_like_this" src="https://user-images.githubusercontent.com/54305413/186432519-296b941c-afcd-43d7-9401-2e6ba96966ca.png">
currently Auto-level works average Line. can possible Auto-level with average Arc?.

also can answer this?
https://github.com/vlachoudis/bCNC/discussions/1732

Thanks.

**Comment by JipeB** [comment]
Hi,
I think the best way to smooth the profile is to multiply the measurement points by reducing the distance between each of them.

JP
