### ISSUE TITLE
wiki installation section is missing

### ISSUE THREAD

**Issue by swarfer** [vlachoudis/bCNC#1745]
Hiya
I am trying to point someone at the intallation instructions, but they are missing.
when i am not logged into github, the screen flickers and goes back to the index.
When I am logged in, clicking 'installation' takes me to the 'create new page' editor.

**Comment by Harvie** [comment]
Anyone with github account can edit the wiki. But i am not sure where do i find the history, so i can roll it back...

**Comment by rschell** [comment]
Appears that section was deleted back in July, I just reverted that deletion.

**Comment by swarfer** [comment]
Thankyou

**Comment by Harvie** [comment]
@rschell thank you. where did you found that? i was not able to find it...

**Comment by rschell** [comment]
I went to the Wiki page and clicked edit, then reviewed the history of the page

**Comment by Harvie** [comment]
But there was no edit button when the page was not existing :-D

**Comment by rschell** [comment]
Think I when to the top level history and looked at the top level history edits (clicked on the History select-able label), it showed up as "Destroyed Installation (markdown)" on Jul 19th.

Looks like this (#1745) and #1725 can be closed now.
