### ISSUE TITLE
bCNC wont open

### ISSUE THREAD

**Issue by GabriellJohnny** [vlachoudis/bCNC#1766]
when i try to start the program i get the following message in the prompt and then it crashes

![Captura de tela 2022-11-30 083821](https://user-images.githubusercontent.com/88600585/204786737-12bf83e0-b0a1-4879-b8be-f642531c6d17.png)

dont know how to fix it, all the modules are installed correctly , this behavior started all the sudden. I am running the program on the Win10 .

**Comment by bgbsww** [comment]
That's reading the configuration file.  It would be ~/.bCNC and <program home>/bCNC.ini on a unix system.

On a windows system, it should be .bCNC in your user's home directory, and bCNC.ini wherever the application is installed.  One or the other of those files is corrupt.

Looking at the stack tract, it's c:\\Users\Volts/.bCNC which is your user config file.  Delete that file, and things should work again.

**Comment by GabriellJohnny** [comment]
it worked, tahnk you!
