### ISSUE TITLE
Display does not render 45 degree laser code

### ISSUE THREAD

**Issue by atrueresistance** [vlachoudis/bCNC#178]
This isn't really a big problem as the code runs fine. bCNC doesn't render gcode exported from picengrave correctly. 

![capture1](https://cloud.githubusercontent.com/assets/7239809/11980271/61a618fe-a95f-11e5-81f1-d1bb63cd5b2a.PNG)

CamOptics renders
![capture](https://cloud.githubusercontent.com/assets/7239809/11980296/7f723610-a95f-11e5-86b5-c5339a50ede8.PNG)

I used the jtechphonics plugin from inkscape to generate the cutout, and picengrave to do the engrave part. Using the bCNC editor to combine the programs. Must say, love the editor.

![rect4149 dithered](https://cloud.githubusercontent.com/assets/7239809/11980389/067fe972-a960-11e5-941f-a7222f29c75d.jpg)

gcode generated
[output_0010.txt](https://github.com/vlachoudis/bCNC/files/71006/output_0010.txt)

**Comment by Effer** [comment]
Hi @atrueresistance 

If M3 command is removed (line 31) the render is correct:

![image](https://cloud.githubusercontent.com/assets/1007007/11991200/9d7080e6-aa17-11e5-8e1e-b57702d9ff99.png)

Still to understand the reason  but hope it could help.

**Comment by Effer** [comment]
The issue happen every times the M03 is preceding a group of G1/2/3 commands that doesn't explicit the motion modal mode. As example:

G1 X0 Y0
(M03) (Comment/ Uncomment the M3 to see the differences)
X100 Y100 (here we are implicit using G1 )
X50 Y0
G1 X0 Y0

To fix seems enough to comment the line 1028 in CNC.py

```python
1026)    elif c == "M":
1027)       self.mval = int(value)
1028)       self.gcode = None	# Why????
```

But that (# Why????) comment is scaring me a lot. 
So @vlachoudis is the right way?

**Comment by vlachoudis** [comment]
You are correct @Effer we should remove this line.

**Comment by vlachoudis** [comment]
I've uploaded the correction

**Comment by Effer** [comment]
I was almost there.. @vlachoudis  steal my point ;)
