### ISSUE TITLE
Error on the tool tip displayed in the macros part

### ISSUE THREAD

**Issue by ThierryM** [vlachoudis/bCNC#180]
Hi,
I've noticed that the tool tip of macros are wrong : the tool tip displayed for the macros is the last good tool tip (of an other section). See the picture where it's the tool tip of colors button in the config part.
![selection_022](https://cloud.githubusercontent.com/assets/1470067/11998339/daf095fe-aa9a-11e5-84e1-707c9053771c.png)
Regards

**Comment by nfz** [comment]
yep, same here.  Problem is with the docstring in the plugin.  I provided a fix in pullrequest #181.

**Comment by vlachoudis** [comment]
Thanks @nfz
