### ISSUE TITLE
bCNC with fluidNC 3.6.6 - Don't work more.

### ISSUE THREAD

**Issue by RDS356** [vlachoudis/bCNC#1801]
The latest version of FluidNC don't work more with Bcnc.
The FluidNC 3.6.5 and early works very well.
Any idea ?

![bcncfluidnc](https://user-images.githubusercontent.com/25726497/212912986-c7ab651f-0988-4e12-874c-dc684351f382.png)

**Comment by Harvie** [comment]
You have bCNC from git?

**Comment by RDS356** [comment]
> You have bCNC from git?

Yes, version 0.9.15 phyton 3.8.7.

**Comment by rschell** [comment]
Traceback suggests that the tool field is blank from the G string.  

Could change "int(g(1:)" to "int(g(1:) or 0)"

**Comment by rschell** [comment]
I had gone a step further and only process the T code when the tool is managed by controller:

                # accept value only if tool change managed by grbl
                if CNC.toolPolicy <= 1: CNC.vars["tool"] = int(g[1:] or 0)
