### ISSUE TITLE
gcode is displayed in a small scrollable frame.

### ISSUE THREAD

**Issue by Git-Bruno** [vlachoudis/bCNC#1885]
The frame showing the gcode is a small scrollable frame that cannot be enlarged to occupy the entire frame at the left of the bCNC window. This is with the last master branch, code dated Apr,22,2024. 
![bCNC_gcode_window](https://github.com/vlachoudis/bCNC/assets/32901840/576cc94d-6e8c-44f2-90de-299722103124)

**Comment by Harvie** [comment]
Thanks for noticing this. i did not. wonder which commit had introduced it...

**Comment by Git-Bruno** [comment]
This was introduced on Fev 09 by PR#1849, Vertical scrollbar to make small screens easier to use. bmain.py was changed to use VScrollFrame.py.
If I replace bmain.py with a copy not using VScrollFrame.py then the gcode fills the entire left frame.
I tested previous versions and the left frame in the Editor page was already scrollable by default.
To me the code introduced by PR#1849 should either not apply when in the Editor page or , for all pages, always adapt the size of the left frame to the screen size and make it scrollable when the content cannot fit in the frame.

**Comment by ownedcore** [comment]
Observing the same with a Debian 12 installation. Also cant figure out which version of bCNC i actually have installed. Though I have the VScrollFrame.py file.

If I change line 39 of VScrollFrame.py and add ", height=event.height" the frame gets all down to the bottom (Editor tab). Also this renders the ability to scroll down, if the left side frame is not occupying the whole window. Tested on "File" tab.

Other thing i notice without the change to VScrollFrame.py and the height addition is that i can scroll the left side up when its not fully occupying available space.

Im not familiar with tk so cant help, just wanted to share my obversation.

**Comment by Git-Bruno** [comment]
This update to VScrollFrame.py woks for me too. May be this change is ready to roll if the display on small screen works as per code change for PR#1849.

**Comment by Harvie** [comment]
Fixed by reverting
