### ISSUE TITLE
bCNC fails to run on fedora 21

### ISSUE THREAD

**Issue by omnister** [vlachoudis/bCNC#191]
Here's what I get:

!) bCNC
Traceback (most recent call last):
  File "./bCNC.py", line 2177, in <module>
    application = Application(tk)
  File "./bCNC.py", line 117, in __init__
    self.ribbon = Ribbon.TabRibbonFrame(self)
  File "/home/walker/laser/bcnc/Ribbon.py", line 479, in __init__
    image=Utils.icons["load"],
KeyError: 'load'

Any ideas?  I think I've installed all the packages mentioned in the README.  This was from pulling down and unzipping the zip file from github.

**Comment by vlachoudis** [comment]
You either have to run the script "bCNC" that sets the proper directories
or download the latest master and sets the correct paths inside the python program
