### ISSUE TITLE
Probing question

### ISSUE THREAD

**Issue by 1bigpig** [vlachoudis/bCNC#21]
@vlachoudis With the latest update to fix the probing response from grbl, I finally got my probe to work.  So, I set up a small area to probe and the probe went off and did its thing and I ended up with a nice little file with like 25 probe coordinates.

So far, so good.  Now, I have no idea how to make a surface compensated G-code file from bCNC.  

![bcnc_probe](https://cloud.githubusercontent.com/assets/1418825/7462194/58fca426-f275-11e4-97cd-f8afe0fb19c7.jpg)

There is no button on the WCS tab.  All I have is 'Clear', 'Get Margins', 'Set Zero', 'Draw' and 'Scan'.  When I go to the pull down menu File --> Probe , all I have is 'Open', 'Save', and 'Save as'.  I have tried the save and save as, and all I am getting is the probe data points saved again.

So, shouldn't there be some kind of 'Process' button on the WCS tab?  Or is there one and mine is missing?

Bruce

**Comment by vlachoudis** [comment]
I agree is not fully intuitive for the moment, however the explanation is on the Wiki page.
After the Scan cycle you have to select a point that you will considered as zero levitation in z. And all probing points will be relative to this location.
Briefly jog to one location. touch the surface on the z axis set zero on the workspace and click the "Set Zero".
Then once you start the run (and the probe exists) the all paths will be interpolated.
