### ISSUE TITLE
Change directory

### ISSUE THREAD

**Issue by TilTisback** [vlachoudis/bCNC#217]
Hello,
i found another bug in the file system.

when i try to open a folder bcnc shows me this opening window: 
![bcnc open](https://cloud.githubusercontent.com/assets/13772017/12678113/7a726bf2-c69d-11e5-9718-145ab048748e.JPG)
now i click on the CAD button in the upper path to change that folder to D:\CAD

but instead of changing to the directory it shows me this error:
![bcnc error](https://cloud.githubusercontent.com/assets/13772017/12678201/ea4be0c0-c69d-11e5-92fb-c1e018d52a18.JPG)

when i click directly on the D: button it changes the directory to this:
![bcnc opene](https://cloud.githubusercontent.com/assets/13772017/12678240/19d73600-c69e-11e5-8ae4-d1774118c3dc.JPG)

my workaround for this is a bit awkward:
i go to the .bcnc file in the users folder and change the dir = D:\CAD\Laserprojektor\CNC to dir = D:\CAD and restart bcnc
now i can select the subfolders correctly and open my new cnc job

i think the problem with this is as follows: the bcnc program is located on the E: drive while the cnc files are on the D: drive.

**Comment by vlachoudis** [comment]
Thanks for the bug report. I will change to windows to see what I can do.

**Comment by vlachoudis** [comment]
I have to find out how to scan for the windows drives in python.
For the moment you can change the drive by typing the drive name
C: or D:
in the field of "Filelname" and press Enter

**Comment by vlachoudis** [comment]
I've changed the FileDialog to respect the drive letter of windows. Can you check if it works.
Still if you want to change drive you have to give it in the Filename
