### ISSUE TITLE
[Smoothie] do not reset

### ISSUE THREAD

**Issue by wolfmanjm** [vlachoudis/bCNC#222]
Stop should not issue a reset for smoothie. ^X should be issued instead, this stops everything immediately, and turns everything off. $X exits halt state.
reset on smoothie is different and should not be used.
(maybe just issue reset when the rest button is clicked, not when stop is clicked).

- Thanks

**Comment by vlachoudis** [comment]
@wolfmanjm, ok I've correct it. The soft reset (default reset button) is sending a ^X as in grbl while the hard reset send a "reset" closes the port, waits 5s and reconnects
