### ISSUE TITLE
Incorrect "python-serial" package name on OSX

### ISSUE THREAD

**Issue by justinclift** [vlachoudis/bCNC#223]
Just fired up bCNC on OSX for the first time, and it came up with a warning about missing "python-serial".

Interestingly, for OSX there is no "python-serial" module available.  This was a bit confusing until finding out it's called "pySerial".  So, on OSX this works:

```
$ pip install pyserial
Collecting pyserial
  Downloading pyserial-3.0.1.tar.gz (134kB)
    100% |████████████████████████████████| 135kB 1.7MB/s 
Building wheels for collected packages: pyserial
  Running setup.py bdist_wheel for pyserial ... done
  Stored in directory: ~/Library/Caches/pip/wheels/06/71/f1/d8c81329abcaf4c623daff8af76a7dbf00f055cb8205cec0ef
Successfully built pyserial
Installing collected packages: pyserial
Successfully installed pyserial-3.0.1
```

It might be useful to update the error message with that.  Optimally, maybe check the platform being run on, and give the instructions for that particular one? :smile:

**Comment by vlachoudis** [comment]
Thanks I've updated the message. I will push it together with the new changes.
