### ISSUE TITLE
MDI clarification

### ISSUE THREAD

**Issue by chamnit** [vlachoudis/bCNC#23]
Here's a simple request. 

Add `MDI`, called Manual Data Input in CNC circles, in front of the command line at the bottom of the GUI window. This will help clarify its use and help users notice it.

**Comment by vlachoudis** [comment]
Good point! 

However the command line is far more powerful than simply sending commands to grbl.
You can do anything from the command line, like:
opening closing, reseting, homing, running, moving the gcode, rotating, cutting, profile calculations and many other (of course perfectly undocumented:)

Maybe called "Command:" to be more general is more appropriate

**Comment by vlachoudis** [comment]
@chamnit Done as "Command:" if it is confusing I could change it to MDI:

**Comment by Effer** [comment]
What about Command/MDI? It makes both.

**Comment by vlachoudis** [comment]
Command: MDI in the tool tip :)
