### ISSUE TITLE
Updates form is not translated

### ISSUE THREAD

**Issue by Effer** [vlachoudis/bCNC#230]
Hi @vlachoudis , for some reason it seems that the _ function is not working for the "Check for updates" form, even if the text is transaleted in the .po file.

![image](https://cloud.githubusercontent.com/assets/1007007/12897765/acec1efc-cea9-11e5-9e64-1e11bcfec665.png)

**Comment by vlachoudis** [comment]
My mistake. I forgot a dummy _() function when I was testing the Updates. :)
Now it is corrected.

**Comment by Effer** [comment]
Thanks.
