### ISSUE TITLE
Tool change on latest master branch

### ISSUE THREAD

**Issue by atrueresistance** [vlachoudis/bCNC#234]
Just pulled the latest master branch before shooting this video. https://youtu.be/qf4ZVV74A8s

What seemed to change? Before it was calibrate, and run for manual tool change. Pause never worked, but it was something I knew and expected (just remove that alligator clip quick). Changed to ignore M6 and back to cutting, but dang what happened? 

Let me know if you want the file. the start of it is as follows. I removed M9 and trailing M30(EOF) as bCNC sends to SO3 and the SO3 does not like.

```
(1-1.25adaptive)
(T2  D=0.125 CR=0.03 - ZMIN=-0.2 - bullnose end mill)
G90
G17
G20
G28 G91 Z0
G90

(2D Adaptive1)

T2 M6
S11028 M3
G54

G0 X3.0765 Y2.8146
Z0.6
Z0.2
Z0.1125
G1 Z0.1 F20
G3 X3.0392 Y2.7654 Z0.0966 I-0.0187 J-0.0246 F4.6
X3.0765 Y2.8146 Z0.0932 I0.0187 J0.0246
X3.0392 Y2.7654 Z0.0898 I-0.0187 J-0.0246
X3.0765 Y2.8146 Z0.0865 I0.0187 J0.0246
X3.0392 Y2.7654 Z0.0831 I-0.0187 J-0.0246
X3.0765 Y2.8146 Z0.0797 I0.0187 J0.0246
X3.0392 Y2.7654 Z0.0763 I-0.0187 J-0.0246
X3.0765 Y2.8146 Z0.0729 I0.0187 J0.0246
X3.0392 Y2.7654 Z0.0695 I-0.0187 J-0.0246
```

**Comment by vlachoudis** [comment]
@atrueresistance normally nothing happened in the Tool Change. I don't understand why for you the pause is not working. Do you use the english version? I saw one issue when unicode characters are used.

**Comment by vlachoudis** [comment]
@atrueresistance I've tried to do a quick fix, but I can only test later in the evening. Could you test it and let me know.

Just another remark, you don't need to remove the M9 and M30 commands manually you can
add in your .bCNC config file
in the [error] section the lines
M9 = 1
M30 = 1
0 = STOP, 1 = SKIP

**Comment by atrueresistance** [comment]
@vlachoudis Thanks, I'll pull down the master this morning and test it out and report back. Thanks for the error file info.

**Comment by atrueresistance** [comment]
@vlachoudis Manual toolchange is working again. Pause still isn't working, this is the correct setting right? 
![capture](https://cloud.githubusercontent.com/assets/7239809/12979036/40ef1f22-d09a-11e5-894d-81a30b993960.PNG)

**Comment by vlachoudis** [comment]
Indeed this is the correct settings.
It should pause twice once before and once after the tool change, by sending an "!" to grbl.
There was a discussion #163 similar, that by replacing the %pause in CNC.py internal bCNC command to "m0" pause was working correctly.

**Comment by vlachoudis** [comment]
@atrueresistance  I've just test it on my machine and it is working correctly. However
I've replaced the feed hold with m0 as it was suggested by @mano1979, and modified the code to correctly show the messages. Could you check if it works for you now?

**Comment by vlachoudis** [comment]
I couldn't test this behavior on my machine, so for me it was working before and now, @atrueresistance could you confirm that is working for you so I can close the issue?

**Comment by atrueresistance** [comment]
I didn't get a chance last night to try changing m0. Give me some time this weekend.

**Comment by mano1979** [comment]
I finally had the time to test it. After changing the "!" command to "m0\n", i get a pause before probing and after probing. I have set it to "only before probing" in bcnc. It really isn't a problem because we want time to remove the alligator clip, but i just wanted to mention it.

Also it would be great to have the message bar tell you the tool you have to change to. Now it quickly flashes a m06 message but before you can read it, it is gone.

**Comment by vlachoudis** [comment]
Are you running the latest grbl? For me it shows the message until you click resume.

**Comment by mano1979** [comment]
I don't believe so. Since i use "grbl-for-cyclone" ( arduino mega2560 and ramps1.4 )

It says version 0.9 though.

Vasilis Vlachoudis <notifications@github.com> schreef op 13 februari 2016 07:44:17 CET:
>Are you running the latest grbl? For me it shows the message until you
>click resume. 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/vlachoudis/bCNC/issues/234#issuecomment-183611718

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by atrueresistance** [comment]
Sorry for the late response. Just pulled the latest master. The machine does in fact pause now after hitting the touch plate, but the play button is grayed out. I am running grbl .9g. @mano1979 where did you change that command?

**Comment by atrueresistance** [comment]
![capture1](https://cloud.githubusercontent.com/assets/7239809/13180247/418ae8d6-d6ed-11e5-800b-ffb1d3756851.PNG)
![capture](https://cloud.githubusercontent.com/assets/7239809/13180251/441d5bba-d6ed-11e5-95df-5fb6030a8156.PNG)

Found it in CNC.py. It pauses, but just clocks. Play or terminal is not accessible.

**Comment by mano1979** [comment]
Indeed cnc.py is the file.

To resume/un-pause you right-click on the message bar where it says queue. Then you can click resume.

It would indeed be handy-er to have the pause button do this....

Frank Wiebenga <notifications@github.com> schreef op 19 februari 2016 16:45:23 CET:
>![capture1](https://cloud.githubusercontent.com/assets/7239809/13180247/418ae8d6-d6ed-11e5-800b-ffb1d3756851.PNG)
>![capture](https://cloud.githubusercontent.com/assets/7239809/13180251/441d5bba-d6ed-11e5-95df-5fb6030a8156.PNG)
>
>Found it in CNC.py. It pauses, but just clocks. Play or terminal is not
>accessible. 
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/vlachoudis/bCNC/issues/234#issuecomment-186267104

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by vlachoudis** [comment]
Or even if you right click on the status message you can access the pause/resume buttons

**Comment by mano1979** [comment]
Indeed. That is what i meant.

Vasilis Vlachoudis <notifications@github.com> schreef op 19 februari 2016 21:15:50 CET:
>Or even if you right click on the status message you can access the
>pause/resume buttons
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/vlachoudis/bCNC/issues/234#issuecomment-186385967

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by atrueresistance** [comment]
Super useful. did not know that was there
