### ISSUE TITLE
Can't save probe file in v0.9.0

### ISSUE THREAD

**Issue by sjj47** [vlachoudis/bCNC#235]
I downloaded v0.9.0 last night to pick up the fix for the Autolevel probe.   That part works great now, all the points on the grid are probed and the data is visible.  However, I can't save the probe data.  I go through the Save process, and a file is created, but it is empty.  I tried both Save-All and Save and got the same results.  

I've tried this several times now with the same results.  Is this a bug, or just a trick I am miwssing?  I was able to save the probe data in v0.7.3.

Thanks!

**Comment by vlachoudis** [comment]
I've put an "if" in the save code instead of "elif" resulting to save twice on the same filename
once as a "probe" and then override it with a gcode save. Now it is corrected
