### ISSUE TITLE
UnicodeDecodeError v0.9.0

### ISSUE THREAD

**Issue by Durga000** [vlachoudis/bCNC#236]
Again...

I can now open v0.9.0, homing position, but the reported position are not correct and I cannot move motors.
I have tried to change range of movement ( we never know) and the changes cannot be saved.
Each time i re-open bCNC, the range values are the original ones not the modified ones.

I Don't know if the 2 problems are linked or not, (maybe is it again my laptop) hereunder the error message:

Traceback (most recent call last):
  File "C:\Users\Pa\Documents\CNC\bCNC-master-3\bCNC-master\Utils.py", line 343, in __call__
    return self.func(*args)
  File "C:\Users\Pa\Documents\CNC\bCNC-master-3\bCNC-master\ControlPage.py", line 303, in setX0
    self._wcsSet("0",None,None)
  File "C:\Users\Pa\Documents\CNC\bCNC-master-3\bCNC-master\ControlPage.py", line 350, in _wcsSet
    data=(_("Set workspace %s to X%s Y%s Z%s")%(WCS[p],str(x),str(y),str(z))).encode("utf-8"))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)

Thanks

**Comment by vlachoudis** [comment]
I have the same problem on linux if I change the language. Once we started the internalization of the code I had to put explicitly the encode("utf8") function to pass the messages as utf8 to be displayed, otherwise tk was complaining. Now I have to remove the encode() to make it work. I don't understand what changed in between.

**Comment by vlachoudis** [comment]
The encoding error was preventing from setting the value in the WCS. Now should be ok.

**Comment by Durga000** [comment]
Sorry, I still have the issue. There is no more error indicated on the Python windows but the Wpos are wrong and I cannot move the motors...

**Comment by Durga000** [comment]
Sorry, the issue is not on bCNC as I have the same trouble with v 0.8.3

Just need to find out what I have changed...

**Comment by Durga000** [comment]
One of my axes was not well plugged... just feel stupid :-)

Once again Thanks for your work.

**Comment by vlachoudis** [comment]
@Durga000  don't worry, thanks for anyway for the Unicode bug :)
