### ISSUE TITLE
Already running. Please stop before

### ISSUE THREAD

**Issue by Effer** [vlachoudis/bCNC#24]
Hi,
  If accidently hit the run button without any Gcode loaded and then try to load a Gcode file, it's not possible to run anything, even hitting the stop button. You can't neither exist the program properly.

To reproduce:
Open bCNC
Open connection to Grbl 
Unlock
Click Run 
Click Stop
Load Gcode
Click Run 
Messagebox Already running should appear

I'm using Grbl 0.9i

**Comment by vlachoudis** [comment]
I've put a protection. Could you check if it is Ok?

**Comment by vlachoudis** [comment]
I had a small bug, not it is Ok.
