### ISSUE TITLE
Cannot reset wpos value

### ISSUE THREAD

**Issue by polnat** [vlachoudis/bCNC#240]
Hi,

After running once i cannot reset  wpos for any axis x, y or z.  sometime i have a strange value like -0.002

thanks

**Comment by vlachoudis** [comment]
@polnat when you click on a button like the X=0, Y=0 or Z=0 , please change to the Terminal tab and see if the command send to GRBL, and what grbl is replying.

**Comment by vlachoudis** [comment]
@polnat I have seen a similar thing on my machine. This is not bCNC issue a floating number rounding issue coming from grbl @chamnit when reporting coordinates far away from the real origin. I believe is purely aesthetics and wont influence your jobs.
