### ISSUE TITLE
Autolevel transform gCode not working correctly

### ISSUE THREAD

**Issue by atrueresistance** [vlachoudis/bCNC#247]
After running the autolevel the following gcode file will not run correctly. The spindle makes it to 

```
G00Z0.1
ok
G00X1.2541Y1.0788
G1X31.85414Y27.40152Z-0.487366
ok
G1X31.82366Y27.55392Z-0.488889
```

but no ok is ever given. Then the spindle goes towards home. You can see in the image where the spindle is relative to the board. 

[top.txt](https://github.com/vlachoudis/bCNC/files/139224/top.txt)
![capture](https://cloud.githubusercontent.com/assets/7239809/13197684/a4148f16-d7ba-11e5-979a-3389140b53b0.PNG)

Without the autolevel the code runs fine. I used flatcam to generate the code. 

Also here is the saved .probe file
```
12.3647 121.994 5
11.7932 84.5922 5
-10 5 10


12.3647 11.7932 0.000205722
39.772 11.7932 -0.324794
67.1792 11.7932 -0.574794
94.5864 11.7932 -0.724794
121.994 11.7932 -0.674794

12.3647 29.993 -0.224794
39.772 29.993 -0.549794
67.1792 29.993 -0.774794
94.5864 29.993 -0.924794
121.994 29.993 -0.849794

12.3647 48.1927 -0.399794
39.772 48.1927 -0.674794
67.1792 48.1927 -0.899794
94.5864 48.1927 -1.02479
121.994 48.1927 -0.949794

12.3647 66.3924 -0.524794
39.772 66.3924 -0.774794
67.1792 66.3924 -0.949794
94.5864 66.3924 -1.04979
121.994 66.3924 -0.974794

12.3647 84.5922 -0.624794
39.772 84.5922 -0.824794
67.1792 84.5922 -0.949794
94.5864 84.5922 -1.02479
121.994 84.5922 -0.949794
```

**Comment by vlachoudis** [comment]
Could you change grbl to report inches, as well bCNC to think in inches and try again?

**Comment by vlachoudis** [comment]
The first line in top.txt is G20 and is switching to inches.
If I find time the next days I will work to properly take into account the change of units in the autolevel part.

**Comment by vlachoudis** [comment]
I've just pushed a modified version of CNC.py which in principle should expand the paths first with the correct units and then strip the G20/G21 from sending to grbl. I don't have access to my machine to check
could you check if it works with your code (of course without changing to inches the grbl reporting)

**Comment by atrueresistance** [comment]
Yes, I am out right now. After running errands, I'll pull master and attempt again give me a couple hours.

**Comment by vlachoudis** [comment]
Ok. I think I have a solution right now. The new master is correcting now the autoleveled path to reflect the units the gcode is setting. I still haven't tried on my machine but dumping the code now seems ok.

**Comment by atrueresistance** [comment]
Wierd. So the first two holes it goes to drill them, and then goes back to origin. Not following the path like intended, but still cutting them where they are supposed to be. 

![2 hour level](https://cloud.githubusercontent.com/assets/7239809/13200361/b88e1bca-d809-11e5-95ed-1e0127e5d426.PNG)

You can see in the etched board where it went back to origin and then to the point engrave directly. The etchings near the holes are a good example. I could see this behavior as a really good way to break bits. 
![img_20160220_193633](https://cloud.githubusercontent.com/assets/7239809/13200364/e71fe4e6-d809-11e5-8cef-4f3dafa2b015.jpg)

Autolevel Time
![2 hr finish](https://cloud.githubusercontent.com/assets/7239809/13200362/c25630fc-d809-11e5-992c-59f65afcef96.PNG)

Autolevel really tacks on time compared to no autolevel

No Autolevel Time
![no-autolevel](https://cloud.githubusercontent.com/assets/7239809/13200363/cdf6357e-d809-11e5-8aeb-463d98eb97ea.PNG)

**Comment by vlachoudis** [comment]
I believe you have tested the first correction I've uploaded which was
changing the units to be similar with what grbl is reporting. However it
was not correcting the feed rate and the g0 motions :(

The second correction, is changing the autoleved path to reflect
the units in the gcode.
I've just run and dump your gcode with your probe information and here is the output
[run.txt](https://github.com/vlachoudis/bCNC/files/139505/run.txt)
Comparing the original (top.txt) and the autoleveled one the only
difference you will see is the z-correction in all the g1 motions.

**Comment by atrueresistance** [comment]
@vlachoudis most likely. I'll try the board again as soon as Amazon delivers another PCB. So is the feedrate and g0 motions fixed or has this turned into an enhancement item? 
How does autolevel handle clearance? So for instance flatcam sets .1 as the default safety height. If autolevel finds a valley that is .2 down followed by a hill that is +.2, does autolevel compensate for this?

**Comment by vlachoudis** [comment]
G0 and feed are fixed. Autolevel is only applied to the g1,g2,g3 so clearance has to be higher than any position of your pcb

**Comment by atrueresistance** [comment]
autoleveled a few jobs yesterday. looks like feed is good. closing issue

**Comment by vlachoudis** [comment]
perfect and sorry for your PCB. I will tag this as a new release

**Comment by atrueresistance** [comment]
Working pefectly thank you! ![img_20160225_214037](https://cloud.githubusercontent.com/assets/7239809/13342583/939e285c-dc08-11e5-97c0-f5c0992298fb.jpg)

**Comment by vlachoudis** [comment]
Nice. Why you don't make multipass? I use pcbgcode for eagle and with 2-3 multipasses it makes much nicer separation and cleans all the burr.

**Comment by atrueresistance** [comment]
Mostly because this is the first one ever, I've designed and made. Boy was it a learning process. For passes what was your depth per pass and feed?

**Comment by vlachoudis** [comment]
@atrueresistance  I didn't mean multipass in depth, but in the outline to make the isolation of traces thicker. I use a V-carve bit with 0.1mm tip and 30deg angle
and I typically ask 0.4mm isolation so it would make 4 passes.
Depth depends on the pcb. On the cheap ones I use 80um one some good ones I use 150um
Spindle is a 12000rpm and feed rate of 500-700 mm/min
