### ISSUE TITLE
End-stop

### ISSUE THREAD

**Issue by cyryllo** [vlachoudis/bCNC#257]
I use a program with Cyclone PCB. I have two endstop for the x-axis and y-axis. I don't see in the possibilities use zero position using these end-stop.

**Comment by CarlosGS** [comment]
Hi @cyryllo, sorry but I don't get what you mean :S
Can you give us some more detail?

**Comment by cyryllo** [comment]
Hello
I try set home in program, but get error
![zrzut ekranu z 2016-04-08 11 29 34](https://cloud.githubusercontent.com/assets/288180/14379954/50acc9d6-fd7d-11e5-9a24-a370bcb13722.png)
I setup my cyclonePCB https://github.com/carlosgs/grblForCyclone/wiki/1%29-Configure-bCNC-for-Cyclone
next try home 
![bcnc_3_home](https://cloud.githubusercontent.com/assets/288180/14380220/947e7c1c-fd7e-11e5-83bf-444d2364a854.png)


https://github.com/carlosgs/grblForCyclone/wiki/2%29-Hello-World!-Mill-a-bowl-with-bCNC

**Comment by Effer** [comment]
Hi @cyryllo , could be that the homing is disabled in GRBL? Can you try to read parameter $$?

![image](https://cloud.githubusercontent.com/assets/1007007/14391556/0a1d81e6-fdbd-11e5-8b30-f9487df26baf.png)

Sorry for this terrible screenshoot

**Comment by cyryllo** [comment]
Yes in cnc shield and Uno i have $22 disable. Now upload on ramps and mega and have enabled. Where can I change this in uno and shield? I use this firmware https://github.com/carlosgs/grblForCyclone/tree/grblForCyclone_CNCShield

**Comment by cyryllo** [comment]
I was turned on in the settings. Just make it work I had to clear the memory EEPROM :).
Now i enable ;)

**Comment by CarlosGS** [comment]
Awesome!!
I've added a note in https://github.com/CarlosGS/grblForCyclone/wiki/1%29-Configure-bCNC-for-Cyclone
Remember that you can also edit the github wiki pages if you find any step that is confusing, in order to help other people :)
Thanks @Effer for helping to find the issue
