### ISSUE TITLE
Connection win 7 64 bit

### ISSUE THREAD

**Issue by milezdr** [vlachoudis/bCNC#259]
Hi. I just find out about this grbl GUI and I have hard time connecting my arduino to the bCNC.
I'm using win 7 x64bit and I get this errors 
![pic 1](https://cloud.githubusercontent.com/assets/17602526/13546517/8a603c90-e2b0-11e5-9cbb-fa9ea2816293.JPG)
![pic2](https://cloud.githubusercontent.com/assets/17602526/13546518/8a61b5a2-e2b0-11e5-8c8b-bdf1c4e3a67a.JPG)

**Comment by vlachoudis** [comment]
Unfortunately the serial library is not part of the standard python package.
So as the dialog claims you have to install the additional serial library from python with the command that is mentioned there for windows

**Comment by Effer** [comment]
Hi @milezdr , it seem that you are missing pySerial module. It's a library for python that take care of serial comunication. You can easy install it following the wiki instruction: 

"
use the correct installer for the same version of your python installation. From a terminal (cmd) you can execute the command (where PythonXX is your python installation directory)
C:\PythonXX\Scripts\easy_install pyserial
"
