### ISSUE TITLE
Windows 10 Python 2.7.9 bCNC.bat 

### ISSUE THREAD

**Issue by rwensley** [vlachoudis/bCNC#262]
Greetings,

I am looking for help in getting the bat file to run.  

When I click on it a screen flashes then disappears.  No errors can be seen as it happens to fast.
I have also tried 'Run as Administrator'

Any help will be appreciated.

Ron Wensley

**Comment by Protoneer** [comment]
Insert "pause" at the end of the bat file to keep the cmd window open or
run the bat from cmd line.

**Comment by motanescu** [comment]
Hi Ron,
I think i had a similar problem
https://github.com/vlachoudis/bCNC/issues/266

**Comment by alfredanil** [comment]
+1 
Same error, not working from cmd line either

**Comment by vlachoudis** [comment]
Can you post a copy of the output from the terminal.

**Comment by mehadisaki** [comment]
I have same problem. cmd also show error

**Comment by rasciodc** [comment]
+1
Same problem here!

Already tried python x86, x64. No luck.

I used bCNC in the past on same laptop and used to run from bat file. 

Put "pause" at the end of the bat but all it gives is a cmd window showing "press any key to continue..."

**Comment by Harvie** [comment]
@rasciodc Do you have python2.7 installed?

**Comment by rasciodc** [comment]
> @rasciodc Do you have python2.7 installed?

Yes. 2.7.15 x86.

Tried to follow steps from #266 with no success. (tried pyserial 3.4 and 3.1)

**Comment by Harvie** [comment]
This is the best way to install and lunch bCNC on windows for now:
https://github.com/vlachoudis/bCNC/issues/964#issuecomment-440315914

It's also described in README

However it does not create any clickable icon. I don't use windows, so i don't really know how to do that. But i guess it will improve in the future. Pull requests welcome :-)

**Comment by rasciodc** [comment]
> This is the best way to install and lunch bCNC on windows for now:
> [#964 (comment)](https://github.com/vlachoudis/bCNC/issues/964#issuecomment-440315914)
> 
> It's also described in README
> 
> However it does not create any clickable icon. I don't use windows, so i don't really know how to do that. But i guess it will improve in the future. Pull requests welcome :-)

After following the instructions I'm able to run bCNC from the bat file again! So weird...

I observed that NumPy was installed during the process, which I'm not sure I had installed before... So I cannot confirm that it was the problem but could be related (as stated in #468).

Well done, thanks!!

**Comment by Harvie** [comment]
> I observed that NumPy was installed during the process, which I'm not sure I had installed before... 

Yes. It's very likely the cause. Check the README next time :-)

**Comment by rasciodc** [comment]
> > I observed that NumPy was installed during the process, which I'm not sure I had installed before...
> 
> Yes. It's very likely the cause. Check the README next time :-)

Yeah, I missed that... my bad. =)

But talking about user experience, a Windows user will inevitably follow steps on https://github.com/vlachoudis/bCNC/wiki/OS#windows , which makes it clear you need to install, in addition to Python itself, only the PySerial package. Perhaps adding NumPy to that list wouldn't hurt... 

Both the ReadMe and the link above mention the need for PySerial. Perhaps NumPy should also be mentioned in both places.

Thanks for your prompt and quick help!

**Comment by Harvie** [comment]
Yes. I have to update the wiki. Pip will now install all packages automaticaly, so there's no need for user to install them manualy one by one.
