### ISSUE TITLE
crash at job start 

### ISSUE THREAD

**Issue by se7en9057** [vlachoudis/bCNC#269]
when starting a job using cam paths generated from flat cam for PCB milling BCNC crashes and python begins a massive memory spike. after reaching 5G i killed the process. attached is the nc i was attempting to run. 

[front.zip](https://github.com/vlachoudis/bCNC/files/171167/front.zip)

system specs. 

intel processor
windows vista x64

**Comment by vlachoudis** [comment]
What python version you use?
I've tested it on linux and it works fine, with 37Mb a bit more than without anyfile.

**Comment by se7en9057** [comment]
Python 2.7.10 (May 23 2015)

**Comment by vlachoudis** [comment]
I have the same version on linux.
I will check on Windows later.

**Comment by se7en9057** [comment]
ok. thank you . if there are any log dumps just let me know where to find them and i'll post them.

**Comment by se7en9057** [comment]
looks like running it in mm fixed the issue.

**Comment by vlachoudis** [comment]
Did you use the auto leveling?

**Comment by se7en9057** [comment]
Yes. But when I got it to work I did the leveling in metric. So I'm thinking the imperial measurement was the issue.

**Comment by vlachoudis** [comment]
Could you send save and send us the autolevel .probe file (from the imperial test) so I could try to debug it.

**Comment by se7en9057** [comment]
sure i'll have to work on that tonight when i get home.


On Mon, Mar 14, 2016 at 9:55 AM, Vasilis Vlachoudis <
notifications@github.com> wrote:

> Could you send save and send us the autolevel .probe file (from the
> imperial test) so I could try to debug it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vlachoudis/bCNC/issues/269#issuecomment-196319466>.
>



-- 
-Andrew

**Comment by se7en9057** [comment]
[front.zip](https://github.com/vlachoudis/bCNC/files/174821/front.zip)

hopefully i did that right. i did an auto level and saved it. 

i think this is user error all around tho.

**Comment by vlachoudis** [comment]
@se7en9057 you've send the gcode and not the probe information. You have to save as ".probe"

**Comment by se7en9057** [comment]
sorry. still getting familial with the software.

On Wed, Mar 16, 2016 at 5:06 AM, Vasilis Vlachoudis <
notifications@github.com> wrote:

> @se7en9057 <https://github.com/se7en9057> you've send the gcode and not
> the probe information. You have to save as ".probe"
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/vlachoudis/bCNC/issues/269#issuecomment-197219687>
>



-- 
-Andrew

**Comment by vlachoudis** [comment]
Do you still experience the issue or it is solved?
