### ISSUE TITLE
Ability to open files on other drives.

### ISSUE THREAD

**Issue by Molex1701** [vlachoudis/bCNC#284]
Hello,
I can only open up files on my E drive. I can't change to another. Is this a python limitation?  I was really hoping to get this to run on Raspberry PI eventually and access my eagle files on my PC.

**Comment by atrueresistance** [comment]
See this issue for reference. https://github.com/vlachoudis/bCNC/issues/122

You need to just type in the network drive letter followed by a : and hit enter. Got me when i was new to bCNC.

**Comment by Molex1701** [comment]
Oh thanks for the info. I'm using your your software for a Cyclone PCB Factory. I've finally gotten it to move properly and do z-level probing.  I just need to order some proper bits to make some circuits.
