### ISSUE TITLE
Button Position

### ISSUE THREAD

**Issue by Guenni75** [vlachoudis/bCNC#288]
Hi.
I have a "Problem" with the 'move Gantry' and the 'WPOS' Button.
How can i hide or move one of them? 
You press the WPOS button quickly accidentally if you just want to move the gantry.

Or is there a way to customize the Toolbar?

**Comment by vlachoudis** [comment]
There is no configuration of the location of these buttons. One has to change the code in the CNCCanvas.py. Your comment is true. I believe they don't fit there. The toolbar should be intendent only for manipulating the canvas. Maybe I can put them as two big buttons in the Control panel under the X=0, Y=0, Z=0 buttons?

**Comment by Guenni75** [comment]
Just swapping the Ruler and the WPOS Button would be much better.

**Comment by vlachoudis** [comment]
I've temporarily move them (just for testing) under the Control status on the left. Let me know your impressions. I have the feeling that is better there.

**Comment by Guenni75** [comment]
They are better there, but still side by side!!
You press the WPOS button quickly accidentally if you just want to move the gantry.

**Comment by vlachoudis** [comment]
Yes, but they are bigger :). I could put one below x and the other below z.

**Comment by Guenni75** [comment]
This is what im talking about ;)

**Comment by Guenni75** [comment]
I think the button fit there very good.
