### ISSUE TITLE
Unwanted move after file open

### ISSUE THREAD

**Issue by Effer** [vlachoudis/bCNC#296]
Not sure if always been present, but I've just noticed that if you open a file and soon after click the canvas the gcode is moved away.

**Comment by vlachoudis** [comment]
Maybe I didn't quite understand what you mean, but I didn't notice any movement after loading the gcode.

**Comment by Effer** [comment]
Sorry sometimes my grammar scares also me  ;)

Strange enough it appears **only using the shortcut**..
How to reproduce:
- open a file using the Ctrl+O shortcut
- the selected canvas tools is an undefined state (see picture)
- click somewhere on the canvas
- all gcode get moved as if move command is applyed

Using the open button everything works correctly

![image](https://cloud.githubusercontent.com/assets/1007007/14469455/efacd0ca-00e4-11e6-83f5-a208bfc20592.png)

**Comment by vlachoudis** [comment]
Thanks. I've just correct it. I was using the default Tkinter bindings <Key-o> for the origin command in the Canvas and the <Control-Key-o> for open file. Suprisingly enough with Ctrl-o both handlers were invoked.
Now I modified the Canvas to use the generic <Key> handler and I do the parsing, which works better.
