### ISSUE TITLE
Probing with ID 33 error

### ISSUE THREAD

**Issue by danst0** [vlachoudis/bCNC#309]
Hi,

I am struggling with an GRBL error. However I think it might be related to bCNC. I try to probe my new tool in the beginning or after tool change.
The commands / errors are as follows:

> g53g0z0.0
> g91G38.2f20.0z-0.0
> g4p1
> ok
> ok
> ok
> ok
> error: Invalid gcode ID: 33
> ALARM: Hard limit

The detailed error is shown in the screenshot:
![2016-04-30-224720_1280x1024_scrot](https://cloud.githubusercontent.com/assets/1544506/14938508/15de97f2-0f26-11e6-9a51-483cf9121d14.png)

This error is thrown no matter if I am already at the X/Y-Probing position or if I am away.

Daniel

**Comment by vlachoudis** [comment]
From your output it seems you are starting the probe from Z=0.0 until Z=0.0

**Comment by danst0** [comment]
I am still unsure what I am doing wrong. Picture 1 is directly after the homing cycle. 
![2016-05-03-204634_1280x1024_scrot](https://cloud.githubusercontent.com/assets/1544506/14994442/4e245970-1170-11e6-9ed3-6bdda374530a.png)


After that I press the calibrate button. Then the ID 33 error shows up immediately, however the X/Y move to the Probing coordinates is still performed, then the machine stops (picture 2).

![2016-05-03-204651_1280x1024_scrot](https://cloud.githubusercontent.com/assets/1544506/14994443/4e45d528-1170-11e6-8154-dc65f1f132ac.png)

**Comment by vlachoudis** [comment]
You have to set a value in the "Distance:" field. This is the probing distance to travel from "Probe:MZ" to "Probe:MZ - Distance". Since it is 0.0 the probing fails immediately. I believe is a good point that I should protect it, or at least issue a message to the user.

**Comment by danst0** [comment]
Thanks for the quick feedback! Now it works!

Daniel

**Comment by vlachoudis** [comment]
Great. I've added also a warning message if it is not set :)
