### ISSUE TITLE
Small bug when rotating g-code

### ISSUE THREAD

**Issue by lakeroe** [vlachoudis/bCNC#311]
I think bCNC contains a small bug when rotating g-code.
Just try [this](https://github.com/vlachoudis/bCNC/files/248233/Spannpratzen.zip) code ...

**Comment by vlachoudis** [comment]
Thanks @lakeroe. I've just fixed it. The transformation code was wrongly writing only the variables there was present. In your code you had lines like "g1 y##" without an "X##". The rotation was altering both but was not writing the modified "X'. Now I am writing all modified variables.
