### ISSUE TITLE
Autolevel

### ISSUE THREAD

**Issue by Guenni75** [vlachoudis/bCNC#316]
Is there a way to aboard the autolevel Scan? 
I can not find a button for this.

**Comment by atrueresistance** [comment]
Abort? You can click the stop button

**Comment by Guenni75** [comment]
There is no Stop Button in the Probe Menu.
No Chance to Press Stop at an emergency.

**Comment by Effer** [comment]
Hi @Guenni75 . That's true, the default configuration doesn't give you the "Run" ribbon in the probe tab. But you can modify some settings to customize  the tab and give you a configuration like this:

![image](https://cloud.githubusercontent.com/assets/1007007/15274727/457d239e-1aba-11e6-8f6a-ec8e0b8a9b0a.png)

To do this you have to manually change the configuration file. Unfortunately this have to be done with an external editor. 

_The file is created in you user directory. **NOT** the "bCNC.ini" file in the bCNC folder. The exact location of this file depends on you operating system here for windows:You can reach it easily using the Environment variable %UserProfile% . Hit [Windows key + R] paste %UserProfile% in the Run prompt, then click OK. The user folder will open and there you'll find the .bCNC file. Right click and choose "open with" then select notepad._

Now you have to add this line in [bCNC] section: **probe.ribbon = Connection Probe Run**

The **Run** option will add the buttons you need. Maybe in the future it will be better integrated.

Another customization I like in my setup is to bind some shortcut to the run-stop buttons. In this way I have some physical button to use. Go to Tools-->Shortcut and customize some buttons:

![image](https://cloud.githubusercontent.com/assets/1007007/15274807/fc019f0e-1abb-11e6-9054-353a65462c69.png)

Response to stop command is fast, but if you need a more reliable and secure way to stop your machine consider to add some real physical buttons, GRBL is ready to accept them.
