### ISSUE TITLE
How add submenu Cut Direction (Climb and Conventional) to menu Pocket and Cut? 

### ISSUE THREAD

**Issue by marketa888** [vlachoudis/bCNC#321]

**Comment by vlachoudis** [comment]
As it is now, the pocket/profile/cut direction remains as it is defined in the path. However you can change it from the "Editor -> Route" . And you can visualize it with the "Editor -> Info -> Info" or the shortcut "n" in the canvas.

**Comment by marketa888** [comment]
I see now , it's easy , thank you.

**Comment by marketa888** [comment]
Conventional/Climb/Rewerse in Route-menu not work properly.
It always gives  Climb metod.
I do not know where I make an error?

please see pocket circle 10mm
-----
(Block-name: Header)
(Block-expand: 0)
(Block-enable: 1)
M3 S12000
G4 P3
(Block-name: 0)
(Block-expand: 1)
(Block-enable: 0)
g0 x10 y0
g1 z0 f10
g3 x10 y0 i-10 j0 f127
g0 z1
(Block-name: 0 [pocket,conventional])
(Block-expand: 1)
(Block-enable: 1)
g0 x0.7925 y0
g1 z0 f10
g3 x0.7925 y0 i-0.7925 j0 f127
g1 x2.0625 y0
g3 x2.0625 y0 i-2.0625 j0
g1 x3.3325 y0
g3 x3.3325 y0 i-3.3325 j0
g1 x4.6025 y0
g3 x4.6025 y0 i-4.6025 j0
g1 x5.8725 y0
g3 x5.8725 y0 i-5.8725 j0
g1 x7.1425 y0
g3 x7.1425 y0 i-7.1425 j0
g1 x8.4125 y0
g3 x8.4125 y0 i-8.4125 j0
g0 z1
------
From inside to outside CCW is Climb not Conventional !


and after convert Climb :
-------
(Block-name: Header)
(Block-expand: 0)
(Block-enable: 1)
M3 S12000
G4 P3
(Block-name: 0)
(Block-expand: 1)
(Block-enable: 0)
g0 x10 y0
g1 z0 f10
g3 x10 y0 i-10 j0 f127
g0 z1
(Block-name: 0 [pocket,climb])
(Block-expand: 1)
(Block-enable: 1)
g0 x8.4125 y0
g1 z0 f10
g2 x8.4125 y0 i-8.4125 j0 f127
g1 x7.1425 y0
g2 x7.1425 y0 i-7.1425 j0
g1 x5.8725 y0
g2 x5.8725 y0 i-5.8725 j0
g1 x4.6025 y0
g2 x4.6025 y0 i-4.6025 j0
g1 x3.3325 y0
g2 x3.3325 y0 i-3.3325 j0
g1 x2.0625 y0
g2 x2.0625 y0 i-2.0625 j0
g1 x0.7925 y0
g2 x0.7925 y0 i-0.7925 j0
g0 z1
------
from outside to inside CW it is Climb !
The change applies to the entire block and not just selected gcode block.

**Comment by vlachoudis** [comment]
@marketa888 it is true, I forgot to consider the direction in the pocket. I will correct it :)

**Comment by vlachoudis** [comment]
@marketa888 actually I was wrong :) the behaviour if you have a g2 and you do a pocket it will create g2, if you have g3 it will create g3, so it keeps the initial orientation

**Comment by marketa888** [comment]
OK. And  radius "r"  changes from low to high and vice versa
needlessly. IMHO :(  
I get always climb milling

**Comment by vlachoudis** [comment]
Pocket will start always from inside to outside (smaller r to bigger r). This is done on purpose to reduce the amount of cuts that the tool is cutting full diameter.

**Comment by marketa888** [comment]
I so want . from small to bigger. If I click reverse selected block I have a radius from large to small :(

**Comment by marketa888** [comment]
only change g2g3 not a radius in selected block to change. please

**Comment by vlachoudis** [comment]
Toi have to click reverse before the pocket operation

**Comment by marketa888** [comment]
So working properly , a little harder to fix later . I miss the icons " find and replace" in the editor.

**Comment by vlachoudis** [comment]
Find and replace could be an addition to the editor. Please add it to the "feature request" issue
