### ISSUE TITLE
Feedrate

### ISSUE THREAD

**Issue by Guenni75** [vlachoudis/bCNC#341]
Could you show the real Feedrate calculated with the Feed Override?
This could be very usefull at testing new materiels and cutter.

I think there is a Problem,too.
Every time i looked in the Terminal, the feed rate of all moves was the same (with Feed Override).
If I have a feedrate of 200 and a plungerate of 100, the Feed Override (for example 150%) sets both to the same rate (300).

**Comment by Effer** [comment]
Hi @Guenni75 , you're right. There's a problem with feed override. I've Pull Request a small fix, but maybe the whole part should be rewritten.
