### ISSUE TITLE
[request]

### ISSUE THREAD

**Issue by atrueresistance** [vlachoudis/bCNC#348]
Is there a way to be able to send a command much like the file footer, but instead a json or webapi hit? I have something like [this](http://www.amazon.com/Securifi-Remotely-Control-Appliances-Interface/dp/B00TC9NC82) (the older version) which connects to my router. This is plugged into the tool port on my vacuum. I can turn the router on my SO3 on/off with my phone or logged into the router. There is an api, and it would be cool to get it working at the end to shut the router down by triggering an api call.

**Comment by Effer** [comment]
With the integrated python script parse, you could do quite everything. You have simply to proceed the python code with the **%** symbol.
Here I call a external program (saved in c:\beep.exe) with a user button.

![image](https://cloud.githubusercontent.com/assets/1007007/15798092/7b707532-2a2d-11e6-9dac-0229ff2b256f.png)

In tehory the same thing can be done even in the gCode, but there are some drawback.
![image](https://cloud.githubusercontent.com/assets/1007007/15798107/0df34696-2a2e-11e6-883e-dc358d524f42.png)
First you must proceed the code with the **%wait ** command to synchronize the stream with the controller.
But the big problem is that the code is executed every time you modify the line in the editor or reload the file.
Maybe this behavior should be changed.

**Comment by vlachoudis** [comment]
@Effer it is executed on every refresh since it expects to return a dynamic gcode.
Maybe we can have a keyword as a prefix to specify when to execute the code

**Comment by Effer** [comment]
@vlachoudis yes, something that could identify what to process only when it is executed in grbl. This to avoid even the %wait command. In this way it could be easy even to use the RPI GPIO.

**Comment by vlachoudis** [comment]
@Effer I've added your request in #310
