### ISSUE TITLE
autolevel - rescan one point

### ISSUE THREAD

**Issue by 466** [vlachoudis/bCNC#361]
Hi there,
I am using the autolevel function for pcb milling, which works quite well most of the time.

Sometimes though, some points do not get scanned correctly, way above the pcb.
I think this is due to some electrical noises oder what ever, which seems to happen every now and then.
Is there a way to rescan an already (but wrong) scanned point?

I hope there is one :)

Best regards!

**Comment by vlachoudis** [comment]
There is no automatic way to rescan problematic points. However you can do it manually. 
- First save the autolevel information into a file with extension .probe.
- Open it with any text editor
- Move the gantry to the problematic location
- Do a single probing
- Copy the z-probe value and override the value in the text file
- Save the text file in the editor
- Load the probe file into bCNC again

However I would suggest to better filter the probe signal for noises
