### ISSUE TITLE
Autolevel and G02 - State error: Invalid gcode ID:36

### ISSUE THREAD

**Issue by sanotronics** [vlachoudis/bCNC#362]
I will just link to the issue I opened in grbl's GH.

To make it short, I tried to mill a PCB with arcs in the corners and bCNC's autolevel feature changed the gcode G02 arc commands to G01 line commands and forgot to erase the R words, so GRBL throws the id 36 error, and the mill stops at the arc.

I ran the same program without the autolevel feature, and it went all the way through :)

![primerpcbmilled](https://cloud.githubusercontent.com/assets/4588575/16167760/8b0c6c9c-34cf-11e6-9012-9b8b631e765a.jpg)

**Comment by vlachoudis** [comment]
Thanks for reporting. I will give a look

**Comment by vlachoudis** [comment]
I forgot to remove the 'R' when the path was autoleveled, the IJK were removed :)
Now it should be ok. Could you test it?

**Comment by sanotronics** [comment]
Yes, I'll try to test it later today.

Will I notice a difference in the smoothness of the arc, running it this way, which makes it into lines?

If so, then maybe I'll prefer running it without the autolevel feature, since I only care that it mills through the board up to the waste board, and for that I don't really care if the board is not leveled.

**Comment by vlachoudis** [comment]
@sanotronics the accuracy of the arc->line conversion is controllable in the ```Tools->Machine->Plotting Arc accuracy``` by default is set to 0.01. This is means maximum offset between the line and arc of 10micrometer.

**Comment by sanotronics** [comment]
Awesome :+1:

**Comment by vlachoudis** [comment]
Great I am closing the issue then.
