### ISSUE TITLE
Small bug when mirroring g-code ?

### ISSUE THREAD

**Issue by lakeroe** [vlachoudis/bCNC#363]
I think bCNC contains a small bug when mirroring g-code (horizontally or vertically).
Maybe this is related to bug #311.
If you can't reproduce the issue I can give more details.

**Comment by vlachoudis** [comment]
Can you post an example

**Comment by lakeroe** [comment]
Sure, an example is [Rohling.txt](https://github.com/vlachoudis/bCNC/files/322418/Rohling.txt) and also a screenshot before and after mirroring vertically.

![before](https://cloud.githubusercontent.com/assets/6253801/16178930/7eb1c28e-3656-11e6-839a-577a3dc625cb.jpg)
![after](https://cloud.githubusercontent.com/assets/6253801/16178932/8a0c4456-3656-11e6-985e-bda78e29b02f.jpg)

**Comment by vlachoudis** [comment]
At some point I was leaving as such the "M" commands in the processing and at some point I've added also the "G" which made this mess. Now it is fixed.

**Comment by lakeroe** [comment]
Thanks a lot
