### ISSUE TITLE
Force Render out?

### ISSUE THREAD

**Issue by atrueresistance** [vlachoudis/bCNC#364]
Is there a way to force rendering. I'm guessing it stops because it takes too long. In reality it doesn't take that long, but would really like to see actual margins. 

![image](https://cloud.githubusercontent.com/assets/7239809/16172763/7a8bef0c-3554-11e6-9701-e1d7a6714a74.png)
![image](https://cloud.githubusercontent.com/assets/7239809/16172766/8b67825a-3554-11e6-83cc-c01ed9c1df4d.png)
![image](https://cloud.githubusercontent.com/assets/7239809/16172769/91ff6d8a-3554-11e6-805e-d480720db6d7.png)

**Comment by atrueresistance** [comment]
INF does not seem to do it. 

![image](https://cloud.githubusercontent.com/assets/7239809/16173517/da4f09b0-3568-11e6-9e16-9badfee0f72d.png)

120 does 

![image](https://cloud.githubusercontent.com/assets/7239809/16173527/fc4372ae-3568-11e6-8d75-979bc03e6f65.png)

**Comment by vlachoudis** [comment]
Thanks, I've updated the infinite time (set internally to 5min :)
