### ISSUE TITLE
Translation to Portuguese

### ISSUE THREAD

**Issue by moacirbmn** [vlachoudis/bCNC#371]
I did translation to Portuguese, and is almost complete, how do uploud? which folders should I send?

**Comment by Effer** [comment]
Hi @moacirbmn , 
with git you can open a pull request and it will contain all needs.

If you have follow this How To: https://github.com/vlachoudis/bCNC/wiki/How%20to%20contribute%20a%20translation 
you should have end now with this structure in the bCNC folder: **\bCNC\locale\pt\LC_MESSAGES**
(I'm not sure if pt is the correct language code for Portuguese) and inside you should have 2 files **bCNC.mo** and **bCNC.po**
This is all it needs I believe.

**Comment by moacirbmn** [comment]
I'm putting more translations but can not upload the folder to the github (the translation I'm doing is for Brazil's Portuguese)

**Comment by vlachoudis** [comment]
@moacirbmn if you don't succeed in making a pull request, post your files on this issue and I could upload them.
BTW what is the difference of Brazilian Portuguese and the ones from Portugal?

**Comment by moacirbmn** [comment]
@vlachoudis It appears to me it "Uploads are disabled.
File uploads require push access to this repository. "

I will try for send you the file already ready to put in the repository.

to answer your question, the difference between Portuguese of Portugal and Brazil are few, usually in few technical terms and adjectives.

**Comment by moacirbmn** [comment]
@vlachoudis I am still new at development with github, How can I send the file to you?

**Comment by vlachoudis** [comment]
How to create a pull request: https://help.github.com/articles/creating-a-pull-request/
The files you could upload them to any file sharing site, or even on google drive and share the link

**Comment by vlachoudis** [comment]
It is strongly preferable to make a pull request it will help you for subsequent changes.

**Comment by moacirbmn** [comment]
@vlachoudis sorry, I'm very inexperienced and I think I messed up when I made the request, so I decided to put in my google drive the folder with the translation.

https://drive.google.com/folderview?id=0ByoRhH0i6j6sUWpkNlRQZ1BxZW8&usp=sharing

**Comment by vlachoudis** [comment]
@moacirbmn thanks. I've just added it

**Comment by Effer** [comment]
Thanks @moacirbmn. 
To keep it updated, learn some git commands will help a lot. There are even some GUI that make it easy.
Anyway if you have doubt feel free to ask (even PM) or post somewhere the updates files.

**Comment by moacirbmn** [comment]
They can make an update of the translation in Portuguese?
I made over 25% of translation

https://drive.google.com/folderview?id=0ByoRhH0i6j6sUWpkNlRQZ1BxZW8&usp=sharing

**Comment by Effer** [comment]
Merged. Thanks @moacirbmn
