### ISSUE TITLE
order.optimize doesn't account for toolchanges 

### ISSUE THREAD

**Issue by RicII** [vlachoudis/bCNC#382]
The ordering in the editor, especially optimize is not aware off tool changes between blocks which
makes the clone & tile operations less useful.

Ideally it should group blocks on tool to minimize tool changes and optimize the resulting path accounting for the tool change (& optional probe) position. (using the manual tool change macro)

**Comment by vlachoudis** [comment]
Optimize simply moves blocks of code to minimize the g0 patps. All commands inside the block will remain as is therefore to changes etc will not be rearranged. Maybe in the future can be mage not smart. So for the moment it is reconnected to apply the optimization selectively

**Comment by vlachoudis** [comment]
Just for clarification. The optimization was done for optimizing the imported dxf before generating the gcode. Optimizing/reordering  already existing gcode can lead to unpredicted behavior, it has to be done with care.

**Comment by RicII** [comment]
Noted, I got the impression that the tool change support was a later addition as well. The cleanest way to implement this would probably to create an other hierarchy level in the editor.
