### ISSUE TITLE
 All axes move on probing 

### ISSUE THREAD

**Issue by danst0** [vlachoudis/bCNC#383]
![img_0294](https://cloud.githubusercontent.com/assets/1544506/17054594/49e5ffc2-5008-11e6-9af2-8974545bf0d0.JPG)
 Hello
Am I doing something wrong with my settings for probing the z axis?
If I press the probe button on the right with these settings (see picture) not only the z axis moves but also X and Y axes.
Any hints?
Daniel

**Comment by vlachoudis** [comment]
Just don't fill the x and y with zeros. Leave them empty. If you set a value it tells grbl to probe along that path.

**Comment by danst0** [comment]
Thank you very much, I will try it as soon as possible. I was not aware that these were machine coordinates.
