### ISSUE TITLE
Only first tool change executed

### ISSUE THREAD

**Issue by danst0** [vlachoudis/bCNC#392]
Hi,

I did the following test pattern with three tools.
Only the first tool change is executed. Between second and third there is only a "hold"-break but no tool change cycle.

Any hints?

Daniel
[20160803 Test Werkzeugwechsel.txt](https://github.com/vlachoudis/bCNC/files/398764/20160803.Test.Werkzeugwechsel.txt)

**Comment by vlachoudis** [comment]
You have not specified a tool number T## for the M6 commands.
bCNC is checking if the tool number has changed and performs the change if different.

**Comment by danst0** [comment]
Makes sense! Thank you
