### ISSUE TITLE
Tabs tutorial in the wiki

### ISSUE THREAD

**Issue by ThierryM** [vlachoudis/bCNC#393]
Hi,
I have added a new page ([https://github.com/vlachoudis/bCNC/wiki/Tabs-tool](https://github.com/vlachoudis/bCNC/wiki/Tabs-tool)) in the wiki where I try to explain how to create holding tabs : I describe the way how I succeeded to use this feature.
Obviously, you can append / correct this page.
Regards

**Comment by Effer** [comment]
Hi @ThierryM , thanks to your effort in improve the always late bCNC documentation.
I'd like to use this opportunity to propose to add a direct link to the Wiki in the main page of bCNC repository. Often issues open refer to already documented procedure.
