### ISSUE TITLE
class CNC has no attribute 'parseLine2' when manually sending commands

### ISSUE THREAD

**Issue by ntoff** [vlachoudis/bCNC#398]
Sending a gcode file seems to work fine but when entering anything into the "Command" box, I get this error popping up.

![error](https://cloud.githubusercontent.com/assets/9030085/17456000/aa579856-5c0c-11e6-8418-d1898c3bbede.PNG)

Running on windows 10
>Python 2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)] on win32

Other python programs work fine, eg Printrun (pronterface)

**Comment by vlachoudis** [comment]
@ntoff thanks. I've just corrected it.
