### ISSUE TITLE
lower Case G-Code from cnc.py

### ISSUE THREAD

**Issue by TSpielmann** [vlachoudis/bCNC#408]
Tools using cnc.py (like Text or Bowl) create G-Code with LowerCase Commands. 
I m using bCNC with Smoothieware  edge-1aa47c6, Build date: Aug 17 2016 04:05:43 and got Command Errors. 
Patching cnc.py to produce UpperCase Code and modifing the Plugin Code to Output UpperCase initial Code (like "F" instead "f") solves it for me.
Don't Know if this is an bCNC or Smoothieware Issue! (Sorry If wrong Place)
If this is an Issue, it hits the Plugins too.

**Comment by vlachoudis** [comment]
It's true that bcnc generated most of the code in lower case while smothie needs upper case. However if you select the smothie board as a controller when the gcode will be sent to smoothie it will be converted to uppercase.

**Comment by TSpielmann** [comment]
That's right and was my Mistake. (not switched to Smoothie)
I beg your pardon!
