### ISSUE TITLE
[Flatten Plugin] - Generated GCode file don't respect the settings

### ISSUE THREAD

**Issue by onekk** [vlachoudis/bCNC#412]
When I use flatten plugin and want to save the file, the block that define the "raster border" is generated and saved in the GCode produced.

I noted that it is defined in the code with (Block-enable: 0)

I can guess that bCNC will not execute this code, but if you rely on the generated code and use it on another "sender" it will not do what you expect.

The questions are:

1) I guess correct?
2) if 1 is yes there is a manner to avoid this without manual delete the block in every generated file?

**Comment by vlachoudis** [comment]
1. yes
2. No.

Unfortunately is a way in bcnc to add metadata in the gcode

**Comment by onekk** [comment]
OK Many thanks.

**Comment by Effer** [comment]
There was another user, some time ago, who asked for a way to export the modified gcode without all the metadata (maybe to the clipboard?). Maybe we could even add an option to omit the disabled gcode from that export.

**Comment by onekk** [comment]
This solution will be good, a save option in the editor tab or maybe a "save Gcode" in file tab that trigger a save window when you could choose some the option like "don't save disabled block" and maybe "save gcode in uppercase", I know grbl will accept even lowercase, but almost all GCODE i've seen is uppercase.

Regards

**Comment by Effer** [comment]
@onekk latest commit #416 has the capability to save gcode as plain text. (only enabled block in uppercase)

**Comment by onekk** [comment]
Thanks, i read only now, i will try maybe monday :-D
