### ISSUE TITLE
Editor 

### ISSUE THREAD

**Issue by rennen11** [vlachoudis/bCNC#417]
With some G-code I can`t see any geometrie in the geometrie window.
loading another file I can see geometrie.
Comparing the two codes shows no difference in commands, only in coordinates.
Running python 2.7 on Win7

**Comment by Effer** [comment]
Can you post the code? You can zip and upload it here or use https://pastebin.com/

**Comment by rennen11** [comment]
Hei Filippo,

 

Here is the code.

With other codes the behavior is also sometimes funny.

When I load a code after another, Istill see the picture of the previous part.

Clicking on the toggle display switch brings up the new one.

 

Another Question:

In the Open File Windows I have only access to C:\ , I am not able to change to disc B:

 

Many thanks to your help.

 

Rennen11

 

Von: Filippo [mailto:notifications@github.com] 
Gesendet: Dienstag, 6. September 2016 07:15
An: vlachoudis/bCNC <bCNC@noreply.github.com>
Cc: rennen11 <rennen11@web.de>; Author <author@noreply.github.com>
Betreff: Re: [vlachoudis/bCNC] Editor (#417)

 

Can you post the code? You can zip and upload it here or use https://pastebin.com/

**Comment by Effer** [comment]
Hi  @rennen11 ,

I can't see any file attached.
The behavior you describe is quite strange, try to change the "time out display" in the combobox on the top-right corner of the rendering canvas. Default value is 2 (seconds) after that time the drawing is suspended and a warning should appear on the bottom of bCNC window.

To navigate to another folder write the desired path in the open file dialog:

![image](https://cloud.githubusercontent.com/assets/1007007/18348884/4bdd4d6c-75ce-11e6-86ce-3b51b4f70764.png)

It seems there's no easy and cross platform way, to list all disks in python.

**Comment by rennen11** [comment]
An other try.

 

Von: Filippo [mailto:notifications@github.com] 
Gesendet: Donnerstag, 8. September 2016 14:15
An: vlachoudis/bCNC <bCNC@noreply.github.com>
Cc: rennen11 <rennen11@web.de>; Mention <mention@noreply.github.com>
Betreff: Re: [vlachoudis/bCNC] Editor (#417)

 

Hi  <https://github.com/rennen11> @rennen11 ,

I can't see any file attached.
The behavior you describe is quite strange, try to change the "time out display" in the combobox on the top-right corner of the rendering canvas. Default value is 2 (seconds) after that time the drawing is suspended and a warning should appear on the bottom of bCNC window.

To navigate to another folder write the desired path in the open file dialog:

 <https://cloud.githubusercontent.com/assets/1007007/18348884/4bdd4d6c-75ce-11e6-86ce-3b51b4f70764.png> 

It seems there's no easy and cross platform way, to list all disks in python.

**Comment by Effer** [comment]
No luck neither this time. I suppose you have to use the web page to upload the file, attaching with your email client doesn't work with github.

Does this happen after you select the geometrie and hit canc to delete it?

**Comment by rennen11** [comment]
hope you can see the file now.
[SD7080_190_Bearb_1.zip](https://github.com/vlachoudis/bCNC/files/462114/SD7080_190_Bearb_1.zip)

**Comment by rennen11** [comment]
hope you can see the file now.
[SD7080_190_Bearb_1.zip](https://github.com/vlachoudis/bCNC/files/462128/SD7080_190_Bearb_1.zip)

**Comment by Effer** [comment]
Hi @rennen11 ,
got the file ;)

I think is just a matter of file format. The file you provide use the number of line at the begin (N10 .. N20 and so on). It's seems like bCNC doesn't like it. There's a function defined in the code (*removeNlines*) but it's never call and miss full implementation.
To add in in the TODO @vlachoudis ?

**Comment by Effer** [comment]
@rennen11 I was wrong. bCNC support NCodes.
In your file there is the G94 code in line N140 that broke the parser. If move the GCode to line before everything look good

![image](https://cloud.githubusercontent.com/assets/1007007/18396001/a57bbc0c-76c1-11e6-82bd-0d5d125830c7.png)

**Comment by Effer** [comment]
It seems like method motionStart in CNC.py doesn't accept some expression that grb can work with.
As example any movement G0/1/2 that contains a G93 or G94 in the same line. It's accepted by grbl but broke the canvas rendering.

It's seem easy to fix

```python
elif gcode==91:
	if decimal == 0:
		self.absolute = False
	elif decimal == 1:
		self.arcabsolute = False

#new code for feedmode
elif gcode==93:
	pass

elif gcode==94:
	pass

elif gcode==95:
	pass
#end of new code for feedmode

elif gcode==98:
	self.retractz = True

```

But before a PR I prefer to wait @vlachoudis for clarification

**Comment by rennen11** [comment]
If I put the G93 or G94 in an extra line, the rest of the code is also not shown.

But it`s not a problem for me because its not necessary for me to use it.

Thank’s for your efforts

 

Von: Filippo [mailto:notifications@github.com] 
Gesendet: Freitag, 9. September 2016 22:23
An: vlachoudis/bCNC <bCNC@noreply.github.com>
Cc: rennen11 <rennen11@web.de>; Mention <mention@noreply.github.com>
Betreff: Re: [vlachoudis/bCNC] Editor (#417)

 

It seems like method motionStart in CNC.py doesn't accept some expression that grb can work with.
As example any movement G0/1/2 that contains a G93 or G94 in the same line. It's accepted by grbl but broke the canvas rendering.

It's seem easy to fix

elif gcode==91:
    if decimal == 0:
        self.absolute = False
    elif decimal == 1:
        self.arcabsolute = False
 
#new code for feedmode
elif gcode==93:
    pass
 
elif gcode==94:
    pass
 
elif gcode==95:
    pass
#end of new code for feedmode
 
elif gcode==98:
    self.retractz = True

But before a PR I prefer to wait  <https://github.com/vlachoudis> @vlachoudis for clarification

**Comment by vlachoudis** [comment]
@effer is correct. I've pushed an update
