### ISSUE TITLE
How to config WorkArea

### ISSUE THREAD

**Issue by Scott216** [vlachoudis/bCNC#42]
How does the WorkArea view work?  When I bring in a file it looks like this:
![bcnc worarea screenshot](https://cloud.githubusercontent.com/assets/819693/7666772/a3fafcdc-fbbe-11e4-8793-949d129c7e18.JPG)
I've got GRBL setup so when it homes, it sets x y and z to zero, not negative numbers like the default.

I posted the gcode I used in the above screenshot here: http://pastebin.com/X1P66uwV

**Comment by chamnit** [comment]
I think it's based on the machine coordinate system and G92 offsets. Once you set part zero within the machine volume, the g-code paths should be inside the yellow box.

**Comment by Scott216** [comment]
I don't use G92 for anything.  In this example I used G55 WCS.  After selecting G55 there was no change to the work area.  My gcode paths are still outside the area.

**Comment by Effer** [comment]
@Scott216  working area is displayed based on some settings in Configuration file the fields are named **feedmax_x**, **feedmax_y**  and  **feedmax_z**   
The problem is that for some reason the values are readen in the opposite direction. So to have a try you can add a minus in front of the actual values. It seems also that the minus sign must be immediately after the equal symbol or will not be read correctly.  
I suspect @vlachoudis will fix this in a couple of nano seconds.

Have a look at <https://github.com/vlachoudis/bCNC/wiki/Configuration> on how reach the file based on your OS.

**Comment by Scott216** [comment]
I'll give that a try.

**Comment by vlachoudis** [comment]
@Effer the numbers are used as negative to describe the workarea, because this is what I was getting out from the grbl. Looking at the (thread)[https://github.com/grbl/grbl/issues/678] this is the default behavior of grbl. However @Scott216 after zeroing the G55 workspace it should come out right?

**Comment by Effer** [comment]
That have a sense. Now I remeber that by tradition the coordinate system is referenced from top right corner. And at beginning was also the choice for my cnc. I will write some clarification in the wiki with a picture.

**Comment by vlachoudis** [comment]
@Scott216 could you please confirm that by zeroing the WCS G55-G59 the workarea goes to the right place. If not then there is a bug somewhere :) which I need to find out.

**Comment by Scott216** [comment]
It will have to wait until next week.

**Comment by Scott216** [comment]
I just did a little test with the work area.  I use G56 for my work coordinates and loaded in a gcode file.  The work area is way too big, about 60 x 60 inches.  In the CNC section of the ini file i have about 11 x 13 inches.  The work area is oriented properly.  I'm using v 0.4.5
![bcnc worarea screenshot 2](https://cloud.githubusercontent.com/assets/819693/7825066/b541f5ac-03d6-11e5-8ef9-e47f1fd5c570.JPG)

**Comment by vlachoudis** [comment]
@Scott216 I forgot the correction of the workarea that @effer made. It should be corrected now

**Comment by Scott216** [comment]
WorkArea seems okay now.  It's the right size and position

**Comment by vlachoudis** [comment]
Perfect :)
