### ISSUE TITLE
Clear error in status bar

### ISSUE THREAD

**Issue by Scott216** [vlachoudis/bCNC#43]
Is there a way to clear the status bar?  It seems once I get an error, it stays there, even if the error isn't relevant anymore and I'm going other things.

**Comment by 1bigpig** [comment]
@Scott216 I just press the "Unlock" button and the error reporter goes back to "Idle".  IF it is a more serious error, "Reset" will do it.

Bruce

**Comment by Scott216** [comment]
I think it would be better if the status bar cleared on it's own once the error doesn't apply

**Comment by vlachoudis** [comment]
@Scott216 The status bar is refreshed periodically and reflects the grbl status by sending a ? about 5 times a second to grbl to report the status. However if grbl reports an error or alarm then bCNC blocks all subsequent submissions until a Reset or Unlock is pressed as @1bigpig mentioned.

**Comment by vlachoudis** [comment]
Again on the new interface <left-mouse-button> click on the status bar clears the error message.
