### ISSUE TITLE
Cannot access C:\ folder

### ISSUE THREAD

**Issue by acaballero6270** [vlachoudis/bCNC#433]
When trying to open a file that is located in folder C:\home. When I click "C" in the open file dialog it jumps to the root folder of bCNC instead of C:\ . Is that a bug? or am I doing something wrong?
Running on Windows 7 with python 2.7.11.

**Comment by Effer** [comment]
Thanks @acaballero6270 to point it out.
I've found how to fix in windows but can't test in linux now.
If you want to modify the code by yourself have a look [here](https://github.com/vlachoudis/bCNC/pull/434/files).

**Comment by acaballero6270** [comment]
It worked. Congratulations!
