### ISSUE TITLE
Floating numbers in DRO

### ISSUE THREAD

**Issue by levis0** [vlachoudis/bCNC#436]
I found what is not very comfortably to readout wpos and mpos - sometimes it shows xx.xxx sometimes xx.xx. i made little change in ControlPage.py and now allways these values are shown in format xxx.xxx. For me it is more comfortable, maybie for somebody other will too.
        def padFloat(self, decimals, value):
                decimals = 3;
                if decimals>0:
                        return "%0.*f"%(decimals, value)
                else:
                        return value

**Comment by Effer** [comment]
Hi @levis0 
have a look at https://github.com/vlachoudis/bCNC/wiki/Customize%20DRO
There's already an option that should fit your needs, **DRO Zero Padding**:
![image](https://cloud.githubusercontent.com/assets/1007007/18776153/973fafa8-8167-11e6-920a-06ea0176de51.png)

You are not the only one who prefer a fixed decimal places

**Comment by levis0** [comment]
Thanks !
