### ISSUE TITLE
TCP/IP connection to grbl is possible to do ?

### ISSUE THREAD

**Issue by levis0** [vlachoudis/bCNC#443]
I wrote little program for ESP8266 to act as access point and listen to a specific port. After wireless connection to it with telnet i can control grbl. Connection is transparent. Can be added to bcnc option TCP/IP:PORT connection option, not only physical serial interface ? It eliminates 1 wired connection and i think will be much more stable.

**Comment by levis0** [comment]
Now i'm trying ESP-12 with firmware esp-link from jeelabs and virtual serial ports emulator from Eterlogic. Seems all is working.

**Comment by vlachoudis** [comment]
I've tried once something like this using the Linux socat command. I don't remember how, but if you search on the web you can find examples how to bind a virtual serial to a file or a TCP/IP address

**Comment by lalo-uy** [comment]
There are many options but this is ok

socat  pty,link=/dev/virtualcom0,raw  tcp:192.168.254.254:8080&

2016-09-29 17:43 GMT-03:00 Vasilis Vlachoudis <notifications@github.com>:
