### ISSUE TITLE
text color same as background color in GUI

### ISSUE THREAD

**Issue by Bodagous** [vlachoudis/bCNC#450]
Hello, I do not think this is an issue with bCNC directly however when I choose a different theme in Ubuntu mate and than run bCNC the text is no longer visible in the drop-down boxes.  To be more specific the text is visible it is just the same color as the background of the boxes...(white on white = not visible) I'm using themes for gtk-2.0 and have tried changing the text color of the theme but still bCNC text remains not visible.  I'm not experienced with python at all and just a few years with Linux so my knowledge is still not enough to go digging through src files to attempt to remedy this on my own.(I tried anyway with no success). any help or point in right direction is appreciated. 

![screenshot_bcnc_textissue](https://cloud.githubusercontent.com/assets/20256625/19027109/ffab62fe-88e1-11e6-917b-24e7bf833f1c.png)

**Comment by Effer** [comment]
I can't help you with this issue but I have to say that the black theme really looks cool!
