### ISSUE TITLE
HAPPY BIRTHDAY bCNC!!!

### ISSUE THREAD

**Issue by Effer** [vlachoudis/bCNC#454]
it's just passed 2 years from the initial commit 4fc071e1886f850f156133a82d885f581076a01a of bCNC. So I think it could be a nice opportunity to celebrate and say thanks @vlachoudis for his big gift to the community.  
It would be fun post here some works done with bCNC (even just run through it) and share our experience.  
Here are some of my tests:
- A wood job
![p1060733](https://cloud.githubusercontent.com/assets/1007007/19434552/6a18bc9c-9466-11e6-8523-c3140935c2b1.JPG)

- A lithophanie in corian 
![p1060737](https://cloud.githubusercontent.com/assets/1007007/19434556/724214b8-9466-11e6-891b-7ca0c0c004dd.JPG)

Happy milling to everyone!
--

**Comment by vlachoudis** [comment]
On the contrary, I have to thank you @effer, @chamnit and all the supporters, which with out all of you bCNC wouldnt be what it is now.
