### ISSUE TITLE
Connected does not change

### ISSUE THREAD

**Issue by atrueresistance** [vlachoudis/bCNC#456]
It seems there is an issue with the latest master. I connect and the menu does not change, nor does the XYZ coordinates render. 

![image](https://cloud.githubusercontent.com/assets/7239809/19831235/8c402dec-9dca-11e6-9db1-c00ae8733c7e.png)

Clicking on it seems to work pop up this. 
![image](https://cloud.githubusercontent.com/assets/7239809/19831244/a80de262-9dca-11e6-8814-244ae93d9688.png)

Now even though this renders incorrectly, I am able to set my WCS and run files.

**Comment by vlachoudis** [comment]
Could you check on the "File" as well the "Terminal" tab if it detected as Grbl V1 or GrblV0.9

**Comment by atrueresistance** [comment]
I'm running `CarbideMotion 0.9g` as of current.

**Comment by auhopu** [comment]
I had a similar issue after the last pull. The status showed: "Not connected".

I could pass commands to my controller (e.g. home, jogging), the controller would execute the commands,  but there was no response back in bCNC. The DRO was empty and the spindle location was not shown on the diagram.

My GRBL is 1.0c and my File/Serial/Controller was set at "Grbl" (as opposed to "Grbl-V0").

With reverting to the previous state, the issue is corrected.

**Comment by vlachoudis** [comment]
Ok, I will downgrade my grbl and give it a test

**Comment by jeffmd** [comment]
I am using 0.9j GRBL and have had no problems with running bCNC git master.

**Comment by vlachoudis** [comment]
Ahh. Did CarbideMotion changed the init string from "Grbl 0.9g" to "CarbideMotion 0.9g"?

**Comment by chamnit** [comment]
@vlachoudis : I think they did a while back, if I remember right. I think they changed it back to `Grbl v0.9g` to address compatibility. Some users may have `CarbideMotion`.

**Comment by atrueresistance** [comment]
@chamnit I'm not sure the firmware was what shipped with the Rev 3 board from Carbide3d. It hasn't been flashed at all.

**Comment by vlachoudis** [comment]
@atrueresistance @auhopu could you check if with the new modification that should detect the string CarbideMotion it works?

**Comment by auhopu** [comment]
I just tried the latest pull, but still get the "Not connected" status and no DRO. Homing & jogging ok.

Also, my previous remark of seeing no response back in bCNC is partly true. $$, $, $G, $I work in terminal. However "?" just returns "ok", no state or current position (my $10=3 ). My GRBL version is 1.0c.20151109 .

Reverting to the previous version works normally.

**Comment by vlachoudis** [comment]
@auhopu Can you tell me what is the init string returned by Grbl after reset?

**Comment by auhopu** [comment]
This one:

Grbl 1.0c ['$' for help]

**Comment by atrueresistance** [comment]
@vlachoudis Lastest changes to sender.py solve my problem. Numbers and connected status are back for my machine.
