### ISSUE TITLE
Editor Sets Z to 0

### ISSUE THREAD

**Issue by Guenni75** [vlachoudis/bCNC#457]
The Buttons Conventional, Climb and Reverse turns all Z Commands from negativ to 0.

For example Reverse

Befor:
G0 X12.5 Y17 Z3
G1 **Z-1**
G1 Y-125
g0 z3

After:
g0 x12.5 y-125
g1 **z0** f300
g1 x12.5 y17 f970
g0 z3

**Comment by vlachoudis** [comment]
@Guenni75 this was discussed in the past. Unfortunatelly, the editor cannot change a cut that contains z motion, is too complicated or impossible in 3D paths. So it operates is as a 2D path at z=0 and then you have to apply a "Cut" tool to perform the cut to the specific height.
