### ISSUE TITLE
IndexError: list index out of range error when loading a DXF with rounded corners.

### ISSUE THREAD

**Issue by dalenunns** [vlachoudis/bCNC#458]
I get the following error when attempting to open a DXF file with rounded corners on the latest version of bCNC (the bug has been there a while though)

> Traceback (most recent call last):
  File "/home/chippy/Downloads/cnc/bCNC/Utils.py", line 391, in __call__
    return self.func(*args)
  File "./bCNC.py", line 1871, in loadDialog
    if filename: self.load(filename)
  File "./bCNC.py", line 1932, in load
    Sender.load(self,filename)
  File "/home/chippy/Downloads/cnc/bCNC/Sender.py", line 487, in load
    self.gcode.importDXF(filename)
  File "/home/chippy/Downloads/cnc/bCNC/CNC.py", line 2374, in importDXF
    path.fromDxfLayer(dxf, entities, units)
  File "/home/chippy/Downloads/cnc/bCNC/lib/bpath.py", line 1121, in fromDxfLayer
    b = bulge[i]
IndexError: list index out of range

I've uploaded an example DXF file here [NONAME_0.dxf.zip](https://github.com/vlachoudis/bCNC/files/601365/NONAME_0.dxf.zip)

I've had a look at the code and what appears to be happening is that the bulge array (list?) does not contain the same number of entries as the x & y co-ordinates. It appears to be caused by some of the co-ordinates in the PolyLine in the DXF file not having a 42 entry (what becomes the 'bulge' entry I think).

Would the fix be when loading a PolyLine from the file without a 42 entry simply adding a default entry to the bulge array with a value of 0? I'm unsure if this would break some other part of the system?

The DXF I've attached was created by DraftSight I took a square and then rounded the corners and exported as a DXF. 

BTW I love bCNC

**Comment by vlachoudis** [comment]
Thank you @dalenunns. Indeed there was a problem with the bulge reading from the LWPOLYLINE. Since it is an optional parameter, DraftSight was not setting it for the linear segments (only for the arcs) and bCNC was loosing the synchronization with the vertices. Now it is corrected.
