### ISSUE TITLE
Positioning problem of the cutter Run/Stop

### ISSUE THREAD

**Issue by Mr-Cozi** [vlachoudis/bCNC#459]
I have a problem positioning the cutter when I start machining, when I press RUN!

And when I stop the Gcode the tool resumes its position ...
Watch the red circle on the attached screenshot, the position of the tool is the same between the two images ...

What is the problem ???

![stop](https://cloud.githubusercontent.com/assets/14169617/20501407/1a20e5c6-b03a-11e6-8e35-d8f4fef31936.jpg)

![run](https://cloud.githubusercontent.com/assets/14169617/20501401/120218ba-b03a-11e6-8eda-61c28c4e04c2.jpg)

**Comment by Guenni75** [comment]
I have a similar Problem.
If i Stop a GCode, often the Z Value is changing.

**Comment by Mr-Cozi** [comment]
Do you find solution ?

If you watch my screenshot, only MPOS Z remains the same between a run and a stop.....

**Comment by vlachoudis** [comment]
@Mr-Cozi @Guenni75 I didn't understand the problem?

**Comment by Mr-Cozi** [comment]
My cutter stay at the same place but the software see différent position... 
See the red spot between the two screenshot!

**Comment by Mr-Cozi** [comment]
ok, i solve my problem...
I checked my g-code program and at the beginning i found the command G92 X... Y... Z...,

I deleted this command and know it's ok !

**Comment by vlachoudis** [comment]
Thanks for reporting @Mr-Cozi I am closing the issue
