### ISSUE TITLE
Object not shown in BCNC

### ISSUE THREAD

**Issue by danst0** [vlachoudis/bCNC#465]
Hi,

I just stumbled across an issue where stuff in the GCODE file is not shown in the BCNC interface.

Please have a look at the result and the pictures. The part of the Dino head is missing in the interface, it is however cut.

I also attached the DXF and Code.

Daniel

![bildschirmfoto 2016-12-09 um 13 33 39](https://cloud.githubusercontent.com/assets/1544506/21076193/ad179498-bf25-11e6-9ed8-27fd19595d60.png)
![bildschirmfoto 2016-12-09 um 13 34 08](https://cloud.githubusercontent.com/assets/1544506/21076194/ad19437e-bf25-11e6-8b16-0d09fd992afc.png)
[Archiv.zip](https://github.com/vlachoudis/bCNC/files/644055/Archiv.zip)

**Comment by Effer** [comment]
Hi @danst0 ,
please check if increasing the timeout rendering time, the issue persist.
This time out is set with the small combobox in the top right corner of the canvas. In your screenshoot is set to 5 (seconds).

**Comment by vlachoudis** [comment]
Any news on that?

**Comment by danst0** [comment]
Sorry for the delay. Increasing the value mitigated the problem. However it's not really obvious...🤖

**Comment by vlachoudis** [comment]
Python is not the fastest for drawing, gcode can be really large, and tkinter can only draw from the main thread. So we had to find a balance between what to show and when to unlock the interface.

**Comment by danst0** [comment]
Limit rendering makes total sense then!
Couldn't there be a window popping up, asking for permission to continue/warn that some items might not be displayed?

Daniel

**Comment by vlachoudis** [comment]
@danst0 That could be an option. But it has to be smart and shown only the first time for each file otherwise it will be annoying on every redraw.

**Comment by poesel** [comment]
I'd like to second that motion. I just came here to report it as a bug. Some notification would be nice.

**Comment by vlachoudis** [comment]
@poesel there is a notification on the status bar, most probably nobody pays attention since is not a popup :(

**Comment by Effer** [comment]
What about change the color label in the Toolbar?
(this one)
![image](https://cloud.githubusercontent.com/assets/1007007/22121077/b964ed5a-de82-11e6-943f-9082e0cf70a3.png)

Or add an **exclamation point** in the lower corner of the canvas.

**Comment by Fosforitofercho** [comment]
i had never seen that , because doesn’t have tag like time out, change this value to greater number fix the problem and render full Gcode :O  , thanks Effer . Each time I convince me that bCNC is the perfect software for GRBL
![image](https://cloud.githubusercontent.com/assets/24783375/22560492/3694db14-e94b-11e6-9198-e613c7d5a6dd.png)
