### ISSUE TITLE
grbl v1.1

### ISSUE THREAD

**Issue by poesel** [vlachoudis/bCNC#467]
Does bcnc support grbl 1.1?
I'm asking because laser mode and (real) jogging would be quite interesting for me.

**Comment by jeffmd** [comment]
Yes.  The feed overide and spindle rpm overide work well too.

**Comment by theblackraven** [comment]
I couldn't find out, if the new jogging mode is supported? Supports bcnc 0.98 the new jogging mode?

**Comment by vlachoudis** [comment]
@theblackraven not for the moment. I am going to test it soon
