### ISSUE TITLE
bCNC RPI3 Alamode CNC Shield

### ISSUE THREAD

**Issue by DenCNC** [vlachoudis/bCNC#474]
I am trying to get bCNC to run on  my Raspberry Pi 3 with Alamode and CNC Shield v3.  I am getting a few errors at startup that will not allow me to connect to the serial port.  I have installed python pyserial module several times and no success.  Here is the first error:

![2016-12-27-175140_1824x984_scrot](https://cloud.githubusercontent.com/assets/24798336/21507732/a47d5a52-cc40-11e6-9a40-e75cf0387371.png)

and then I get this error when I try to select the correct serial port:

![2016-12-27-181743_1824x984_scrot](https://cloud.githubusercontent.com/assets/24798336/21507750/bd08f8c4-cc40-11e6-8fcf-4d0d10b3955b.png)

I have tried everything that I can think of.  I seem so close that I hate to give up.  Any thoughts?

**Comment by DenCNC** [comment]
Never mind. Removed pyserial-3.2.1 and installed pyserial-2.7 and everything works perfect now. Thanks.

**Comment by vlachoudis** [comment]
@DenCNC thanks for letting us know. I will try to investigate why pyserial-3.2.1 is failing.

**Comment by vlachoudis** [comment]
@DenCNC I've tried today the pyserial-3.2.1 and it works ok on my pc
