### ISSUE TITLE
Autolevel Color doesnt work

### ISSUE THREAD

**Issue by Fosforitofercho** [vlachoudis/bCNC#475]
I installed the pillow package with    comand  "easy_install Pillow" from CMD ,

After i open the bCNC, i make autolevel, but i cant see the elevation as a colour map , only the numbers

Someone has been maked it worked on windows ??   or could give me help ? I know is not essential , but is more friendly than numbers 

Thank you so much 

I use bCNC 0.9.7

**Comment by vlachoudis** [comment]
Could you try to see if ImageTK is present, open python and type
```
from PIL import Image
from PIL import ImageTk
```

**Comment by Fosforitofercho** [comment]
Ok, i typed that and nothing message appeared , after i reopen bcn ,load a .nc code and .probe file, but again i only see numbers :S

**Comment by vlachoudis** [comment]
@Fosforitofercho Do you have numpy installed?

**Comment by Fosforitofercho** [comment]
Man my mistake, I didn't know the existence about   automatic installers of python libraries, i had installed Pillow using the console, after ,i found a windows installer of PIL (http://www.pythonware.com/products/pil/)  , click, run and Voilá!  the colors of autolevel works, thank you , escuse me the inconvenience . Yes I Now, sometimes I make trivial questions , but I am not an expert and I never has programmed on python .

**Comment by vlachoudis** [comment]
If you want, you can document your findings in the wiki page to help others
