### ISSUE TITLE
Shortcuts STOP, no reaction

### ISSUE THREAD

**Issue by Guenni75** [vlachoudis/bCNC#476]
The STOP Shortcut at F12, doesn't Stop the G-Code.
If i press F12, the Webbrowser opens the bCNC Page and nothing else happens.
In the shortcut list, the STOP command is really at F12.

**Comment by jeffmd** [comment]
Works fine for me.  When I make changes to the shortcuts, I have to restart bCNC in order for them to take effect.

**Comment by jeffmd** [comment]
There is a fix for this so bCNC does not have to be restarted after changing shortcuts.
see https://github.com/vlachoudis/bCNC/pull/477

**Comment by vlachoudis** [comment]
Thanks for the fix
