### ISSUE TITLE
access to Gcode Editor file

### ISSUE THREAD

**Issue by MohamadAlsadi** [vlachoudis/bCNC#481]
in bcnc . how I can reach to tap  gcode editor and edit code becouse I want add text box and buttons on this page. and connect this button with events

**Comment by vlachoudis** [comment]
Look the EditorPage.py

**Comment by MohamadAlsadi** [comment]
@vlachoudis  : PLZ I want to copy body G-code command without lines which contain header and footer and paste it many time. where I can find this code to edit it in EditorPage.py . and put my loop
