### ISSUE TITLE
External Keypad

### ISSUE THREAD

**Issue by Guenni75** [vlachoudis/bCNC#482]
Hi.
Is there a way to get the default steps (0.1, 1, 10) on an external Keypad?
I don`t use the external one, because every time i have to Switch between the Laptop and external Keypad to Change the Steps.
It makes more sense if a can do this with the external one as well.

**Comment by poesel** [comment]
You can change the steps on an external keypad with + and -

**Comment by vlachoudis** [comment]
@Guenni75  Which keys you would like to set the default steps?

**Comment by Guenni75** [comment]
I tried it now a few weeks and its ok!
