### ISSUE TITLE
WHY DEL G04  Gcode apear route?

### ISSUE THREAD

**Issue by a-sheng** [vlachoudis/bCNC#484]
![1](https://cloud.githubusercontent.com/assets/5866208/21773352/a63cf648-d6c9-11e6-9aba-75bce6a0256c.PNG)

![2](https://cloud.githubusercontent.com/assets/5866208/21773351/a63ca9cc-d6c9-11e6-8984-c34d9c6282f1.PNG)

GCODE [outline.zip](https://github.com/vlachoudis/bCNC/files/693977/outline.zip)

**Comment by vlachoudis** [comment]
Nice catch. bCNC remembers the last gcode execute and it reapplies in every line when drawing.
Now it is restricted only on the motion commands.
Please download the new master
