### ISSUE TITLE
situazione senza aiuto

### ISSUE THREAD

**Issue by miomaox** [vlachoudis/bCNC#486]
Bcnc funziona correttamente par  AUTOLEVELLING ; SCAN DEL PROBE ; SPOSTAMENTI DEL CONTROLLER ; praticamente tutto OK, ma quando vado a incidere il contour di un PCB, lo inizia correttamente ma verso la metà del lavoro si inceppa e non risponde più a nessun comando ad eccezione dello spegnimento. A volte funziona lo stop, allora porto a zero nuovamente il mandrino e inizio una nuova contour, tuttavia, anche in questo caso il lavoro non viene mai portato a termine.
Per il GCODE io uso questo programma online:           http://rapid-pcb.com/
Ovviamente ho bisogno di aiuto!
Grazie a chiunque possa prendere atto di questa mia richiesta.
1000 Cordialità
miomaox

**Comment by Effer** [comment]
Ciao @miomaox ,
il sito qui è in lingua Inglese e per correttezza degli altri utenti sarebbe meglio usare quella lingua per le richieste d'aiuto. Inoltre continuare ad aprire e chiudere il caso non è molto utile, a chi è registrato arriva una mail per ogni caso aperto o chiuso :)
 
Per capire il tuo problema sarebbe utile che caricassi qui il Gcode che si blocca. E' sufficiente comprimerlo in zip e allegarlo.
Se possibile scriviamo in inglese.
