### ISSUE TITLE
English translation

### ISSUE THREAD

**Issue by miomaox** [vlachoudis/bCNC#488]
Bcnc work correctly for AUTOLEVELLING; SCAN THE PROBE; MOVING THE CONTROLLER; virtually all OK, but when I go to affect the contour of a PCB, it starts correctly, but towards the middle of the work is jammed and not responding to any commands except shutdown. Sometimes it works the stop, then the port to zero again the mandrel and start a new recording of the contour, however, also in this case the job is never completed. For Gcode I use this program online: http://rapid-pcb.com/ Obviously I need help! Thanks to anyone who can take note of my request. 
1000 Friendliness 
miomaox

**Comment by vlachoudis** [comment]
I am closing this, since it was a duplicate that resolved.
