### ISSUE TITLE
Overrides reset

### ISSUE THREAD

**Issue by Effer** [vlachoudis/bCNC#489]
In the latest version Override reset button has been substituted  by a ComboBox to select which override affect. To be clear, this:

![image](https://cloud.githubusercontent.com/assets/1007007/21865224/8ff0ef8e-d845-11e6-96cf-a55f62b4bb59.png)

Now to reset you have to Right Click or Double Click the slideBar. This seems not to work correctly in windows. Right click doesn't work at all. While double click has the little drawback that it catch also a single click (if you do it in the dark gray slide bar), and so the override go back to 99% or 101%, depends if you do it at right or left of the slider.
I know the space is precious but could we add a little reset button? Maybe by horizontal splitting the combo box and use the top part to insert a small button. ( The scroll bar is already quite double size other buttons..)

**Comment by vlachoudis** [comment]
Yes that could work.

**Comment by vlachoudis** [comment]
I've just added it, thanks
