### ISSUE TITLE
Tool change and Probe coordinates are not stored

### ISSUE THREAD

**Issue by ralfsteck** [vlachoudis/bCNC#492]
Hi,

is it a bug or a feature that the probe and tool change locations plus the probe distance are not persistent ober a new start of bCNC? I understand that these values don't change all the time so they could be stored somewhere.

**Comment by vlachoudis** [comment]
All these values should be stored on the ${HOME}/.bCNC file on exit. If not then there is some permission problem and bCNC cannot write to this file.
