### ISSUE TITLE
update 1.1e

### ISSUE THREAD

**Issue by robcop2000** [vlachoudis/bCNC#493]
I have tryed to update to GRBL 1.1e. 
My configuration is Arduino Uno- GAUPS-Stepper DRV 8825.
GRBL 1.1.e- bCNC 0.9.7 as controller
As soon as I have update the 0.9.6 bcnc doesn't connect to the arduino.
I have updated but I had to delete the ./bcnc configuration  becuse the controller doesn't open. Or better start opening but at a certain point it closes automatically.
If I try to modiicate the new one, but doesn't work.
Tahnks
Roberto

**Comment by robcop2000** [comment]
Another request is possible to download older version?

**Comment by vlachoudis** [comment]
I've just downloaded the new grbl 1.1e and it connects without any problem. Normally it should autodetect the grbl, but for certainty please set in the "File" tab the "Controller" to **"Grbl"**.
"Grbl-V0" is for V0.9 or older.

You could download either from github in tab "Releases" or you could clone the git repository and then checkout any of the older versions.

**Comment by Fosforitofercho** [comment]
+1 In my case works without problem with grbl 1.1e  , In conect menu ,  I select "Grbl", push conect  and works great

**Comment by vlachoudis** [comment]
I am closing the issue, @robcop2000 if you can be more precise on what is the problem we can reopen it
