### ISSUE TITLE
Request; Config Menu

### ISSUE THREAD

**Issue by robcop2000** [vlachoudis/bCNC#494]
Should be grate to have screen where to modify all the GRBL config in one time without to write every time $XX=Y.....

**Comment by jeffmd** [comment]
Try Tools->Controller in the menu:
![bcnccontrolsettings](https://cloud.githubusercontent.com/assets/20491679/21963025/a6b38612-db08-11e6-9725-68ff31e2db98.png)
After changing the values you need to click on the "Controller" big button at the top with the little gear to the left.  You may have to select that button twice, I do under linux.  A green progress bar will show on the bottom when grbl is being updated with the new settings.
