### ISSUE TITLE
Incomplete Gcode render image 

### ISSUE THREAD

**Issue by Fosforitofercho** [vlachoudis/bCNC#495]
Good afternoon 
When I load huge Gcodes , for example a relief for wood ,the code is shown incomplete ,  however it sends all the code correctly , for it i think that is only a problem of render ![image](https://cloud.githubusercontent.com/assets/24783375/21967407/bdcdb954-db5c-11e6-9d75-9a3c6f5e1571.png)

Doesnt affect the funtionality, but is easy think that gcode is bad . I lost entire day for that

**Comment by jeffmd** [comment]
Have a look at this : https://github.com/vlachoudis/bCNC/issues/465
