### ISSUE TITLE
The problem with the option to change the direction of feed.

### ISSUE THREAD

**Issue by Dimitry-Muzi** [vlachoudis/bCNC#501]
When I turn to the editor "to change the direction of flow," then change the feed rate (not the one that was in the file). For example: I had a feed rate of 300mm / min, and after application of function - 1200. This is a mistake somewhere or it can be set up?

**Comment by vlachoudis** [comment]
Unfortunately not. It is not easy to reverse the path and keep this information, even more difficult is to keep the z-motion also. So these path manipulations convert the block to a 2D path which loses all information on the passes depth, feed rates etc.
