### ISSUE TITLE
STEP [s]: CommandLine problem

### ISSUE THREAD

**Issue by PeterCNC** [vlachoudis/bCNC#503]
Hello

Thank you for the bCNC program.  I noticed a little problem with the STEP command. 
STEP 0.5 does not work (no error but no change in step either). 
I looked at the code in bCNC.py

#STEP [s]: set motion step size to s
   elif cmd == "STEP":
     try:
       self.setStep(float(line[1]))
     except:
       pass

and I think that maybe
  self.setStep(float(line[1]))
should be 
  self.control.setStep(float(line[1]))

Peter

**Comment by vlachoudis** [comment]
Thank you I've added your correction
