### ISSUE TITLE
Can't copy grbl settings

### ISSUE THREAD

**Issue by poesel** [vlachoudis/bCNC#504]
Under Linux I can't copy the grbl output in the terminal window. Which would be useful for backup. 
Or as an improvement allow an export to file right there.

**Comment by jeffmd** [comment]
I just left click in the terminal area to highlight the lines I want to copy, then do Ctrl-c to copy the selected text.  Then I open up my favourite text editor and do Ctrl-v to paste the selected text.  Works on my Raspberry Pi.    Using Ctrl-insert for copy and Shift-insert to paste also works.  Works the same on Fedora too.

**Comment by poesel** [comment]
Hmm, I tried again and now it works. But I also updated from 0.95 to 0.97.
Sorry - should have tested better. This issue can be closed.
