### ISSUE TITLE
Adjusting Scale for Higher DPI Screens

### ISSUE THREAD

**Issue by magveda** [vlachoudis/bCNC#505]
Is it possible to change the DPI settings for high resolution screen?

**Comment by vlachoudis** [comment]
From bCNC you can change the fonts in the Tab: Tools -> Fonts, but not the DPI.
Now in the font size if you set a negative number e.g. -12, tk creates the font to the exact pixel size,
with positive 12, it will use the DPI of your screen.

**Comment by Effer** [comment]
Doubling icon size on load may also help. 
You can try by modify the method **loadIcons()**  in the file Utilis.py 

 ```python
def loadIcons():
	global icons
	icons = {}
	for img in glob.glob("%s%sicons%s*.gif"%(prgpath,os.sep,os.sep)):
		name,ext = os.path.splitext(os.path.basename(img))
		try:
			icons[name] = PhotoImage(file=img)
			icons[name] = icons[name].zoom(2, 2) #<--  Double size Icon
		except TclError:
			pass

**Comment by magveda** [comment]
Thanks! Will try these suggestions!

**Comment by vlachoudis** [comment]
@Effer it should be added as a user preference the zooming of icons

**Comment by Effer** [comment]
Ok will do.

**Comment by vlachoudis** [comment]
Thanks to @Effer it is now an option in the preferences. #506

**Comment by magveda** [comment]
You are great!

**Comment by garyemiller** [comment]
Help!  Where is that config option?  I can't find it.

Here is a screen shot, so you see how hard it is to read:

![screen](https://github.com/vlachoudis/bCNC/assets/1270340/df115e5c-1ceb-4146-8048-fdef5238e6f1)
