### ISSUE TITLE
Implementation of new GRBL Jogging Feature ? 

### ISSUE THREAD

**Issue by tmie** [vlachoudis/bCNC#510]
Any plans to implement the Jogging with GRBL 1.1 '$J=' command?
Seems interesting:
[Grbl v1.1 Jogging](https://github.com/gnea/grbl/wiki/Grbl-v1.1-Jogging)

**Comment by Effer** [comment]
I don't remember where but @vlachoudis said is going to implement it soon.
Briefly reading the doc it seem not so straightforward. Lot of test and debugging ahead I suppose.

**Comment by tmie** [comment]
Ok, I will be patient.
Thanks for the answer :-)

**Comment by hdo** [comment]
Any updates on this yet? Up to now the new jogging feature has not been implemented yet :-(

**Comment by PCSDIAS** [comment]
With the patch shown on August 8 I have got this functional cellphone bCNC GUI.
![pendant_gui](https://user-images.githubusercontent.com/27500167/46952174-7ef19700-d060-11e8-82fc-ad6b57140d26.png)

**Comment by PCSDIAS** [comment]
Hi all.
I'm sorry to tell that I misplaced the last comment.

The correct should be on "Jogging bCNC with a cell phone #930"
