### ISSUE TITLE
Question Nextion 

### ISSUE THREAD

**Issue by Hamewoker** [vlachoudis/bCNC#514]
Hello to the developers.
It would be possible as in this Prg
Https://www.mikrocontroller.net/topic/345380?page=2#4844529
Adding a Nextion display to control?
Since I can not program just one please to you.
Best greetings from Germany
Sven

**Comment by Effer** [comment]
Hi @Hamewoker , 
for sure it could be done. The product seems interesting.

**Comment by Hamewoker** [comment]
Yes this is it, currently use it itself, so you do not need a JogPad, and can change it any way,
I would appreciate it if it klabt.
Best regards Sven
from Germany

**Comment by Harvie** [comment]
I guess this is more in scope of GRBL
