### ISSUE TITLE
bCNC freezing problem with grbl fixed

### ISSUE THREAD

**Issue by fheflin** [vlachoudis/bCNC#516]
Using bCNC my jobs were stalling after a few steps in. It turned out that grbl was choking on the M7 code Fusion 360 was generating. No M7 No more problems. 
Hope that helps someone. I had set the configuration to ignore the Tool Change code and was getting a little cranked when that didn't fix it. It was the M7 still left int the Fusion CAM Code.

**Comment by vlachoudis** [comment]
You can set bCNC to ignore the M7 command.
You have to create a section [Error] in your .bCNC file
and set the commands to ignore like
[Error]
M7 = 1

0 = Stop execution
1 = Skip
