### ISSUE TITLE
Rendering failed

### ISSUE THREAD

**Issue by ralfsteck** [vlachoudis/bCNC#521]
Hi,

I did some pretty large milling jobs recently and I love my combination if Raspberry Pi (2), Protoneer board and bCNC. But I notice a render failure every time I start a larger job. The display stops drawing lines at a certain point. Do I have to increase the RAM amount of the Pi or is that an permanent issue of the poor performance of the Pi.

Cheers, Ralf

**Comment by jeffmd** [comment]
Have a read of this: #465

**Comment by ralfsteck** [comment]
Not until now, sorry. That did the trick.
