### ISSUE TITLE
Zoom alignement camera image

### ISSUE THREAD

**Issue by tmie** [vlachoudis/bCNC#522]
Hello again,
here's my next problem: the viewing angle is too wide.
When I mount the camera at the desired height of  approx. 5cm I get a pretty small picture (the objects on the picture are small, not the image itsself).
Is there a way to increase the zoom level for camera adjustment, with the current setting I am not sure if I am really hitting the center of my reference hole. 
The picture is perfectly sharp, so it should be possible to increase the magnification without loosing details.
Best regards
Tom

**Comment by vlachoudis** [comment]
Did you try to zoom in with your mouse?
Depending on the location of the camera selected
Gantry: should try to overlap the image at the correct location of the gantry on canvas with the proper dimensions, if the "Camera" parameters are correctly set. Zooming in or out it will always try to reproduce the correct dimension
All other locations: If you zoom too much out it will stay with zoom level 1 if you zoom in it will follow the zoom of the canvas
