### ISSUE TITLE
Error executing drilling G-code program 

### ISSUE THREAD

**Issue by shefus** [vlachoudis/bCNC#531]
This makes a hole and stops when the drilling program. Tried different options G-code with two computers - Windows and Linux. The only problem in drilling, engraving and milling - everything is OK. Other controllers (gbrl controller) to execute G-code is fine.
bCNC no error.  Status bar from the beginning to the end of the performance: current 0 [28]
Python in Windows gives an error:
![bcnc](https://cloud.githubusercontent.com/assets/17686658/23578025/75cb4d88-00ff-11e7-9c8c-4a1144ad9aba.JPG)

## **Example G-code:**
T1M6
G0Z2.000
G0X0.000Y0.000S15000M3
G0X15.946Y39.870Z2.000
G0
G1Z-2.000F120.0
G0Z2.000
G0X22.408Y41.408
G0
G1Z-2.000F120.0
G0Z2.000
G0X25.792Y35.870
G0
G1Z-2.000F120.0
G0Z2.000
G0X29.946Y41.408
G0
G1Z-2.000F120.0
G0Z2.000
G0X36.561Y39.870
G0
G1Z-2.000F120.0
G0Z2.000
G0X0.000Y0.000
G0Z2.000
G0X0Y0
M30

In this case some time ago, it was all excellent. What could be the problem?

**Comment by vlachoudis** [comment]
It has nothing to do with the drill command. It simply means that the serial communication died for some reason. My guess is a hardware problem, noise?
