### ISSUE TITLE
How many axis are supported?

### ISSUE THREAD

**Issue by killpop** [vlachoudis/bCNC#532]
First off, I love bCNC, I have been using it now for a while and it has always been great. Thank you guys for all of your hard work. I have used a lot of other GUIs and nothing comes close to this one.I have been trying to bCNC to work with the 4 and 6 axis build of grbl with no luck. Is there some kind of setting that I need to enable? This is kinda bumming me out, I just spend a whole lot of time getting the 4th axis to work in grbl on a mega/ramps 1.4 now only to be stopped by a lack of gui support. How would we go about getting more axis?

**Comment by vlachoudis** [comment]
For the moment there is no additional axis support. There was one port to accept a 4th axis (extruder).
