### ISSUE TITLE
Check Gcode is problem

### ISSUE THREAD

**Issue by quangvi** [vlachoudis/bCNC#537]
Hi admin ,When I use button $C [Check Gcode] and press botton Start . File Gcode start check error and load to 99% , after, problem is happen,, end line is ok but Check not complete, bCNC is lock , only button Stop or Exit I press ok, i try open another file ,but  problem is same  , this is mistake my? . I use Grbl ,thank you

**Comment by vlachoudis** [comment]
It could be that there is some error in the counting. I will check

**Comment by quangvi** [comment]
thank @vlachoudis

**Comment by vlachoudis** [comment]
Thanks for reporting. Now it is fixed.
