### ISSUE TITLE
Zeroing using G54

### ISSUE THREAD

**Issue by TheArcher1980** [vlachoudis/bCNC#540]
When zeroing the axes, bcnc will use G10 L20, writing the position to the AtMega's ROM.
This will over time damage the ROM. The AtMega's ROM is only capable of around 100.000 write cycles.

**Comment by chamnit** [comment]
That's what you want to do and save your coordinate data. If you write to eeprom 10 times a day, everyday, it'll take 27 years to wear that particular section of eeprom out. It's also very cheap to replace.

**Comment by vlachoudis** [comment]
@chamnit is right. I cannot see any issue in destroying the eeprom.
