### ISSUE TITLE
Autoleveling and laser 

### ISSUE THREAD

**Issue by leogala** [vlachoudis/bCNC#543]
Hi,
I'm using GRBL 1.1 in laser mode with a laser cutter.  When I run a gcode after applied autoleveling in bCNC, happens that after a movement with laser OFF (a G0 I guess) , z axis is moved a little bit (apparently in relation with autoleveling) and laser is turned on, then a G1 is performed correctly with laser on. The problem is such z movement with laser on that ruin the cut.
This does not happen without autoleveling do I deduced that was related to autoleveling. Any idea to solve the problem ? Am I doing something wrong ?
Thanks in advance

Leo

**Comment by vlachoudis** [comment]
There was a bug #483 spotted by @dguerizec. Could you try the newest master if it exhibits the same behavior
