### ISSUE TITLE
DRO (both machine and work position) and status aren't updating

### ISSUE THREAD

**Issue by FishyD** [vlachoudis/bCNC#544]
Windows 10, X-carve w/ X-Controller, GRBL 1.03C (X-Carve fork). 

bCNC connects the machine (COM3) but the status and both coordinates aren't correctly updating. I can unlock the machine (even though the lock icon always shows unlocked) with $X or home but as I jog the machine the coordinates aren't moving, they always read 0,0,0 or sometimes all 6 are blank. I have attached a screen shot, as you can I have a connection but the status says "not connected" and there are not machine or work coordinates.  Sometimes new errors will populate; I forced a homing fail, but still no correct DRO readout. 

![error 2 bcnc](https://cloud.githubusercontent.com/assets/26522740/24081299/904571fa-0c87-11e7-90ef-8756a9849644.JPG)
![error bcnc](https://cloud.githubusercontent.com/assets/26522740/24081301/965387b2-0c87-11e7-9a13-4273938a9912.JPG)

**Comment by digicnc** [comment]
I have the same problem, my GRBL Version 1.1e, with the terminal I can check the connection, but the DRO Section showing "Not connected"

**Comment by FishyD** [comment]
Exactly! I can check the connection, pull the $$ and jog but the DRO shows no connection and doesn't update the coordinates.

**Comment by vlachoudis** [comment]
Can you send a copy of the terminal

**Comment by digicnc** [comment]
Here a copy of the terminal:






![2017-03-22](https://cloud.githubusercontent.com/assets/15715099/24191351/1f132ec0-0f1e-11e7-9ed2-44756d83d732.png)

If you want that I run a specific command, just let me know. 

Thanks

**Comment by vlachoudis** [comment]
Can you set $10=1

**Comment by digicnc** [comment]
Ok, I tried, this, now it is working alright ....
Thanks a lot

**Comment by vlachoudis** [comment]
You are welcome

**Comment by FishyD** [comment]
Unfortunately even with $10=1 (it was at $10=2) I am still not getting position reporting on the DRO. See my terminal below. 
![error 2](https://cloud.githubusercontent.com/assets/26522740/24307511/d866942a-109a-11e7-83ff-f93f7482b4ea.JPG)
![error](https://cloud.githubusercontent.com/assets/26522740/24307512/d86a4ac0-109a-11e7-889a-4e22f430d815.JPG)
