### ISSUE TITLE
Fusion 360 generated code stops just after start, but runs ok in universal gcode sender

### ISSUE THREAD

**Issue by stasjminister** [vlachoudis/bCNC#548]
As mentioned I am having issues with 2 files generated in fusion360. But both run ok when sending with universal gcode sender 0.9. 

Right after pressing start the machine moves a bit, then suddely halts. With no error codes that I can see..

Any suggestions?

I am running bcnc 1.0.9. and grbl 1.1

GRBL code in txt-file. (had to change extension from.nc
[dobbel sirkel4mm flat.txt](https://github.com/vlachoudis/bCNC/files/869336/dobbel.sirkel4mm.flat.txt)
)

**Comment by atrueresistance** [comment]
Generate the code with no coolant and it will run fine

**Comment by stasjminister** [comment]
Tanks! Will try asap. 3.14 thumbs up for extremely quick reply!

**Comment by stasjminister** [comment]
I also had to change the post processor in fusion360 to the carbide3d one. 
With the default encoder I got lots of error 33 and error 36 as well when I finally got it run, after 5-10 presses on start. So I guess the default encoder left a whole lot of gravel for bcnc to chew trough.

Thanks for your help. Much appreciated. If your ever in Oslo, Norway, I owe you a beer :)
