### ISSUE TITLE
bCNC spindle override ERROR?

### ISSUE THREAD

**Issue by viewsat** [vlachoudis/bCNC#550]
When sending gcode, such as changing the spindle% PWM output will have an incorrect action.
Use the oscilloscope to see PWM output.
When <100 will automatically continue to change to a minimum, when> 100 will automatically continue to change to the maximum.

See my youtube video :
https://youtu.be/5Dt0TNT3uTE

**Comment by BlueOrangeLive** [comment]
@ viewsat : Maybe look in bCBC Settings Tools / Config and Tools / Controller spindle speed adjust.
Greetings Jürgen

**Comment by Heszu** [comment]
@BlueOrangeLive : ??? and ???, How stop the drifting ???

**Comment by vlachoudis** [comment]
@viewsat I think I found the problem. Could you check now

**Comment by viewsat** [comment]
@vlachoudis I tested the spindle override function is no problem, thank you very much!

**Comment by vlachoudis** [comment]
Thanks for confirming
