### ISSUE TITLE
Am I losing steps on the Z axis?

### ISSUE THREAD

**Issue by Thorgrlm** [vlachoudis/bCNC#556]
Hi, I have a doubt, I checked that doing several times the autolevel in the same pcp gives me different values at the same test points.
Is that normal or my machine lost steps?, it's few but They are microns of difference.

Thanks fou your help

**Comment by jeffmd** [comment]
Maybe or could be dirty pcb or pcb is not securely mounted.

**Comment by Thorgrlm** [comment]
I will format the pc, the pcb is well secured
I already comment anything

**Comment by Thorgrlm** [comment]
Hi, I have formatted the PC, and I still have the same problems, I don't know if it will be normal, I upload a photos
[img]http://i.imgur.com/anxcxwG.png[/img]
[img]http://i.imgur.com/JuGRRix.png[/img]

**Comment by vlachoudis** [comment]
Could it be that you are using a high feed rate during the probing. Go very slow to check.

**Comment by Thorgrlm** [comment]
I have the speed by default.
[img]http://i.imgur.com/IOJIPce.png[/img]

**Comment by Harvie** [comment]
Sounds like mechanical or deceleration problem to me. Please reopen if there's problem in bCNC.
