### ISSUE TITLE
Create file exe from python

### ISSUE THREAD

**Issue by Terminator88** [vlachoudis/bCNC#559]
Can you give me file setup.py. I try many and many time, but file bCNC.exe still not run. I don't undertand why reason. I run on window 10, python 2.7.13, py2exe-0.6.9.win32-py2.7, pyserial-2.7.win32-py2.7,
 pypiwin32-219.win32-py2.7, PIL-1.1.7.win32-py2.7. I run project ok with Pycharm.
File setup.py of me:

#!/usr/bin/python
from distutils.core import setup
import py2exe
setup(windows = [{"script": "bCNC.py"}])
or:
from distutils.core import setup
import py2exe
setup(console=['bCNC.py'])
------------------------------------------------------------
It appear some error like below when I click file exe:
1.
Traceback (most recent call last):
  File "bCNC.py", line 41, in <module>
NameError: name '__file__' is not defined
2.
Traceback (most recent call last):
  File "bCNC.py", line 2563, in <module>
  File "bCNC.py", line 112, in __init__
  File "Sender.pyc", line 221, in __init__
  File "CNC.pyc", line 910, in loadConfig
  File "ConfigParser.pyc", line 618, in get
ConfigParser.NoOptionError: No option 'startup' in section: 'CNC'
3.
Runtime Error!
Program: C:\User\ABC\Desktop\...
R6034
An application has made an attempt to load the C runtime library incorrectly.
Please contact the application's support team for morw information
-------
The application was unable to start correctly (0x0000142). Click OK to close the application
4.
C:\User\ABC\Desktop\...\....\dist\bCNC.exe
The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.
5. 
The program just appear then disappear in a jiffy.
6. I use cx-Freeze:
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
    __import__(name + "__init__")
  File "C:\Python27\lib\site-packages\cx_Freeze\initscripts\Console.py", line 20, in <module>
    importer = zipimport.zipimporter(os.path.dirname(os.__file__))
zipimport.ZipImportError: not a Zip file
-------------------------------------------------------------- 
Any one help me. I appriciate for you'r help.

**Comment by Effer** [comment]
Hi @Terminator88 
have a look here #437
