### ISSUE TITLE
Serial LED(tx/rx) keep blinking ,is that normal?

### ISSUE THREAD

**Issue by Perzcana** [vlachoudis/bCNC#564]
As captioned, when i open serial port , connect to board (arduino uno with grbl 0.9), the tx\rx pilot light on board will started blink synchronously, but seems that there was no data been sent. The other tools like grbl controller do not have this issue. Sadly :( , cause of my poor english, i couldn't find the description in wiki. So, is that normal ?

**Comment by Effer** [comment]
Hi @Perzcana , 
in short it's normal and not an issue.
It's the way bCNC update grbl status. It keep pooling grbl in background. Probably others interface use a different approach.
