### ISSUE TITLE
Delete reference position

### ISSUE THREAD

**Issue by danielpcb3d** [vlachoudis/bCNC#566]
I'm a bcnc newbie and i'm very happy with it but i have a little problem, which i didn't get fixed. I've built a pcb milling maschine based on a grbl flashed board which i control with bcnc. For every milling prozess i use the autolevel function. After that i press "Start" and the milling head moved first to the false direction, comes back to his previous position and start milling. What i'm doing wrong?

**Comment by vlachoudis** [comment]
there should be something in your gcode like a g28 to go to a reference position first

**Comment by danielpcb3d** [comment]
Thanks a lot for your reply. How can delete this gcode or can i configure in bcnc that the milling maschine have to start at the given position?

**Comment by danielpcb3d** [comment]
Has nobody an idea how to delete the reference position?

**Comment by vlachoudis** [comment]
From what I know, you cannot delete, but at least you can define to something meaningful.
Or you have to modify your g-code generator not to use this command
