### ISSUE TITLE
Pause and Start problem

### ISSUE THREAD

**Issue by quangvi** [vlachoudis/bCNC#567]
Hi admin @vlachoudis   , i 'm using GRBL v1.1 , if I press connect to Grbl, bCNC display "Conneted" 
if i press Start Program and press Pause late, button Start not execute again
if I press Reset on bCNC first ,bCNC display "Idle",  button Start and Pause is normal , something wrong ?

**Comment by user012flo** [comment]
Try to press Pause again, to continue your program.

**Comment by quangvi** [comment]
no no, when the bCNC display " Connected" , @user012flo   I Try to press Pause again, but its nothing execute , i resolve it's now , in source bCNC , when bCNC connect "COMxx", it's send " Reset" the bCNC go to "Idle" before Start program

**Comment by Harvie** [comment]
Same problem. Once i pause, i can't unpause.

**Comment by neilgill** [comment]
I tried double clicking Pause, then double clicking Pause again, wait between each double click, after two or three goes, my machine resumed. It seemed to work consistently, several double clicks gets it going.

**Comment by Harvie** [comment]
Seems to be fixed

**Comment by luisca95** [comment]
la primera vez que le di un solo click no me funciono lo que hice despues fue solo darle doble click al boton pausa y funciono volvio a correr el gcode

**Comment by Harvie** [comment]
No tengo dinero. No no no no.
Try upgrading to latest bCNC.
