### ISSUE TITLE
Tool Tip not saved

### ISSUE THREAD

**Issue by Scott216** [vlachoudis/bCNC#57]
I customized one of the user buttons, but it's not saving the tool tip info.  i'm using bCNC v 0.4.5

**Comment by Effer** [comment]
Strange, they all work for me. @Scott216 do you edit the file manually or using the context menu by right click on Button. Can you post the [Buttons] section in the config file of your user folder?

**Comment by Scott216** [comment]
I used the context menu.  I can post the [Buttons] section later when I'm back in my shop .  BTW, I'm running Windows 7.

**Comment by vlachoudis** [comment]
@Scott216 the tooltip was saved but not restored when the dialog was opening. Now it should be back

**Comment by Scott216** [comment]
Thanks, it works now.
