### ISSUE TITLE
Proposal: Add jog commands to bottom of Auto Level panel

### ISSUE THREAD

**Issue by woodworkerbob** [vlachoudis/bCNC#577]
I use the Auto Level feature with wood projects. My SO3 probe switch is offset, X, Y, and Z,  from the router bit.  During the Auto level process the origin must be set to the probe switch, then back to the cutting bit.

It would be handy to have jog commands under the auto level inputs, preventing the jumping back and forth to the control tab.

Not a biggie. Just a minor improvement.

Thanks,
Bob

**Comment by Effer** [comment]
Hi @woodworkerbob ,
have a look here https://github.com/vlachoudis/bCNC/wiki/Customize-Menu
 to customize the layout. Hope this can help.
