### ISSUE TITLE
Box generator: add option to make open boxes (like drawers)

### ISSUE THREAD

**Issue by Harvie** [vlachoudis/bCNC#588]
Please make it possible to generate open boxes with only 5 sides rather than 6. Without finger joints on top side. Eg. something like this:

![image](https://cloud.githubusercontent.com/assets/276504/26030263/29d9b8b6-384e-11e7-82dc-671f2b12516e.png)

**Comment by vlachoudis** [comment]
It could be an option for the future. For the moment you can export it as a finger box, save it as DXF, import it in any cad program like librecad, and delete the fingers from the top side. You can even delete the top side and the fingers from inside bCNC but it is a bit more cumbersome.

**Comment by Harvie** [comment]
Nice. I didn't realized i can do that. I really like how bCNC does not make difference between g-code and drawing. It makes it really usefull. Like swiss army knife of g-code.
