### ISSUE TITLE
bCNC+Midi2CNC spotted on TV!

### ISSUE THREAD

**Issue by CarlosGS** [vlachoudis/bCNC#593]
Not an issue - I just want to let you know of the (brief) appearance of bCNC + Midi2CNC last night on TV!
Our friend @LuisDiazUgena took his Cyclone PCB Factory to the show and demonstrated how music can be generated with stepper motors :-D

![screenshot from 2017-05-19 10-19-19](https://cloud.githubusercontent.com/assets/1636266/26240792/946b9a18-3c82-11e7-83b7-b6f99e54a130.png)

![screenshot from 2017-05-19 10-12-49](https://cloud.githubusercontent.com/assets/1636266/26239768/a1fd81b8-3c7e-11e7-8b39-b5f599f819bf.png)

You can see the full segment here: <http://www.atresplayer.com/television/programas/hormiguero/temporada-6/capitulo-130-jessica-chastain_2017051800547.html> (about minute 39 into the show)

Luis asked me for the best way to achieve stepper music and I told him about the Midi2CNC plugin. He required no further help :-)
Great job @vlachoudis @Effer @others making CNC so easy!!

**Comment by LuisDiazUgena** [comment]
Thanks for sharing that :) it's been nice to bring some open source technology on air!

**Comment by vlachoudis** [comment]
Cool! Thanks for sharing. To see the video it requires registering, would it be possible to extract only that portion from the video and upload it on youtube?

**Comment by Effer** [comment]
Awesome! Thanks @CarlosGS to point it out! TV in Spain seems lot more interesting than here in Italy :)

**Comment by CarlosGS** [comment]
Here you have the segment: https://youtu.be/t4Pr6p_o2Zo

Sorry I forgot of the player restrictions outside of spain :-)

El 19 may. 2017 8:25 p. m., "Filippo" <notifications@github.com> escribió:

Awesome! Thanks @CarlosGS <https://github.com/carlosgs> to point it out! TV
in Spain seems lot more interesting than here in Italy :)

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/vlachoudis/bCNC/issues/593#issuecomment-302776880>, or mute
the thread
