### ISSUE TITLE
G-Code problem; C-Code from software target

### ISSUE THREAD

**Issue by wrehj** [vlachoudis/bCNC#600]
Hello,

I construct my layout using the software target.

Now I have the problem that the G code is not processed.

The machining starts and breaks after about one centimeter of travel to the center point.

Nothing works anymore.

Zero trip and Autolevel previously run clean.

The sample file from the Youtube video runs without problem.

What do I have to consider? What am I doing wrong?

Attached my G-Code file as TXT.

[lichtbooster_wreh_kupfer.txt](https://github.com/vlachoudis/bCNC/files/1064199/lichtbooster_wreh_kupfer.txt)

**Comment by vlachoudis** [comment]
There is an line that grbl doesn't like "G64P0.05". However there as a bug in bCNC and the error flag was reset, so you couldn't see the error unless you clicked on the "Status button". Now it is corrected.
Anyway removing the G64 line everything works.
