### ISSUE TITLE
Can't left-click icon on taskbar

### ISSUE THREAD

**Issue by Terminator88** [vlachoudis/bCNC#601]
When I "open file" or "save file", then if i not yet choose file, I choose "show the desktop", I can't open application return. I click icon in the taskbar, but have not any response. Anyone can help me ?
![open file](https://user-images.githubusercontent.com/26424544/27001485-8254ce7e-4df5-11e7-82ea-a39e2b6e4bfb.PNG)
![can not open](https://user-images.githubusercontent.com/26424544/26999636-e76016d4-4dc8-11e7-83a3-8dc1508ea1f5.png)

**Comment by vlachoudis** [comment]
Maybe the File dialog window which has the focus remains open. try to close it first.
