### ISSUE TITLE
Incorrect feedrate in G8? canned routines and machine in imperial

### ISSUE THREAD

**Issue by Serbitor** [vlachoudis/bCNC#607]
When the machine is set to inches the feed rate for G8? commands is not output in the correct units.

```
G20
G81 R0.07874 Z-0.06693 F0.39370 X2.12205 Y0.70079
```

results in bCNC sending 

```
g0 x2.12205 y0.70079
g1 z-0.06693 f9.999
```

to grbl

PR #606 should fix this

**Comment by vlachoudis** [comment]
Thanks!
