### ISSUE TITLE
Go to study!

### ISSUE THREAD

**Issue by ser007** [vlachoudis/bCNC#616]
Hi. bCNC is a great project. Thanks for the work!

I'm looking forward to studying it so I can learn how it works and one day I can collaborate.

I would like to know the best development tool (IDE) that is compatible with Python Tinker where I can handle the interface, add more buttons, etc.

Thank you

**Comment by vlachoudis** [comment]
You are welcome. I didn't find any developement UI for tkinter. I use vim

**Comment by Effer** [comment]
Hi @ser007 , 
just a couple of thoughts:
- The codebase is huge, and I mean HUGE. @vlachoudis wrote thousands of code lines and bCNC do a lots of things. So it's not easy to get the whole picture.
- Doc is poor but the code is well written (and quite self documented). You can learn a lot from a project like this.
- Believe it or not everything in the GUI is handwritten, so there's no tool to visually adjust icons,buttons,layout. Here the code rules.
- As IDE I've used PyScripter, PyCharm and then switch to VS2015 with python plugin (Python Development Tools). All works well, supports breakpoints and watch variables out of the box. For some changes and plugins I've simply use Notepad++.  With python you can do.
- I've found the [plugins ](https://github.com/vlachoudis/bCNC/wiki/How-to-create-a-plugin)sandbox an easy point from where to start. There you can create some specific functionality without wondering too much about the rest.

Hope this could help.

**Comment by ser007** [comment]
Hello guys,

@Effer, I'll check the tools you're suggesting.

@vlachoudis, @Effer thank you
