### ISSUE TITLE
How do I use the flatten tool?

### ISSUE THREAD

**Issue by rhfinch** [vlachoudis/bCNC#617]
I have a fealing I'm missing something, but I can't figure out how to use tthe flatten and other tools.

I Enter stock details, material, and end mill the click flatten. I fill in in the flatten panel, then what do I do  to make it happen? Some documents refer to an Execute button but I don't see one. I tried cut and enter more data but nothing happens. What am I missing?

Any advice would be greatly appreciated.

**Comment by mandrav** [comment]
Just above the tool settings, there is the title of the tool, "Flatten" in this case, with a gear icon next to it. The title is actually a button: just press it to execute the plugin...

**Comment by rhfinch** [comment]
Thank you so much mandrav. It was driving me crazy!
