### ISSUE TITLE
Tools info: question

### ISSUE THREAD

**Issue by kees1948** [vlachoudis/bCNC#618]
Hello, I'm a recent user of this wonderful piece of software. After playing with it
for a while the following question came up, for which I could not find an answer:
Where in the bCNC window can I find information for the next (drill) tool to place?
bCNC goes in  HOLD:0 mode but I would like to find which (drill) tool I need to place next.

best regards, Kees

**Comment by vlachoudis** [comment]
The program should display the comment of any on the to change line. Now if there is no comment, maybe it should simply display the tool number
