### ISSUE TITLE
Trouble importing files to bcnc on Raspberry Pi 3

### ISSUE THREAD

**Issue by suiterec** [vlachoudis/bCNC#619]
Hi, I am trying to open .dxf files (exported from Solid Edge) into bcnc on my raspberry pi 3. When I try to open anything, nothing happens. There is loading text in the bottom left of the window with the correct file path, but no matter how long I leave it, nothing ever opens. What could be my problem? Thanks in advance!

**Comment by vlachoudis** [comment]
Could you upload one of those dxf files to test.

**Comment by suiterec** [comment]
.dxf flies are not supported by the file uploader on github so I have attached it here.

**Comment by suiterec** [comment]
Sure. Here is one I have had trouble with. 

[Profile1.zip](https://github.com/vlachoudis/bCNC/files/1143212/Profile1.zip)

**Comment by vlachoudis** [comment]
When I load your dxf I get the following image
![profile1](https://user-images.githubusercontent.com/3834594/28863420-24406dbe-7769-11e7-90a8-77bcc4ad85c3.png)
which is consistent with what I see in librecad
