### ISSUE TITLE
Control:

### ISSUE THREAD

**Issue by kees1948** [vlachoudis/bCNC#621]
When I do: File -> New and next Control->Start, the system moves to: 0, 0, 20 (X,Y,Z) in mm
or 0, 0, 508 in inch....... It will also fire the Laser at max power.
Why is that? I would expect it to go to 0, 0, 0..... Where can I change this preference?
Z 508 inch is far beyond the mechanical travel of my machine :-)

Why does the displayed values of Mpos and Wpos not change when the units setting is changed?

**Comment by vlachoudis** [comment]
In "Tools -> Config" you have the default Header and Footer code to be appended in your imported file. Please change to your preference.
