### ISSUE TITLE
Camera problems, fixed

### ISSUE THREAD

**Issue by Elvenblood** [vlachoudis/bCNC#623]
I had a problem with getting my camera to work. I'm on a laptop which has a camera, and now I added another. Couldn't get it to work at first, then I changed in Camera.py line 47 to:
self.idx     = Utils.getInt("Camera", "webcam")

So now it uses the settings from the ini-file. Don't know if that is the correct way of solving it, but it works.

**Comment by vlachoudis** [comment]
Very strange since the call in Pendant.py is Pendant.camera = Camera.Camera("webcam") which later translates to self.idx = Utils.getInt("Camera", "webcam")
