### ISSUE TITLE
not connectet

### ISSUE THREAD

**Issue by Baeckchen** [vlachoudis/bCNC#624]
Hello,
first of all, bcnc is a gread programm, thanks for all the work.

Today i update / upgrade my rasperry jessi and now bcnc prompt "not connectet" and the MPos and WPos displays are empty. But I can jog, homing etc. from bcnc and when I open the terminal Status and MPos are reportet.
Bcnc Version is 0.9.9
What can I do
Gruß aus Düsseldorf
Andreas

![bcnc fehler](https://user-images.githubusercontent.com/10011400/28720810-86f861b4-73ae-11e7-9174-5b0df1e72412.JPG)

**Comment by Effer** [comment]
Hi @Baeckchen,

do you set the correct firmware version to match your controller?

![image](https://user-images.githubusercontent.com/1007007/28727093-0c4754d2-73c4-11e7-81ab-f6fd1be0ac20.png)

**Comment by Baeckchen** [comment]
Hi @Effer,
I've nothing changed in bCNC and off course I've tested both GRBL versions.
At the End I've set up a new Jessy on another RPi and there are the same erros. I've never watched at the terminal screen are there only the MPos data and status or additonally the WPos data ?
Please check this for me.

**Comment by vlachoudis** [comment]
Can you show a screenshot of the terminal

**Comment by W-E** [comment]
There is a known issue with a linux kernel version and serial port. If you look in the terminal from which you started bCNC, you may see a message saying something like "device reports readiness to read but returned no data" or the like. This is related to the serial port driver in the Linux kernel. Googeling the exact message leads to solutions. Like https://askubuntu.com/questions/680473/ubuntu-14-04-usb-serial-port-device-reports-readiness-to-read-but-returned-n 
I had the same issue on an laptop running an not up-to-date Ubuntu. After a dist-upgrade ( which included a kernel upgrade) it works.
This may also be an issue on Raspian...

**Comment by Baeckchen** [comment]
Hello,
back from holidays I`ve made a screenshot from the terminal after a homing command from bcnc.
![grafik](https://user-images.githubusercontent.com/10011400/29215740-77bf349e-7eac-11e7-8a6c-c2643f5906f4.png)

**Comment by Baeckchen** [comment]
and here the release info 

pi@raspberrypi:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux

**Comment by vlachoudis** [comment]
It seems you have changed the report setting in grbl v0. and you don't show the WPos that it is needed by bCNC.

**Comment by Baeckchen** [comment]
I thing so, but I´ve made no changes in the grbl controller.
The only thing I´ve done is update and upgade the os and perhaps I´ve made changes to the grbl controller by pressing the <controller> button ?

![grafik](https://user-images.githubusercontent.com/10011400/29217288-917a7c72-7eb1-11e7-83ab-c07ab0c18ff4.png)

**Comment by vlachoudis** [comment]
Be careful the setup here is for Grbl V1 and not of V0.9.
Anyhow I would strongly recommend you upgrade your controller to V1.1 it has a lot of extra functionality that you could benefit of.

**Comment by Baeckchen** [comment]
I`m such a idiot, I´ve changd the settings <$10 Status report option> to 1 back to 3 everything worked fine.

Never change a running system :-) so I do not dare to upgrade my controller to V1.1

Thankes for all the help

Grüße aus Düsseldorf
Andreas

**Comment by vlachoudis** [comment]
On the contrary this upgrade you should do :)

**Comment by github051** [comment]
Hi Andreas, 
I'm also came across same issue. Then i saw u r above comment and i corrected $10=3
Now its working fine.
Thank you.
