### ISSUE TITLE
bCNC does not detect lost connection to grbl

### ISSUE THREAD

**Issue by W-E** [vlachoudis/bCNC#629]
bCNC does not detect if the controller is disconnected. Not even if you click e.g. the "move x" button after disconnecting the controller.
As bCNC seems to "talk" to the controller all the time ( likely to update the positions, you can see the LED's blink) it should be easy to detect a lost connection.
AFAIK bCNC should go to "stop" and throw a message if a disconnect is detected.

**Comment by vlachoudis** [comment]
Thanks, I've added this check right now.

**Comment by W-E** [comment]
Superb. Thanks again !
