### ISSUE TITLE
Home shortcut shouldn't be on by default

### ISSUE THREAD

**Issue by truhlikfredy** [vlachoudis/bCNC#634]
I know you meant it well, but in my case I use the home to edit numbers a lot and if the gantry is in such position which would damage the head/gears which is in my case very often then then HOME button is very scary.

Either remove these:

self.bind('<Home>',		self.home)
self.bind('<KP_Home>',	self.home)

Or allow them to be configured, but they shouldn't be on all the time by default.

**Comment by vlachoudis** [comment]
Indeed I agree. its done. both KP_Home and KP_End are removed.

**Comment by truhlikfredy** [comment]
I didn't had much problems with end, but it will be safer. What is actually the difference between Home and KP_HOME ? I meant to write <Home> in the first line and somehow only '' is there.

**Comment by vlachoudis** [comment]
KP_xxxx = keypad

**Comment by truhlikfredy** [comment]
Then probably the non-keypad should be removed as well?

**Comment by vlachoudis** [comment]
correct, done
