### ISSUE TITLE
Problems moving DXF-Imports

### ISSUE THREAD

**Issue by domstar** [vlachoudis/bCNC#639]
Hello,

first of all thanks for this great program. It works fine and I found just a small problem.
If I Import 2D data from a dxf file or g-code, it is not possible to move it i z-direction. Sometime this is very useful, esspecially while importing a "solid" and putting sth. to engrave on top of it.

If you need an example or sth. like that, please let me know it.

Best Regards
domstar

**Comment by vlachoudis** [comment]
All, editing operations are done in 2D in the X-Y plane. If you want to move it in Z you need to issue a cut operation and define the stock height and depth there, of course it wont work for 3D solids. Alternatively you can leave the Z as is and just adjust the Wpos on the top of your surface
