### ISSUE TITLE
No manual spindle control

### ISSUE THREAD

**Issue by adambrum** [vlachoudis/bCNC#640]
Im still learning on bcnc but i cant seem to get manual spindle control working.

bcnc rev 0.9.0.1
grbl rev 1.1
running on Raspberry pi3.

I can control the spindle with g code but not with the manual control.

Thanks Adam

**Comment by vlachoudis** [comment]
Pressing the Spindle button sends the relevant on/off mxxx command. However when on you need to drag the slide with the RPM. BTW you have the latest version of bCNC?

**Comment by adambrum** [comment]
I don't get any commands when I press the spindle button at all.

**Comment by vlachoudis** [comment]
Check if in the Tools->Config you have the "Laser Cutter" option enabled

**Comment by adambrum** [comment]
I have tried that,

The spindle button does show as depressed when I click it but no commands sent

**Comment by adambrum** [comment]
All my fault, works if machine is in idle mode.

Thanks for the help.

Just one other thing, when i overtravel after homing with soft limits enabled i get error 2 and the only way to clear it is to stop and restart communications ?

Any ideas
