### ISSUE TITLE
I can't see buttons of plugins on toolbar.

### ISSUE THREAD

**Issue by hayttle** [vlachoudis/bCNC#645]
Hi guys, I can't see the buttons of plugins on toolbar like that:
![screenshot](https://user-images.githubusercontent.com/5686790/29499632-4476ce66-85ec-11e7-96db-f05bca2669f8.png)

**Comment by vlachoudis** [comment]
It is changed in the last versions, and now are in the drop down menus.
```CAM v``` has a drop down arrow you click it and then you have everything there
