### ISSUE TITLE
importing DXF

### ISSUE THREAD

**Issue by dodolbysuround** [vlachoudis/bCNC#646]
Hey there,
I have some troubles importing DXF from Inksape. Are they any tricks or any point to care about when I generate the DXF?
My problem tooday is that rectangles with rounded squares are considered as right angle by BCnc
Thank by advance

**Comment by vlachoudis** [comment]
Can you send us the dxf you tried, maybe as well the svg from inkscape

**Comment by dodolbysuround** [comment]
Here you are (-;

[logo.zip](https://github.com/vlachoudis/bCNC/files/1251165/logo.zip)

**Comment by vlachoudis** [comment]
It is not bCNC that interprets wrongly is the dxf conversion the problem. If you open your dxf with any cad (e.g. librecad)
![image](https://user-images.githubusercontent.com/3834594/29705134-063e69bc-897d-11e7-8c1c-b955ae13eaa9.png)

I would suggest to convert all objects to paths in inkscape Menu -> Path -> Object to path
```Shift-Control-C```
BTW How did you convert the svg to dxf?

**Comment by dodolbysuround** [comment]
I just used "save as" / .DXF 
is there any better way to do?

**Comment by vlachoudis** [comment]
Interesting I didn't know that :)
Anyway if you convert first to paths then it works.
