### ISSUE TITLE
Cannot connect to serial port

### ISSUE THREAD

**Issue by kirch93** [vlachoudis/bCNC#647]
Hi Guys,

I have downloaded and installed python 2.7.13, pyserial 3.3 and BCNC, but cannot get anything to show up in the com port section. I also cant seem to get windows 7 to give me a com port number to type in manually either. I have a USB 2.0 type b plugged into my phoenix cnc controller which goes to the standard usb on the computer.

I am not sure if it is a problem with pyserial or not. Any help would be greatly appreciated.

**Comment by vlachoudis** [comment]
You can try in the command line
C:> python
...
>>> import serial
and check the error message it will return

**Comment by electrokean** [comment]
Check if the COM port appears under Ports in Windows Device Manager.  If it doesn't, or if it says it isn't working, then pyserial won't be able to use it.  You may need to install a driver for the CNC controller USB interface.

**Comment by Harvie** [comment]
Please reopen if issue persists

**Comment by JWood1w4** [comment]
I'm having the same issue. 
![image](https://user-images.githubusercontent.com/49564031/56046687-cc01ad80-5d11-11e9-8a45-65f94b354ddc.png)

Here is what I've got as an error message.

I also don't have the drop down menu. The board shows up in the IDE and my device manager. Any ideas?

**Comment by JWood1w4** [comment]
> 
> 
> You can try in the command line
> C:> python
> ...
> `>>> import serial`
> and check the error message it will return

I'm not getting anything back at all.

![image](https://user-images.githubusercontent.com/49564031/56047236-fb64ea00-5d12-11e9-9b7e-2da35896fee9.png)

**Comment by Harvie** [comment]
Have you installed bCNC using pip as reccomended in README and wiki?

**Comment by JWood1w4** [comment]
I can get pyserial to work. I can get it to show com3. IDK what is wrong. 
![image](https://user-images.githubusercontent.com/49564031/56059569-5823cd00-5d32-11e9-9e2e-fd2e4902de9c.png)

**Comment by Harvie** [comment]
Have you installed bCNC using pip as reccomended in README and wiki?
Can you provide output of `pip freeze`?

**Comment by georgegohl888** [comment]
Ii have the same issue with windows 10
