### ISSUE TITLE
Checkbox plugins doesn't check (WINXP)

### ISSUE THREAD

**Issue by crafted77** [vlachoudis/bCNC#653]
Hello. 
Congratulations on your work! I've encountered a problem... checkbox (plugins option) doesn't check on winxp with python 2.7.5, PIL 1.1.7, bCNC 0.9.10,

**Comment by crafted77** [comment]
Hi... maybe i've "found" the problem... fonts?
My checkbox will not check when clicked but bcnc work. So, i can't see the "x" into the checkbox. Anyone use winxp with bcnc? I've try thaoma font... now i see the sqaure box but no "x".
Sorry for my bad english

**Comment by crafted77** [comment]
Solved! 

Install Supplemental language support

**Comment by vlachoudis** [comment]
Good to know. Thanks
