### ISSUE TITLE
autolevel

### ISSUE THREAD

**Issue by kees1948** [vlachoudis/bCNC#667]
Hello,

I loaded a G-code file for alignment drill. I used 'margins' to set the size of
the area. And after Scan I learned to my surprise that is was working in 
mm. The G-code file has an G20 line which should flag it as in inches.

What did I wrong or what did I miss?

best regards
Kees

**Comment by vlachoudis** [comment]
The autoleveling is done on the units that you have specified in the settings of bCNC and should be consistent with Grbl. Do you have everywhere flag as inches?

**Comment by kees1948** [comment]
On 10/12/17, Vasilis Vlachoudis <notifications@github.com> wrote:
> The autoleveling is done on the units that you have specified in the
> settings of bCNC and should be consistent with Grbl. Do you have everywhere
> flag as inches?
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/vlachoudis/bCNC/issues/667#issuecomment-336214001

Hello Vasilis,

I'm not sure if I understand you completely. The G-code file has the
G20 line, which as I understand should indicate inches. You meant to
say that the grbl interpreter should
take note of that? The display in bCNC also is scaled down to mm where
the sizes are inch.

I'm learning the CNC lingo and principles still.

thank yoy,

Kees

**Comment by vlachoudis** [comment]
In the "Tool -> Config" you should have  inches or mm matching the grbl setting "Tool -> Controller -> $13 Report Inches"
