### ISSUE TITLE
Avoid homing between offsets

### ISSUE THREAD

**Issue by RadicBotanic** [vlachoudis/bCNC#681]
Hello,

First off I'd like to say how greatly I appreciate the work being done on here and how much I've been enjoying using and learning to use bCNC. Thank you for the hard work. I'm having trouble figuring out how to avoid homing between work offsets for fear of crashing. Another problem I'm encountering is when pausing a job I can't figure out how to restart it. I can only stop it and in that case it would home before I can restart(which would also rerun the entire operation from the start rather than picking up where I left off). Thank you for you time and effort.

**Comment by vlachoudis** [comment]
First question I didn't understand. Normally changing work offsets, you don't need to home. 
To resume click again the "Pause" button is toggling between pause /   resume.
