### ISSUE TITLE
Integrate A Machine Timer [Enhancement]

### ISSUE THREAD

**Issue by atrueresistance** [vlachoudis/bCNC#684]
@vlachoudis If I'm looking to integrate a machining timer where would I go about it?

The idea here is since bCNC runs all the code and it keeps track of execution time is there a easy way to have it sum all the time up and store it in like the bcnc.ini file?

It would be nice to view how many hours ran on a spindle to anticipate replacing router brushes or determine what hours of the day a particular machine is seeing the most use.

**Comment by vlachoudis** [comment]
Do you want accurate timing that the spindle is on or some rough idea, e.g. total execution time.
You could potentially use the time of the progressbar of the status. I have to give a look on how to extract the information and save it.

**Comment by CyberHugger** [comment]
Assuming we're not using spindle control I guess the only way you would know is based on the execution time for the tool paths. Not sure if you can pick that out of the gcode to decide what to measure or if we'll need to have a configuration item somewhere to tell you.  It gets even more complicated for those who may use the same machine for multiple uses like CNC and Laser.  How would you know? It might be easier to just add an AC hour meter to your spindle.

**Comment by atrueresistance** [comment]
That is what I was thinking, based off the status. I don't think it needs to be super accurate. The multiple device question is something to consider. I'm one of those people using it for CNC and laser, but just looking for a general hour usage.

**Comment by Harvie** [comment]
I think this should be implemented in GRBL or VFD as some people might use various g-code senders on that machine.
