### ISSUE TITLE
Improve GUI (flat ? ) 

### ISSUE THREAD

**Issue by masterleo** [vlachoudis/bCNC#686]
I think the icons should be flat design and with 3 colors only. like this : 
![97ff4303099f0800a59a47a6bbb45e4a--flat-design-app-design](https://user-images.githubusercontent.com/8157302/32098775-0f2d4d50-bb0e-11e7-874c-58ef9bec607b.jpg)

**Comment by masterleo** [comment]
If you are ok with that or agree please reply to me and say it.

**Comment by vlachoudis** [comment]
Closed as duplicate of #679
