### ISSUE TITLE
Serial Timeout

### ISSUE THREAD

**Issue by Guenni75** [vlachoudis/bCNC#691]
I got a Serial Timeout every few minutes (write timeout)!!
Can't do anything!

Tested the latest BCNC Version, the same Problem!

**Comment by vlachoudis** [comment]
Most probably you have a noise problem. There are many threads and discussion on that on the web

**Comment by Guenni75** [comment]
After 4 hours with no Problems?
Where was the noise 4 hours befor? 
I used another Laptop and all works fine.

**Comment by vlachoudis** [comment]
Thank, I am closing the issue
