### ISSUE TITLE
G-code words consist of a letter and value. Letter was not found.

### ISSUE THREAD

**Issue by pb777** [vlachoudis/bCNC#692]
Hi I got an error while milling with autoleveling. I think this could be an Issue because the Gcode seems OK for me (There are Letters for XYC- see screenshot). I tried the same Gcode without autoleveling and had no failure.
![image 1](https://user-images.githubusercontent.com/33527673/32625850-bd3eb242-c58d-11e7-9b68-d46cce85e568.png)

**Comment by CyberHugger** [comment]
The Z value in that command is really long. I wonder if something isn't prepared for that level of precision.

**Comment by iceturf** [comment]
I noticed this issue myself, I found the only solution was to restart bCNC.

**Comment by pb777** [comment]
Meantime i changed the USB-Cable and I never had this problem again, maybe it is Communicationfailure.

**Comment by iceturf** [comment]
Curious - I have a CNC protoneer Hat, so I can't shorten or change my cabling. Good to hear you were able to clear up the problem.

**Comment by Harvie** [comment]
Use latest version. If problem persists, try the editor tab -> edit -> "round" feature.
