### ISSUE TITLE
USB numpad

### ISSUE THREAD

**Issue by goloplo** [vlachoudis/bCNC#695]
I know that the usb keypad is already mapped by default, but is there any method to use the shortcuts to custom map this type of numpad?
![51xg4vxvzel _ss500_](https://user-images.githubusercontent.com/18336193/32980670-ac80f948-cc62-11e7-844d-531b54ad7295.jpg)

**Comment by vlachoudis** [comment]
Unfortunately not through any configuration. It needs some tweaking in the code.

**Comment by einencool** [comment]
Hello,

Would it be possible to add the macros to the Shortcuts?
How much work would it be? I don‘t know much about programming, but it would be very nice to add the macros to the shortcuts, so I could map them to the wireless Num Pad and it would make controlling the CNC much easier.

Thank you in advance.
