### ISSUE TITLE
Smoothie Issue with Center Probe using a ring

### ISSUE THREAD

**Issue by Norxcode** [vlachoudis/bCNC#705]
Had issues running the _Center Probe Using A Ring_ job

Setup: bCNC 0.9.10 , and SmoothieBoard. 

Every attempt resulted in the "z probe triggered before move aborting command" - if not at the first side, it would fail on one of the other.

Found a way around it by editing the probepage.py and - adding a few extra %wait so that the move from the wall could be finished before issuing the next G38.3 code.

lines.append("%s x-%s"%(cmd,diameter))
lines.append("%wait")
lines.append("tmp=prbx")
lines.append("g53 g0 x[prbx+%g]"%(diameter/10))
lines.append("%wait")
lines.append("%s x%s"%(cmd,diameter))
lines.append("%wait")
lines.append("g53 g0 x[0.5*(tmp+prbx)]")
lines.append("%wait")
lines.append("%s y-%s"%(cmd,diameter))
lines.append("%wait")
lines.append("tmp=prby")
lines.append("g53 g0 y[prby+%g]"%(diameter/10))
lines.append("%wait")
lines.append("%s y%s"%(cmd,diameter))
lines.append("%wait")
lines.append("g53 g0 y[0.5*(tmp+prby)]")
lines.append("%wait")
lines.append("g90")
self.app.run(lines=lines)

**Comment by vlachoudis** [comment]
Thanks, I've included your change
