### ISSUE TITLE
Spindle Start then stop when bCNC loads

### ISSUE THREAD

**Issue by Biggs427** [vlachoudis/bCNC#717]
I'm running bCNC  latest version under linux on Raspberry PI.  Everything works fine except the when I launch bCNC the spindle starts automaticly runs for 1-2 sec then stop.

Once loaded, the start/stop and RPM control are working flawlessly.

What would cause such behaviour?

Thanks

**Comment by tuxintrouble** [comment]
As far as I know this is a GRBL/Arduino problem. Ehen bCNC connects, it resets GRBL which toggles the Arduino's Spindle output.I have routed my pwm wire through the e-stop switch, which I have locked when I start bCNC. Otherwise there is not much you can do about it IMO.

**Comment by lalo-uy** [comment]
You can remove de 100nF cap ( or the R in the V4) to avoid auto reset at
port openig. You will have to manual press RESET to flash after that.

2018-01-09 19:07 GMT-03:00 Sebastian Stetter <notifications@github.com>:
