### ISSUE TITLE
How to implement custom macros and/or buttons

### ISSUE THREAD

**Issue by CyberHugger** [vlachoudis/bCNC#718]
I have the gcode to do a 3-axis probe but right now I have to go load that file and run it to perform the function then go load the gcode for the thing I want to mill. Is there any way to create a macro or button that will execute that gcode without messing with a gcode file I already have loaded?

**Comment by Guenni75** [comment]
Right click on one of the six Buttons in the menu (above USER).
Put the Gcode into the Box.
