### ISSUE TITLE
error:20

### ISSUE THREAD

**Issue by kaizoku-619** [vlachoudis/bCNC#735]
Hey guys, when I try to start running the program I get the following error: **error:20** the error indicates that an unsupported or invalid g-code found in block. But when I try the g-code in another cnc software it works fine.
![screenshot from 2018-01-30 20-21-59](https://user-images.githubusercontent.com/22129291/35586532-a52f55d0-05c0-11e8-8471-db1292a2f5c8.png)

**Comment by vlachoudis** [comment]
Click on the red "error:20" button to see which line is causing the problem.
It is mentioned several times, that bCNC stops for safety when any error is reported from the controller, while other senders silently continue.
However there are ways (see the wiki) on how to tell bCNC to not send any "invalid command" from the controller.

**Comment by AhmedGhar** [comment]
@vlachoudis , I have the same problem, and I couldn't setup bCNC t not send any "invalid command".

**Comment by Harvie** [comment]
Should be fixed. Please use latest grbl and latest bcnc git master. reopen if still needed.
