### ISSUE TITLE
Database Location

### ISSUE THREAD

**Issue by NPolman** [vlachoudis/bCNC#736]
Hello,

I am using bCNC on a Windows (10) and a Linux (Debian 9) Laptop.
But i want to copy my materials/tools database from the Windows to the Linux Laptop but cant find a file that holds them.
where can i find the file that holds my database or what do i need to copy to get my current database on my Linux Laptop. 
if i copy the whole directory bCNC wont launch on the linux.

thanks for the help

**Comment by Harvie** [comment]
see wiki https://github.com/vlachoudis/bCNC/wiki/Configuration



    Even in windows the .bCNC file is created in the user folder. You can reach it easily using the Environment variable %UserProfile% . Hit [Windows key + R], paste %UserProfile% in the Run prompt, then click OK. The user folder will open and there you'll find the .bCNC file. Right click and choose "open with" then select notepad.

The configuration file can also be viewed using the button in Tool --> Config --> User file.
