### ISSUE TITLE
Probe Orient creating g-code errors

### ISSUE THREAD

**Issue by gattarin** [vlachoudis/bCNC#737]
Hi!

I'm trying to align my stock using Probe->Orient. This used to work well, but today I think I stepped on a bug.

When trying to orient attached file, bCNC will change this line:
G18 G3 X44.314 Z0.5 I-0.317
to
G3 G3 X44.287233 Z0.5 I-0.316973 Y-8.523884 J0.00414

This line is failing to run on my GRBL 1.1f.20170801

Is this a BUG?
If you could advise workaround I would much appreciate it?

Thanks,
Marcin

[Holes v1.txt](https://github.com/vlachoudis/bCNC/files/1692155/Holes.v1.txt)

**Comment by gattarin** [comment]
Sure! This is least I could do in return for this great software!
Thanks!
Marcin

W dniu pon., 5.02.2018 o 08:46 Vasilis Vlachoudis <notifications@github.com>
napisał(a):

**Comment by vlachoudis** [comment]
Please try the new master. It should correct the problem
