### ISSUE TITLE
Probe offset 

### ISSUE THREAD

**Issue by fabriziobianchi34** [vlachoudis/bCNC#738]
Hello .In the bncn is there a offset setting in Z  of probe settings.
Is there  a way to make  a offset in X ?
Because i use  a sensor ir and i have it -60 mm of the center.
Thanks

**Comment by vlachoudis** [comment]
It is the controller who is interpreting the information on the offset.
bCNC just passes the information to the controller as is, and
there is only one setting on the TLO
