### ISSUE TITLE
no reaction from ultimaker

### ISSUE THREAD

**Issue by macsimski** [vlachoudis/bCNC#76]
hello all,

setup: bCNC 0.4.9 on Ubuntu 14.04 64bit. machine: ultimaker original with marlin firmware.

symptoms: connecting goes ok. after pressing home, $H is sent??? pressing unlock sends $X

partially log from terminal window (no copy paste possible)

echo:Marlin1.0.0
echo: Last Updated: Feb 19 2015 09:56:12 | Author: (David Braam)
Compiled: Feb 19 2015
...<bla setup>...
echo:SD init fail
$H
echo:Unknown command: "???????????????????????????????$H"
ok

where are those variables $H and $X defined?

**Comment by vlachoudis** [comment]
Hi, bCNC is working with the Grbl firmware.
The $H and $X are the homing and unlock commands of grbl.
