### ISSUE TITLE
DXF generated by Autodesk 123D

### ISSUE THREAD

**Issue by demsjfp5** [vlachoudis/bCNC#763]
When opening a dxf file, the console shows:
"Cannot handle entity type: 3DSOLID in layer: 0"

simple test file attached containing a simple cube with a hole.
[test.zip](https://github.com/vlachoudis/bCNC/files/1725746/test.zip)

Program     : bCNC
Version     : 0.9.14
Last Change : 5 Feb 2018
Platform    : win32
Python      : 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
TkVersion   : 8.5
TclVersion  : 8.5

**Comment by vlachoudis** [comment]
bCNC can only handle 2D DXF files. 3D objects are not supported. Sorry
