### ISSUE TITLE
Xbox controller no longer works after entering Gcode manually.

### ISSUE THREAD

**Issue by probe3** [vlachoudis/bCNC#765]
I'm using a program called Xpadder to map keyboard keys to my Xbox controller which I'm using as a XYZ remote. Everything works fine when I start a new job but when the job is over and I want to change a tool, I manually type "G0 X0 Y0" so the spindle goes to X0 and Y0 so i can swap the tool and find my new Z0. After I type in the Gcode manually the Xbox remote stops working.

**Comment by vlachoudis** [comment]
While the focus is on any text input field, no commands are send to controller.
Only when the focus is on the canvas the keyboard commands are send.
You can always press escape to move the focus to the canvas

**Comment by probe3** [comment]
Thank you!
