### ISSUE TITLE
High DPI blur solution

### ISSUE THREAD

**Issue by SLS8** [vlachoudis/bCNC#772]
Hi
I ran bCNC for the first time on a high dpi display, on Win 10, and all the fonts were blurry because of not being dpi-aware by default. After finding this thread:
https://stackoverflow.com/a/43046744
all i did was to add "from ctypes import windll" and the line "windll.shcore.SetProcessDpiAwareness(1)" at the beginning of the bCNC.py code marked as  "Main Application window".

Now the gui is clear and sharp.

**Comment by vlachoudis** [comment]
Thanks. Good to now
