### ISSUE TITLE
Plasma cutting

### ISSUE THREAD

**Issue by Nossolov** [vlachoudis/bCNC#774]
I use bCNC now for plasma cutting. I activate the Laser cutting option in config, and plasma start and stop at the right places. Good ! Sadly, plasma need time for drilling metal. I add lines in Gcode "g4 Pxx" after each "m3", with more or less xx according to thickness.
Could it be possible to add plasma option just like laser in config, and automatically generate Gcode with the lines "g4 pxx" ?
Thank's.

**Comment by vlachoudis** [comment]
On my new branch, I've added two fields to be user customized gcodes what one can consider as "enter/exit" or "start/stop" for each path.
