### ISSUE TITLE
Serial not working correctly.

### ISSUE THREAD

**Issue by mano1979** [vlachoudis/bCNC#779]
When i start bCNC the serial connection is not working correctly. it makes a connection but the status bar still says "not connected", and the cnc is not reacting to any buttons. If i use another program to make a serial connection, all is fine. After that bCNC can also connect properly.

I am using GRBL 0.9 (grbl-for-cyclone (ramps1.4 and arduino mega2560))

**Comment by jpascher** [comment]
did you install the serial 3.4 and Python 2.7.4 correctly?  Serial driver has to be installed or added to Python in a  command line  way. The fist time i installed my driver did not work either.

**Comment by Harvie** [comment]
Does this still happen? I tried grbl for ramps once and it seemed buggy to me, but i wasn't doing much testing. have you tried real grbl?
