### ISSUE TITLE
Usb connector

### ISSUE THREAD

**Issue by avilab84** [vlachoudis/bCNC#784]
the USB button shows a blue cable that was used in the 90s. 
I would prefer a icon of a usb cable.
https://github.com/vlachoudis/bCNC/blob/master/icons/serial32.gif
![image](https://user-images.githubusercontent.com/14994740/37857389-eae0d44c-2efa-11e8-8240-5fbea144445c.png)

**Comment by vlachoudis** [comment]
Correct. Could you find a nice one with 32x32 pixels. When I resize it the result is not nice.

**Comment by masterleo** [comment]
Maybe this one ? 

![serial32](https://user-images.githubusercontent.com/8157302/37926007-74c30f30-3136-11e8-8fa8-df517add48e6.gif)

**Comment by masterleo** [comment]
I use it on my BCNC it is great 
![img_20180326_221644](https://user-images.githubusercontent.com/8157302/37931014-a354b4ee-3144-11e8-9d87-ed4948662a1b.jpg)

**Comment by masterleo** [comment]
On the same topic, the button should be green when connected and red when disconnected. (Quote from my girlfriend) The actual behaviour shows red when connected.

**Comment by vlachoudis** [comment]
done
