### ISSUE TITLE
Keyboard Zoom not Working in Windows

### ISSUE THREAD

**Issue by crowjik** [vlachoudis/bCNC#8]
So the zoom doesn't work with the keys that show in the menu (=, -). It does work when I click on "Zoom In" or "Zoom Out" in the menu, so this isn't a big deal. May be another issue with the tkinter windows library?

**Comment by vlachoudis** [comment]
It was an error on the tooltip. It works with Control + equal or minus.
=,- alone increases/decreases the step size of the jogging
