### ISSUE TITLE
Profile / pocketing operation takes a long (infinite?) amount of time

### ISSUE THREAD

**Issue by MrSurly** [vlachoudis/bCNC#801]
Using the attached DXF:

Ubuntu 17.10, bCNC tag 0.9.11

* select the "outline" path
* then under "tools," select "Profile", using a default 3.175mm end mill, outside, no overcut
* click "profile"

"Spinner" style mouse pointer, have waited several minutes without any response.  No error messages on the console.

[slide.zip](https://github.com/vlachoudis/bCNC/files/1896008/slide.zip)

**Comment by vlachoudis** [comment]
Thanks for the report. Please try the new master which solves the problem.
