### ISSUE TITLE
Filter the console/log file?

### ISSUE THREAD

**Issue by WillAdams** [vlachoudis/bCNC#81]
The console has a lot of redundant information --- could we filter it and not repeat?

e.g., the statement of the current machine position --- if this hasn't changed from the last report, why mention it? Instead, just output a single character if it hasn't changed over a given timeframe, then double that time before the next period is emitted:

 - . --- machine has been stationary for 0.25seconds
 - .. --- machine has been stationary for 0.75 seconds (0.25 + 02.5*2)
 - ... - machine has been stationary for 1.75 seconds
 - .... 3.75
 - ..... 7.75
 - ...... 15.75

&c.

**Comment by vlachoudis** [comment]
@WillAdams, its an interesting proposal. Right now the programs updates the state

- every 0.25s with a ? to check the position of the machine, but this information is not dumped at all in the console. It is transparent to the user.
- periodically with a $G command every 10s, while it is not running and if there was an I/O activity in between
- every time you click on the "WCS" tab, it requests the parameters of the machine
- on some commands that will could possibly change the state of the machine

Maybe we could keep a dictionary with the last returned lines from grbl and check for any change there.
