### ISSUE TITLE
New user using raspberry pi on official 7 in touch screen

### ISSUE THREAD

**Issue by andrewjacko** [vlachoudis/bCNC#814]
G'day I've just started playing with bcnc on my raspberry pi using the 7 inch touch screen. Whenever I try to change the screen resolution and exit out the program and re open it it defaults back to its original setting of 958 X 490. Is it correct for me to change these settings in the bcnc tools tab then click on config the user file? Or do I change these settings somewhere else?

**Comment by buschhardt** [comment]
Hallo there is also a commandline parameter -g
`./bCNC -g 600x600` 

Greetings from Saxonia
