### ISSUE TITLE
Problem with Profile in Command Line in the direction inside

### ISSUE THREAD

**Issue by MARIOBASZ** [vlachoudis/bCNC#822]
On the command line, if I write:
profile 1 in
make the route out for that tool value!
Only allows the internal route for the tool loaded in the software.
Another point: It would be nice to add an offset as another parameter, either in the form:
profile 1 0.5 out
or
profile 1 out 0.5
or
profile 1 + 0.5 out

**Comment by vlachoudis** [comment]
Try putting a sign on the offset
```profile 1```    (outside)
```profile -1```  (inside)
or
```profile i[nside]```
```profile o[utside]```
using the default tool

**Comment by MARIOBASZ** [comment]
Thank you! Although it works in the same way in / out as -1/1, it does what I want, it writes the diameter of the tool with its corresponding sign
