### ISSUE TITLE
event trigger

### ISSUE THREAD

**Issue by sjamesparsonsjr** [vlachoudis/bCNC#835]
I have a python script that takes a picture and runs openCV image process.  I've added the event to .bCNC with a path to the script.  How do I trigger said event?

**Comment by sjamesparsonsjr** [comment]
So I was thinking that scripting might work instead of an event.  However, when I use %pythone code, nothing happens.  Anyone have an example I can see?

**Comment by Harvie** [comment]
This works for me: `%print "lol"`
