### ISSUE TITLE
The bCNC don't load a large design

### ISSUE THREAD

**Issue by Thorgrlm** [vlachoudis/bCNC#843]
Hi all people, I found a problem in the software, when I load my design in the software if my design is large, in the screen not show all design, if I send the work at my CNC, my CNC make work all

**Comment by Thorgrlm** [comment]
This is my desing
[img]https://i.imgur.com/misEJ72.png[/img]

This is my desing in the bCNC
[img]https://i.imgur.com/SWzz78H.png[/img]

**Comment by aujgillam** [comment]
I was having this same issue. Make sure the timeout settings are not set too low, it is the drop down at the top right of the design box. see issue 485 [https://github.com/vlachoudis/bCNC/issues/485]

**Comment by Thorgrlm** [comment]
Hi my friend, thanks you for yopur help, this is solved
