### ISSUE TITLE
bCNC TinyG and Pi3

### ISSUE THREAD

**Issue by Seb66** [vlachoudis/bCNC#844]
Hi,

I have changed out my CNC controller to a TinyG and cannot get the USB port/Connection active.
There is no USB driver other than usb0 and AMAO. When i open usb 0 the prompt says it connected but doesnt change the orange button?

How do i get tinyG to work with bCNC on a Pi3?

**Comment by vlachoudis** [comment]
I have a version which **works** (a big word) with TinyG. It lacks still many features in order to be compatible.

**Comment by MARIOBASZ** [comment]
Excellent! I want to test the operation of the machine with jerk control and so far only G2Core / Tinyg has implemented it. It would be nice to be able to handle it from BCNC

**Comment by colinluthier** [comment]
@vlachoudis Is the TinyG version available as a Beta?

**Comment by Harvie** [comment]
Duplicate of #83
