### ISSUE TITLE
Tool change

### ISSUE THREAD

**Issue by iceturf** [vlachoudis/bCNC#845]
Hi, 

    so I've run into a few small issues with bCNC - and the most overt thing is...

Tool changes - say I'm doing a drill file, with multiple drill sizes. To change the sizes, I would then have to re-probe to get the correct height. I'd be curious if there would be way to allow for re-probing during a pause situation?

**Comment by vlachoudis** [comment]
You need to configure bCNC for manual tool changes (see the wiki) and then
supply a tool change command in the gcode

**Comment by iceturf** [comment]
Thanks, I guess I'm still getting familiar with the bCNC features - I totally missed that wiki.
