### ISSUE TITLE
I have problems in  the autolevel test

### ISSUE THREAD

**Issue by Thorgrlm** [vlachoudis/bCNC#846]
Hi my friends everyone, I don't understand well the steps to follow to perform the autoleveling since it doesn't work properly, always the tool sinks more than what I want.
The way I do it is:

I take the portico to the point where I want to make the pcb and I establish the axis X = 0; Y = 0
I select the probe tab.
I execute the probe test to locate the point Z = 0
I set that position at Z = 0 in the software.
I now perform the autolevel test, when it finishes I take the tool to the position X, Y, Z = 0 and I press the Zero button in the autolevel menu.
The last step I go at the control tab and press the start button

**Comment by vlachoudis** [comment]
This is repeated question, please change the rendering **Timeout:** on the drop down box top-right of the canvas
