### ISSUE TITLE
ImportError: No module named tkinter

### ISSUE THREAD

**Issue by josb86** [vlachoudis/bCNC#848]
Hi, I am trying run bCNC, but when a execute in cmd show me:

File "C:\user\...........\bCNC\bCNC.py", line 32, in <module>
   import tkinter
ImportError: No module named tkinter

What can I do?

**Comment by vlachoudis** [comment]
Most probably you installed python v3. bCNC works with v2

**Comment by josb86** [comment]
Hi, I have installed 2.7.15

**Comment by vlachoudis** [comment]
Could you reinstall python and ensure you select that tkinter is installed.
