### ISSUE TITLE
Import button not easy to find

### ISSUE THREAD

**Issue by Harvie** [vlachoudis/bCNC#877]
I've been looking for import button here in file menu:

![image](https://user-images.githubusercontent.com/276504/41879738-349c5974-78db-11e8-9579-ef00fb53d908.png)

For several days i was thinking that the feature was removed, but then i've found it's just hidden in editor menu:

![image](https://user-images.githubusercontent.com/276504/41879764-53eb13b0-78db-11e8-8d6e-ac5d95feeb76.png)

I think this feature might make sense to have in both of these menus. Sometimes i just want to quickly open two drawings/gcodes at the same time to check differences between them. Or overlay them for some other reason...

**Comment by Harvie** [comment]
I've tried adding button to `FilePage.py` and then in `bCNC.py` add this:

```python
                self.bind('<<Import>>',           self.importFile)
```

It gives following error, don't know why:

```
Traceback (most recent call last):
  File "/home/harvie/Temp/bCNC/Utils.py", line 421, in __call__
    return self.func(*args)
  File "./bCNC.py", line 2005, in importFile
    fn,ext = os.path.splitext(filename)
  File "/usr/lib/python2.7/posixpath.py", line 98, in splitext
    return genericpath._splitext(p, sep, altsep, extsep)
  File "/usr/lib/python2.7/genericpath.py", line 99, in _splitext
    sepIndex = p.rfind(sep)
AttributeError: Event instance has no attribute 'rfind'
```

**Comment by vlachoudis** [comment]
You should call importFile without any argument like 
```lambda x,s=self: s.importFile()```

**Comment by Harvie** [comment]
![image](https://user-images.githubusercontent.com/276504/42138803-8b85573e-7d83-11e8-9cb2-aefb252c1a50.png)

coming in next pull request :-)

**Comment by avilab84** [comment]
The new button is not usefull !

**Comment by Harvie** [comment]
@avilab84 it's not new button, it's old button in new place. also if it's not usefull for you then simply don't use it. problem solved :-) what works for one, might not work for other. i don't use all bCNC buttons either.
