### ISSUE TITLE
Work area display

### ISSUE THREAD

**Issue by yOPERO** [vlachoudis/bCNC#89]
Hi everyone
I am having some problem trying to find out how to get the "work area" box to be displayed properly.

![mygrbl1](https://cloud.githubusercontent.com/assets/1375754/9213082/b37b7ae4-4086-11e5-845a-1ad9949033c2.png)

If yo look at the screenshot above you will see that the "work area "box goes from (0,0) to (-200,-200).
According to my settings in bCNC.ini it should go from (0,0) to (200,200) : 
[CNC],
units = 0
acceleration_x = 25
acceleration_y = 25
acceleration_z = 50
feedmax_x = 3000
feedmax_y = 3000
feedmax_z = 2000
travel_x = 200
travel_y = 200
travel_z = 100

Do you guys think it may be something related to my grbl(0.9) settings ($130,$131 and $132) ?

**Comment by vlachoudis** [comment]
Hi @yOPERO it is a common convention that the workspace is at negatives coordinates
look at the #42. You have to set the workarea dimensions in the configuration of bCNC as well in grbl. After homing it should display correctly.
