### ISSUE TITLE
[Question] Autolevel interpolation and line segmentation

### ISSUE THREAD

**Issue by androiders** [vlachoudis/bCNC#896]
Hello!
I have started using bCNC for pcb milling and so far i really like it. I have some questions though. I am trying to find how i can "optimize" the auto leveling by using as few probe points as possible. This leads me to questions:

1. How is the interpolation done between the points on the grid? Is it just linear interpolation?
2. The autolevel wiki page states that "G1 commands will be split in multiple segments if needed". How is this split made and what controls it? 
3. Generally, how many points/units(square) do people use when auto levelling a pcb?  

The reason for the questions is that i get big variations in result even with quite small difference in size of pcbs. 

Anyways, thanks for the program and the effort!

--Anders Folkesson

**Comment by vlachoudis** [comment]
1. Linear interpolation
2. The split is done on the grid lines and as well up to a maximum sagitta defined by the user
3. Depends how flat is your working surface. Typically I do select an average spacing between
the probe points of 10-20mm

**Comment by androiders** [comment]
Thank you! I will keep experimenting with the grid size.
