### ISSUE TITLE
Add  "viewing angle"  to .bCNC

### ISSUE THREAD

**Issue by yOPERO** [vlachoudis/bCNC#90]
Not sure if it you can add this to the current version or to next but it would be nice to set the view  along with the other settings in .bCNC file.

I do prefer ISO1 so I have hard coded it myself on bCNC.py(line116).

Thanks.

**Comment by vlachoudis** [comment]
I've added a feature to remember and restore the last view angle in the ini.

**Comment by vlachoudis** [comment]
the new release remembers the viewing angle
