### ISSUE TITLE
Problem in trochoidal splicing straight

### ISSUE THREAD

**Issue by MARIOBASZ** [vlachoudis/bCNC#914]
In splicing straight leaves the route when direction changed
![image](https://user-images.githubusercontent.com/11743403/42457888-fcd19678-836e-11e8-9ccb-edd563dbab44.png)
I had that problem that I later corrected

**Comment by Harvie** [comment]
This was already fixed in PR #911 .

**Comment by MARIOBASZ** [comment]
Ok,

**Comment by Harvie** [comment]
It is the place, but i actively work on trochoidal and chances are that by the time you file issue, there will already be new unmerged version in my fork. So if you want to try the latest version of trochoidal, you can watch my fork directly, so you don't have to wait until merge...

**Comment by Harvie** [comment]
I added support for following ARC paths by trochoids. You can discus trochoids in #815 and close this issue...
