### ISSUE TITLE
add explanatory comment to plugins

### ISSUE THREAD

**Issue by MARIOBASZ** [vlachoudis/bCNC#917]
As in issue # 802, the interesting thing about adding an image was added, it would be nice to be able to add some comments to the plugin that serves users in its use, or recommendations (see for example in the trocordial plugin)

**Comment by Harvie** [comment]
It's not in 802, it's in #806 . Also why you create new issues, when you can just add comment to that existing one? Please close this and discuss in #806.

**Comment by Harvie** [comment]
duplicate
