### ISSUE TITLE
Open file shortcut is enable during file processing.

### ISSUE THREAD

**Issue by Effer** [vlachoudis/bCNC#92]
Using the shortcut Ctrl+O during the running of a part programm, pop up the open file dialog. I think this should be avoided.
Also in the canvas if you select a part (Ctrl+A) during the straming of the file you can you can move it.

**Comment by vlachoudis** [comment]
I forgot to protect the keyboard shortcuts as well. I will put a protection in every function

**Comment by vlachoudis** [comment]
@Effer I completly forgot that... :)

**Comment by Effer** [comment]
@vlachoudis and so today we can declare the "close any issue day" ;)

**Comment by vlachoudis** [comment]
Almost :) there are a couple ones still pending. I believe the most important is the Autolevel to check if the gcode program changes units during the run. But I wanted to do it carefully...
