### ISSUE TITLE
Restlessness: Pocket Operation: Add new cutting alternatives

### ISSUE THREAD

**Issue by MARIOBASZ** [vlachoudis/bCNC#924]
in pocket operation it would be good the option of successive passes being smoothed with spiral type trajectories or directly as spirals. Another alternative used is that there is a first trochoidal central pass and then traditional straight passes
See #815

**Comment by Harvie** [comment]
Why opening new issue, when you already know there's #815 discussing this topic?

**Comment by Harvie** [comment]
closing duplicate
