### ISSUE TITLE
Help!! where I find the list with parameters for end mill?

### ISSUE THREAD

**Issue by MARIOBASZ** [vlachoudis/bCNC#925]
I want to add an end mill type T (or flat, I do not know its name), and a thickness field to make the correct thickness of fillets when generating threads, and I do not know in which file to work

**Comment by walterwissmann** [comment]
In .bcnc in the homedirectory. There the [EndMill] Section...

You can ad a tool with copy and paste the variables from an other tool, count up the variable number , edit the variables and at last count up the n-counter.
