### ISSUE TITLE
Changes occurred when opening file

### ISSUE THREAD

**Issue by MARIOBASZ** [vlachoudis/bCNC#927]
Sometimes these changes occur when you open the file by transforming the lines to comment (Block -X: G0 Z0). Cause and solution?
![image](https://user-images.githubusercontent.com/11743403/43776626-cae04a5a-9a26-11e8-94d9-fdd5dd15a967.png)

**Comment by Harvie** [comment]
Do you have latest git version of bCNC???

**Comment by MARIOBASZ** [comment]
Thanks! That happened
