### ISSUE TITLE
2d digitizer, patern digitizer, jog digitizer.

### ISSUE THREAD

**Issue by FatNarval** [vlachoudis/bCNC#929]
Hello,  great work on bcnc!
I personaly like having camera probing, it is great feature!

It is great for simple shapes, I can manualy copy (with mouse)  x,y coordinates and create gcode or plt file which could be exported and edited as vectors in other cad or cam programs.
But for  it is very tedious and error prone process due to manual copying of coordinates.

 I wish that  bcnc could be easier to use as 2d pattern digitizer,  you jog to a point pres a button/key and coordinates are stored in a single text file.  Repeat. That simple. Is it actually possible to implement this feature?
Maybe it could have options to save file as a Gcode or plt file or dxf or xls?

If this option catches on,  conversational options  like: arcs, circles,  g0/g1, feeds, Z position...etc could be added later.

Thanks

**Comment by MARIOBASZ** [comment]
uau! It would be good! I do not know how hard it is, I do not know if I am reasoning perfectly, but another application could be combined with visual recognition, it would be another way to find limits of a piece, hole center, or alignment for two-sided pcb.

**Comment by MARIOBASZ** [comment]
Or 2D 3D scanner

**Comment by FatNarval** [comment]
@MARIOBASZ   Nothing that fancy :)  I have in mind very simple solution using existing hardware (and software).
 For jogg digitizing camera is not even neccessary but it helps, you can do all digitizing fron your desktop. 
I do not know how complicated it is as I am not a programmer myself
I can not find good ilustrations on the net but here are couple of them, they are using encoders and manualy move the pointer. Idea is the same just use jog moves and camera .
https://youtu.be/lPonmGaA7Mw
https://vimeo.com/17095655
https://www.youtube.com/watch?v=hVMaa1NueWI

**Comment by FatNarval** [comment]
This is best ilustration for what I had in my mind, it is aplugin with simmilar features for mach3. I can not find any yt video to ilustrate how it works.
https://www.machsupport.com/forum/index.php?topic=28901.0

**Comment by FatNarval** [comment]
@MARIOBASZ you orobably had something like this on your mind?
https://youtu.be/vTrGxb7s1oc

**Comment by MARIOBASZ** [comment]
It would not be bad if someone wants to work on it! Perhaps it is very ambitious, with an emitting diode and a phototransistor as a line follower or complement with artificial vision. By the way, I do not know if a diode and phototransistor could be used to generate autolevel points

**Comment by Harvie** [comment]
I've added basic 2D digitizing feature to Probe page:
![image](https://user-images.githubusercontent.com/276504/44999558-7c5e4500-afbe-11e8-853e-976bba18ad56.png)
Just jog and click to record the point!

**Comment by FatNarval** [comment]
Wow! Great!
That was just I had in mind!

Testing soon!
Thanks!

**Comment by swarfer** [comment]
please refer to 
https://github.com/vlachoudis/bCNC/issues/967
where I have provided code for using shortcut keys for the RAPID and FEED buttons

**Comment by FatNarval** [comment]
Is it possible that control (jog) pad that is featured in control tab be also featured in probe tab?
This is very important for manual digitizing to be able to quicklyand change jogging step length .
Thanks!

**Comment by Harvie** [comment]
@FatNarval this is already proposed in #1057
