### ISSUE TITLE
Laser cutter option

### ISSUE THREAD

**Issue by dougmany** [vlachoudis/bCNC#93]
Do you have any interest in a laser cutter option in the config file?  I bought a Raspberry Pi CNC to replace the crappy control board on a Chinese laser cutter.  I got bCNC to work by replacing z changes in the code with m3 and m5 commands like this:

replace:		block.append("g0 %s"%(self.fmt("z",self.safe)))
with:		        block.append("M5")

replace:		block.append("g1 %s %s"%(self.fmt("z",z), self.fmt("f",self.feedz)))
with:			block.append("M3")

**Comment by vlachoudis** [comment]
Very nice idea. I don't have a laser cutter but I will add an option in the config for lasercutter and modify the code accordingly.

**Comment by dougmany** [comment]
I am looking forward to it.  Great job on this project.  It has really helped me out.

**Comment by vlachoudis** [comment]
In the new interface (just uploaded) I have an option in the settings for the lasercutter.
