### ISSUE TITLE
i can't start bcnc

### ISSUE THREAD

**Issue by darmalodar** [vlachoudis/bCNC#943]
Microsoft Windows [Versión 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Reservados todos los derechos.

C:\Windows\system32>cd..

C:\Windows>cd..

C:\>cd bcnc

C:\bcnc>dir
 El volumen de la unidad C es 64Win7
 El número de serie del volumen es: B815-16CC

 Directorio de C:\bcnc

21/08/2018  01:26 a.m.    <DIR>          .
21/08/2018  01:26 a.m.    <DIR>          ..
13/08/2018  03:29 a.m.                28 .gitignore
13/08/2018  03:29 a.m.                 0 .git_cache_meta
13/08/2018  03:29 a.m.               224 bCNC
13/08/2018  03:29 a.m.               102 bCNC.bat
13/08/2018  03:29 a.m.               160 bCNC.desktop
13/08/2018  03:29 a.m.             1,150 bCNC.ico
13/08/2018  03:29 a.m.             5,686 bCNC.ini
13/08/2018  03:29 a.m.            19,656 bCNC.png
13/08/2018  03:29 a.m.            67,980 bCNC.pot
13/08/2018  03:29 a.m.            80,488 bCNC.py
13/08/2018  03:29 a.m.            33,236 bCNC.xbm
13/08/2018  03:29 a.m.             9,192 Camera.py
21/08/2018  12:20 a.m.             8,240 Camera.pyc
13/08/2018  03:29 a.m.           136,581 CNC.py
21/08/2018  12:20 a.m.           101,137 CNC.pyc
13/08/2018  03:29 a.m.            72,585 CNCCanvas.py
21/08/2018  12:20 a.m.            59,297 CNCCanvas.pyc
13/08/2018  03:29 a.m.            29,290 CNCList.py
21/08/2018  12:20 a.m.            25,126 CNCList.pyc
13/08/2018  03:29 a.m.             5,941 CNCRibbon.py
21/08/2018  12:20 a.m.             5,919 CNCRibbon.pyc
13/08/2018  03:29 a.m.            38,489 ControlPage.py
21/08/2018  12:20 a.m.            37,875 ControlPage.pyc
13/08/2018  03:29 a.m.            19,703 EditorPage.py
21/08/2018  12:20 a.m.            20,411 EditorPage.pyc
13/08/2018  03:29 a.m.            10,553 FilePage.py
21/08/2018  12:20 a.m.            10,465 FilePage.pyc
13/08/2018  03:29 a.m.    <DIR>          icons
21/08/2018  12:45 a.m.    <DIR>          lib
13/08/2018  03:29 a.m.             1,763 LICENSE.BSD3
13/08/2018  03:29 a.m.                13 LICENSE.md
13/08/2018  03:29 a.m.             1,291 LICENSE.MIT
13/08/2018  03:29 a.m.    <DIR>          locale
13/08/2018  03:29 a.m.               343 makefile
13/08/2018  03:29 a.m.    <DIR>          pendant
13/08/2018  03:29 a.m.             7,379 Pendant.py
21/08/2018  12:20 a.m.             7,609 Pendant.pyc
21/08/2018  12:45 a.m.    <DIR>          plugins
13/08/2018  03:29 a.m.            61,726 ProbePage.py
21/08/2018  12:20 a.m.            52,084 ProbePage.pyc
13/08/2018  03:29 a.m.             3,163 README.md
13/08/2018  03:29 a.m.            21,543 Ribbon.py
21/08/2018  12:20 a.m.            19,322 Ribbon.pyc
13/08/2018  03:29 a.m.            44,250 Sender.py
21/08/2018  12:20 a.m.            40,336 Sender.pyc
13/08/2018  03:29 a.m.             6,451 TerminalPage.py
21/08/2018  12:20 a.m.             6,505 TerminalPage.pyc
13/08/2018  03:29 a.m.            53,788 ToolsPage.py
21/08/2018  12:20 a.m.            50,572 ToolsPage.pyc
13/08/2018  03:29 a.m.             6,105 Updates.py
21/08/2018  12:20 a.m.             6,222 Updates.pyc
13/08/2018  03:29 a.m.            22,101 Utils.py
21/08/2018  12:20 a.m.            21,639 Utils.pyc
21/08/2018  12:29 a.m.    <DIR>          __pycache__
              48 archivos      1,233,719 bytes
               8 dirs  264,922,771,456 bytes libres

C:\bcnc>python bcnc.py
Traceback (most recent call last):
  File "C:\bcnc\ToolsPage.py", line 934, in __init__
    exec("import %s"%(name))
  File "<string>", line 1, in <module>
  File "C:\bcnc\plugins\slicemesh.py", line 26, in <module>
    import numpy as np
ImportError: No module named numpy
Traceback (most recent call last):
  File "bcnc.py", line 2592, in <module>
    application = Application(tk)
  File "bcnc.py", line 113, in __init__
    self.ribbon = Ribbon.TabRibbonFrame(self)
  File "C:\bcnc\Ribbon.py", line 494, in __init__
    image=Utils.icons["new"],
KeyError: 'new'

C:\bcnc>

**Comment by Harvie** [comment]
Currently you need to install following python libraries to run development version:
numpy, scipy, enum

I am working on eliminating these dependecies, but i probably can't get away without numpy at all and without scipy some features would be slowed down too much.

**Comment by Harvie** [comment]
Now you should only need numpy: https://pypi.org/project/numpy/

**Comment by darmalodar** [comment]
07/10/2017  08:07 a.m.           228,621 LinuxCNC_Getting_Started.pdf
09/10/2017  01:44 a.m.    <DIR>          Mach3
25/11/2017  11:44 p.m.    <DIR>          miniBloq.v0.83
01/12/2006  11:37 p.m.           904,704 msdia80.dll
04/09/2017  03:56 p.m.    <DIR>          My Drivers
14/07/2009  12:20 a.m.    <DIR>          PerfLogs
21/09/2017  10:57 p.m.                 0 places.sqlite
08/10/2017  08:44 p.m.    <DIR>          Predator Software
21/08/2018  12:24 a.m.    <DIR>          Program Files
13/08/2018  03:11 p.m.    <DIR>          Program Files (x86)
21/08/2018  07:32 p.m.    <DIR>          pyserial-3.3
21/08/2018  12:29 a.m.    <DIR>          pyserial-3.4
21/08/2018  12:03 a.m.    <DIR>          Python27
05/05/2018  05:49 p.m.    <DIR>          ShanaEncoder
25/01/2018  10:07 p.m.    <DIR>          temp
21/08/2018  06:45 p.m.    <DIR>          totalcmd
20/05/2018  11:10 a.m.    <DIR>          Users
21/08/2018  12:27 a.m.    <DIR>          Windows
29/07/2018  10:32 a.m.    <DIR>          Windows_Repair_Toolbox
               8 archivos     13,296,423 bytes
              23 dirs  263,751,094,272 bytes libres

C:\>cd pyserial-3.3

C:\pyserial-3.3>dir
 El volumen de la unidad C es 64Win7
 El número de serie del volumen es: B815-16CC

 Directorio de C:\pyserial-3.3

21/08/2018  07:32 p.m.    <DIR>          .
21/08/2018  07:32 p.m.    <DIR>          ..
07/03/2017  07:32 p.m.            23,993 CHANGES.rst
07/03/2017  10:44 p.m.    <DIR>          documentation
21/08/2018  07:33 p.m.    <DIR>          enum-0.4.6.tar
21/08/2018  12:59 a.m.            20,265 enum-0.4.6.tar.gz
07/03/2017  10:44 p.m.    <DIR>          examples
02/05/2016  09:29 p.m.             1,885 LICENSE.txt
29/03/2016  04:31 p.m.             1,074 MANIFEST.in
21/08/2018  07:01 p.m.        13,470,769 numpy-1.15.1-cp27-none-win_amd64.whl
21/08/2018  07:01 p.m.        13,470,769 numpy.whl
07/03/2017  10:44 p.m.             1,612 PKG-INFO
18/02/2016  06:57 p.m.            12,497 pylintrc
07/03/2017  10:44 p.m.    <DIR>          pyserial.egg-info
20/12/2016  07:03 p.m.             1,763 README.rst
07/03/2017  10:44 p.m.    <DIR>          serial
07/03/2017  10:44 p.m.               146 setup.cfg
18/06/2016  04:41 p.m.             2,948 setup.py
07/03/2017  10:44 p.m.    <DIR>          test
              11 archivos     27,007,721 bytes
               8 dirs  263,751,094,272 bytes libres

C:\pyserial-3.3>cd enum-0.4.6.tar,gz
El sistema no puede encontrar la ruta especificada.

C:\pyserial-3.3>cd enum-0.4.6.tar.gz
El nombre del directorio no es válido.

C:\pyserial-3.3>cd enum-0.4.6.tar.gz
El nombre del directorio no es válido.

C:\pyserial-3.3>dir
 El volumen de la unidad C es 64Win7
 El número de serie del volumen es: B815-16CC

 Directorio de C:\pyserial-3.3

21/08/2018  07:37 p.m.    <DIR>          .
21/08/2018  07:37 p.m.    <DIR>          ..
07/03/2017  07:32 p.m.            23,993 CHANGES.rst
07/03/2017  10:44 p.m.    <DIR>          documentation
21/08/2018  07:33 p.m.    <DIR>          enum
21/08/2018  12:59 a.m.            20,265 enum-0.4.6.tar.gz
07/03/2017  10:44 p.m.    <DIR>          examples
02/05/2016  09:29 p.m.             1,885 LICENSE.txt
29/03/2016  04:31 p.m.             1,074 MANIFEST.in
21/08/2018  07:01 p.m.        13,470,769 numpy-1.15.1-cp27-none-win_amd64.whl
21/08/2018  07:01 p.m.        13,470,769 numpy.whl
07/03/2017  10:44 p.m.             1,612 PKG-INFO
18/02/2016  06:57 p.m.            12,497 pylintrc
07/03/2017  10:44 p.m.    <DIR>          pyserial.egg-info
20/12/2016  07:03 p.m.             1,763 README.rst
07/03/2017  10:44 p.m.    <DIR>          serial
07/03/2017  10:44 p.m.               146 setup.cfg
18/06/2016  04:41 p.m.             2,948 setup.py
07/03/2017  10:44 p.m.    <DIR>          test
              11 archivos     27,007,721 bytes
               8 dirs  263,751,081,984 bytes libres

C:\pyserial-3.3>cd enum

C:\pyserial-3.3\enum>dir
 El volumen de la unidad C es 64Win7
 El número de serie del volumen es: B815-16CC

 Directorio de C:\pyserial-3.3\enum

21/08/2018  07:33 p.m.    <DIR>          .
21/08/2018  07:33 p.m.    <DIR>          ..
21/08/2018  07:32 p.m.    <DIR>          dist
29/10/2015  08:07 p.m.    <DIR>          enum.egg-info
29/10/2015  08:07 p.m.             6,618 enum.py
29/10/2015  07:32 p.m.            35,147 LICENSE.GPL-3
29/10/2015  07:33 p.m.                51 MANIFEST.in
29/10/2015  08:07 p.m.             2,491 PKG-INFO
29/10/2015  08:07 p.m.                59 setup.cfg
29/10/2015  08:06 p.m.             2,557 setup.py
29/10/2015  08:07 p.m.    <DIR>          test
               6 archivos         46,923 bytes
               5 dirs  263,751,081,984 bytes libres

C:\pyserial-3.3\enum>python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to enum.egg-info\requires.txt
writing enum.egg-info\PKG-INFO
writing top-level names to enum.egg-info\top_level.txt
writing dependency_links to enum.egg-info\dependency_links.txt
reading manifest file 'enum.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'enum.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build
creating build\lib
copying enum.py -> build\lib
creating build\bdist.win-amd64
creating build\bdist.win-amd64\egg
copying build\lib\enum.py -> build\bdist.win-amd64\egg
byte-compiling build\bdist.win-amd64\egg\enum.py to enum.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
copying enum.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying enum.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying enum.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying enum.egg-info\not-zip-safe -> build\bdist.win-amd64\egg\EGG-INFO
copying enum.egg-info\requires.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying enum.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
creating 'dist\enum-0.4.6-py2.7.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing enum-0.4.6-py2.7.egg
creating c:\python27\lib\site-packages\enum-0.4.6-py2.7.egg
Extracting enum-0.4.6-py2.7.egg to c:\python27\lib\site-packages
Adding enum 0.4.6 to easy-install.pth file

Installed c:\python27\lib\site-packages\enum-0.4.6-py2.7.egg
Processing dependencies for enum==0.4.6
Searching for setuptools==28.8.0
Best match: setuptools 28.8.0
Adding setuptools 28.8.0 to easy-install.pth file
Installing easy_install-3.5-script.py script to C:\Python27\Scripts
Installing easy_install-3.5.exe script to C:\Python27\Scripts
Installing easy_install-script.py script to C:\Python27\Scripts
Installing easy_install.exe script to C:\Python27\Scripts

Using c:\python27\lib\site-packages
Finished processing dependencies for enum==0.4.6

C:\pyserial-3.3\enum>cd..

C:\pyserial-3.3>cd..

C:\>dir
 El volumen de la unidad C es 64Win7
 El número de serie del volumen es: B815-16CC

 Directorio de C:\

04/10/2017  12:56 a.m.    <DIR>          AdwCleaner
12/12/2017  10:23 p.m.    <DIR>          ale
12/12/2017  09:26 p.m.    <DIR>          asdda
13/10/2017  01:43 a.m.    <DIR>          Autodesk
03/10/2017  07:04 a.m.            32,768 bcd_backup
21/08/2018  01:26 a.m.    <DIR>          bcnc
23/07/2018  09:00 p.m.            19,728 bootsqm.dat
21/09/2017  10:57 p.m.                 0 cookies.sqlite
21/08/2018  01:20 a.m.    <DIR>          enum-0.4.6
30/09/2017  02:01 p.m.             3,449 GUDownLoaddebug.txt
14/05/2018  11:59 p.m.    <DIR>          KVRT_Data
07/10/2017  08:06 a.m.        12,107,153 LinuxCNC_Documentation.pdf
07/10/2017  08:07 a.m.           228,621 LinuxCNC_Getting_Started.pdf
09/10/2017  01:44 a.m.    <DIR>          Mach3
25/11/2017  11:44 p.m.    <DIR>          miniBloq.v0.83
01/12/2006  11:37 p.m.           904,704 msdia80.dll
04/09/2017  03:56 p.m.    <DIR>          My Drivers
14/07/2009  12:20 a.m.    <DIR>          PerfLogs
21/09/2017  10:57 p.m.                 0 places.sqlite
08/10/2017  08:44 p.m.    <DIR>          Predator Software
21/08/2018  12:24 a.m.    <DIR>          Program Files
13/08/2018  03:11 p.m.    <DIR>          Program Files (x86)
21/08/2018  07:37 p.m.    <DIR>          pyserial-3.3
21/08/2018  12:29 a.m.    <DIR>          pyserial-3.4
21/08/2018  12:03 a.m.    <DIR>          Python27
05/05/2018  05:49 p.m.    <DIR>          ShanaEncoder
25/01/2018  10:07 p.m.    <DIR>          temp
21/08/2018  06:45 p.m.    <DIR>          totalcmd
20/05/2018  11:10 a.m.    <DIR>          Users
21/08/2018  12:27 a.m.    <DIR>          Windows
29/07/2018  10:32 a.m.    <DIR>          Windows_Repair_Toolbox
               8 archivos     13,296,423 bytes
              23 dirs  263,751,032,832 bytes libres

C:\>cd bcnc

C:\bcnc>dir
 El volumen de la unidad C es 64Win7
 El número de serie del volumen es: B815-16CC

 Directorio de C:\bcnc

21/08/2018  01:26 a.m.    <DIR>          .
21/08/2018  01:26 a.m.    <DIR>          ..
13/08/2018  03:29 a.m.                28 .gitignore
13/08/2018  03:29 a.m.                 0 .git_cache_meta
13/08/2018  03:29 a.m.               224 bCNC
13/08/2018  03:29 a.m.               102 bCNC.bat
13/08/2018  03:29 a.m.               160 bCNC.desktop
13/08/2018  03:29 a.m.             1,150 bCNC.ico
13/08/2018  03:29 a.m.             5,686 bCNC.ini
13/08/2018  03:29 a.m.            19,656 bCNC.png
13/08/2018  03:29 a.m.            67,980 bCNC.pot
13/08/2018  03:29 a.m.            80,488 bCNC.py
13/08/2018  03:29 a.m.            33,236 bCNC.xbm
13/08/2018  03:29 a.m.             9,192 Camera.py
21/08/2018  12:20 a.m.             8,240 Camera.pyc
13/08/2018  03:29 a.m.           136,581 CNC.py
21/08/2018  12:20 a.m.           101,137 CNC.pyc
13/08/2018  03:29 a.m.            72,585 CNCCanvas.py
21/08/2018  12:20 a.m.            59,297 CNCCanvas.pyc
13/08/2018  03:29 a.m.            29,290 CNCList.py
21/08/2018  12:20 a.m.            25,126 CNCList.pyc
13/08/2018  03:29 a.m.             5,941 CNCRibbon.py
21/08/2018  12:20 a.m.             5,919 CNCRibbon.pyc
13/08/2018  03:29 a.m.            38,489 ControlPage.py
21/08/2018  12:20 a.m.            37,875 ControlPage.pyc
13/08/2018  03:29 a.m.            19,703 EditorPage.py
21/08/2018  12:20 a.m.            20,411 EditorPage.pyc
13/08/2018  03:29 a.m.            10,553 FilePage.py
21/08/2018  12:20 a.m.            10,465 FilePage.pyc
13/08/2018  03:29 a.m.    <DIR>          icons
21/08/2018  07:29 p.m.    <DIR>          lib
13/08/2018  03:29 a.m.             1,763 LICENSE.BSD3
13/08/2018  03:29 a.m.                13 LICENSE.md
13/08/2018  03:29 a.m.             1,291 LICENSE.MIT
13/08/2018  03:29 a.m.    <DIR>          locale
13/08/2018  03:29 a.m.               343 makefile
13/08/2018  03:29 a.m.    <DIR>          pendant
13/08/2018  03:29 a.m.             7,379 Pendant.py
21/08/2018  12:20 a.m.             7,609 Pendant.pyc
21/08/2018  12:45 a.m.    <DIR>          plugins
13/08/2018  03:29 a.m.            61,726 ProbePage.py
21/08/2018  12:20 a.m.            52,084 ProbePage.pyc
13/08/2018  03:29 a.m.             3,163 README.md
13/08/2018  03:29 a.m.            21,543 Ribbon.py
21/08/2018  12:20 a.m.            19,322 Ribbon.pyc
13/08/2018  03:29 a.m.            44,250 Sender.py
21/08/2018  12:20 a.m.            40,336 Sender.pyc
13/08/2018  03:29 a.m.             6,451 TerminalPage.py
21/08/2018  12:20 a.m.             6,505 TerminalPage.pyc
13/08/2018  03:29 a.m.            53,788 ToolsPage.py
21/08/2018  12:20 a.m.            50,572 ToolsPage.pyc
13/08/2018  03:29 a.m.             6,105 Updates.py
21/08/2018  12:20 a.m.             6,222 Updates.pyc
13/08/2018  03:29 a.m.            22,101 Utils.py
21/08/2018  12:20 a.m.            21,639 Utils.pyc
21/08/2018  12:29 a.m.    <DIR>          __pycache__
              48 archivos      1,233,719 bytes
               8 dirs  263,751,032,832 bytes libres

C:\bcnc>python bcnc
  File "bcnc", line 3
    DIR=`dirname $0`
                 ^
SyntaxError: invalid syntax

C:\bcnc>python bcnc.py
Traceback (most recent call last):
  File "C:\bcnc\ToolsPage.py", line 934, in __init__
    exec("import %s"%(name))
  File "<string>", line 1, in <module>
  File "C:\bcnc\plugins\slicemesh.py", line 32, in <module>
    import stl #FIXME: write smaller STL parser
  File "C:\bcnc\lib\stl\__init__.py", line 1, in <module>
    from .stl import BUFFER_SIZE
  File "C:\bcnc\lib\stl\stl.py", line 12, in <module>
    from . import base
  File "C:\bcnc\lib\stl\base.py", line 21, in <module>
    class Dimension(enum.IntEnum):
AttributeError: 'module' object has no attribute 'IntEnum'
Traceback (most recent call last):
  File "bcnc.py", line 2592, in <module>
    application = Application(tk)
  File "bcnc.py", line 113, in __init__
    self.ribbon = Ribbon.TabRibbonFrame(self)
  File "C:\bcnc\Ribbon.py", line 494, in __init__
    image=Utils.icons["new"],
KeyError: 'new'

C:\bcnc>

**Comment by darmalodar** [comment]
intalled enum y numpy and it shows me what i send

**Comment by mexbravo** [comment]
same problem

**Comment by alk1913** [comment]
try this. i only change the icons extension from GIF like in the last functional clone
[bCNC-master (22).zip](https://github.com/vlachoudis/bCNC/files/2312188/bCNC-master.22.zip)

**Comment by mexbravo** [comment]
thanks...with this version work perfect

**Comment by Harvie** [comment]
Yes, the problem is caused by me changing icons from GIF to PNG. It's strange that for me PNG works without problem. I think that it might be caused by the fact that i have Pillow module installed, which adds PNG support to Tkinter. I will revert PNGs back to GIF, but i'd like to understand this issue better, so please can you tell me if installing Pillow helps?

**Comment by mexbravo** [comment]
I have Pillow installed too, and doesnt work with PNG

**Comment by MARIOBASZ** [comment]
I also download Pillow in windows and it did not work. I will try to return from png to gif

**Comment by Harvie** [comment]
I've converted images back to GIFs and commited the changes...

**Comment by Laopa** [comment]
Hi

I got same issue, now with BCNC(22) it is nearly ok.  Mean BCNC can be open and launch, but if look at the CMD windows, find than missing some PYTHON module. nympy.....

To get ride of all anoying problems,  i add this command line in administrator CMD windows to install all necessary modules in PYTHON2.7.13.

"python -m pip install --user numpy scipy matplotlib ipython jupyter pandas sympy nose"

ALSO one very important things and not mention anywhere is YOU MUST INSTALL PYTHON2.7 X32. the X64 does not work. Also PYSERIAL is only for X32.

Happy CNC.

**Comment by Harvie** [comment]
> "python -m pip install --user numpy scipy matplotlib ipython jupyter pandas sympy nose"

AFAIK you don't need all of these, probably only numpy.

**Comment by cz7asm** [comment]
I had the same problem running it on Windows:

```
Traceback (most recent call last):
  File "bCNC.py", line 2592, in <module>
    application = Application(tk)
  File "bCNC.py", line 113, in __init__
    self.ribbon = Ribbon.TabRibbonFrame(self)
  File "D:\devel\mech\bCNC-master\Ribbon.py", line 495, in __init__
    image=Utils.icons["new"],
KeyError: 'new'
```

It turned out it was caused by this in Utils.py:

```
               try:
			icons[name] = PhotoImage(file=img)
			if getBool("CNC", "doublesizeicon"):
				icons[name] = icons[name].zoom(2,2)
		except TclError:
			pass
```
tkinter doesn't work with png images (at least on my win version) and the exception doesn't end up being very informative!

**The solution** (info here - http://effbot.org/tkinterbook/photoimage.htm):

```
                from PIL import Image, ImageTk
           ...
		try:
                        image = Image.open(img)
			icons[name] = ImageTk.PhotoImage(image)
			if getBool("CNC", "doublesizeicon"):
				icons[name] = icons[name].zoom(2,2)
		except TclError as e:
                        print e
			pass
```

**Comment by Harvie** [comment]
@cz7asm if you read this issue closely, you will find that i've removed the need for pillow and that it waits for upstream merge. you can try new version which does not need pillow from my fork:
http://github.com/harvie/bCNC/

**Comment by cz7asm** [comment]
@Harvie right, I gave it as much time as this issue deserved :)

**Comment by Guenni75** [comment]
I had the same Problem and the Harvie-Version works.
