### ISSUE TITLE
Tool Change Information

### ISSUE THREAD

**Issue by micksulley** [vlachoudis/bCNC#945]
This is not an issue as such but I didn't know how to post information for bCNC
I have been testing the Tool Change function and am really impressed, but I did find the documentation a bit sketchy, so I created a document for it and thought someone else may find it useful.

[ToolChangeV01.doc.zip](https://github.com/vlachoudis/bCNC/files/2307946/ToolChangeV01.doc.zip)

**Comment by Harvie** [comment]
I think this should go to wiki: https://github.com/vlachoudis/bCNC/wiki
I am not sure if you have permissions to edit it, but i suppose you do.

**Comment by micksulley** [comment]
Just tried it and it seems I do have permission, it is there.

**Comment by MARIOBASZ** [comment]
It is a good help to get involved in editing guides!
I have not seen your contribution uploaded to the page yet, I hope they upload it soon

**Comment by Harvie** [comment]
It's already there: https://github.com/vlachoudis/bCNC/wiki/Tool-Change-with-bCNC,-FreeCAD-&-grbl
