### ISSUE TITLE
Parameters of speed and acceleration in BCNC? Possible control of jerk?

### ISSUE THREAD

**Issue by MARIOBASZ** [vlachoudis/bCNC#949]
Are the acceleration and maximum velocity values ​​in the BCNC configuration used somewhere, in some way? Could it be a possible way to soften the jerk to use accelerations and higher speeds, for example, to optimize the trochoidal cutting method?

**Comment by Harvie** [comment]
As far as i know this is handled by GRBL and bCNC can be only used to setup GRBL's internal parameters...
