### ISSUE TITLE
Hershey text in bCNC

### ISSUE THREAD

**Issue by Navy001** [vlachoudis/bCNC#951]
I created text using Hershey extension n InkScape but in bCNC they they still in outline rather than in single line. Is there are a way or an add on for to use them ?

**Comment by Harvie** [comment]
This sounds like inkscape problem to me. Maybe use single line font made for engraving? Like these for example:
http://www.mrrace.com/CamBam_Fonts/

**Comment by Navy001** [comment]
You were right of course ! I kind of need to unselect my text before re-select it and process as Gcode. Sorry to bother you !  
I am sure that the "b" in bCNC stand for the "BEST" !!! I like it very much ! 
THANKS VERY MUCH
