### ISSUE TITLE
BCNC Linux - IDLE Message in Terminal

### ISSUE THREAD

**Issue by cncvictor** [vlachoudis/bCNC#957]
Hello guys
I use the BCNC for my mini pen CNC in Linux Mint, it always worked perfectly, but for a few days now, I open the program and it does not connect. I use the Arduino Uno with the A4988 shield. I open the Bcnc terminal and an IDLE, IDLE, IDLE message will appear without stopping. I do not know what it can be and I need the help of my friends.
I already changed the Shield for another reservation I have, I tested the arduino, I installed GRBL, Pyserial, etc, but nothing.

I await and thank you in advance

Victor

**Comment by Harvie** [comment]
#958 duplicate
