### ISSUE TITLE
Make the error exportable as a file

### ISSUE THREAD

**Issue by onekk** [vlachoudis/bCNC#96]
Please Make the error report exportable as a file so i can send it to you, as my machine controller have no internet connection.

Thanks and Regards.
Carlo D.

**Comment by vlachoudis** [comment]
Good idea, I should put it as an option . For the moment the error report you can copy&paste to a file. The terminal output is not possible to copy, but I have to add it as well.

**Comment by Effer** [comment]
Is exsportable now? Does it really needs to?

**Comment by vlachoudis** [comment]
No it is not exportable. But it is very easy to copy paste on another file. So I don't see the reason.
