### ISSUE TITLE
Not connecting to Shapoeoko 3

### ISSUE THREAD

**Issue by SLCJedi** [vlachoudis/bCNC#963]
Hi. Just installed on a RPi 3b+. bCNC opens, but as soon as I try to connect it freezes. The Pi has to be restated to close bCNC. Screenshot for error message in the terminal.
![image](https://user-images.githubusercontent.com/18455002/45273358-9e007600-b46f-11e8-865c-c4b58a50c705.png)

**Comment by Harvie** [comment]
use latest git master and install numpy module for your python
