### ISSUE TITLE
lasercutter speed / power

### ISSUE THREAD

**Issue by sns5400** [vlachoudis/bCNC#977]
Hello, when i load a dxf file for cutting, the cutterspeed F is 1200 mm/min and movement F are 3000 mm/min inside the gcode

Is there a way to set the power in procenten , speed for cutting and speed for movements ?

thank you in advance

**Comment by MARIOBASZ** [comment]
maybe the maximum speed you have set is 1200

**Comment by Harvie** [comment]
You set this using g-code like `M3 S1000`
