### ISSUE TITLE
Question Intersection, union; problem with difference. Possible exclusive union?. Intersection: strange behavior

### ISSUE THREAD

**Issue by MARIOBASZ** [vlachoudis/bCNC#984]
had not seen the intersection and difference utilities @harvie.
I have drawn two squares.

![image](https://user-images.githubusercontent.com/11743403/46226429-9c212880-c332-11e8-85ee-c2756441fc2c.png)

1- If I choose to make a difference between both squares, two figures appear identical to the selected squares, I do something wrong or it is not working difference.
2- Intersection repeats the common routes. Minor detail, but maybe you can make the route a single one instead of a duplicate one.

![image](https://user-images.githubusercontent.com/11743403/46226502-e0acc400-c332-11e8-977c-18009c33f4f2.png)

3-Possibility of implementing exclusive union? =union-difference 
(I do not know if I had already asked him sometime) (intersection appears with dots)

![image](https://user-images.githubusercontent.com/11743403/46226814-d808bd80-c333-11e8-8bdb-e84e6fc4e3f4.png)

**Comment by MARIOBASZ** [comment]
I began to read the code, I lack basic knowledge of some things (can ask things things if I lack to be able to understand?). The difference works correctly to subtract island

**Comment by MARIOBASZ** [comment]
rying to adapt for external union or exclusive union (that from point A of intersection to point B of intersection the road is by the outside), I discovered that if one of the figures starts inside the other, intersection has a result other than intersection:
![image](https://user-images.githubusercontent.com/11743403/46237352-54ae9280-c35a-11e8-9bd3-bf3a24e8d822.png)
It would not be a problem for external union

**Comment by Harvie** [comment]
These plugins are in development. They are only building blocks for bigger plugin for pocketing. They are not meant to be used directly for now!

**Comment by MARIOBASZ** [comment]
Sorry, I had not noticed.
Woww !!! You are a few steps to use on the PCB islands!

![image](https://user-images.githubusercontent.com/11743403/46247538-393b9a00-c3e3-11e8-9474-540a8f7c200d.png)

It would be an excellent strategy to be able to use a combination of two or more endmil for the elimination of copper

**Comment by Harvie** [comment]
I don't think it makes sense to use bCNC as PCB CAM right now. There is very nice free opensource program with better fit for this task:
http://flatcam.org/manual/procedures.html#copper-area-clear

**Comment by MARIOBASZ** [comment]
I have used Flatcam before, I prefer pcb-gcode. The good thing for me would be that from pcb-gcode you could use more than one endmill for the widening of copper-free zones, instead of successive passes with an endmill of 0.10, or from here, which I still believe can be a simple option, quick to use and very adaptable by the intervention of different opinions. After all, you have been criticized for trying an adaptive milling existing 360, and at least we both went to trochoidal milling (by the way, you still have at your disposal the diameters for adaptive trocoid in the corners), upload the spiral machining to enlarge the holes, there is the descent in ramp, helicoid ...
And with helical drilling, adapting it, (an idea pending to implement) with the same tool to perform the different perforation diameters, it is possible to optimize the PCB operations with the least change of tools.
I do not know how to do it, for you maybe it's very simple: Having the points of intersection A and B, can you generate the route so that the result is from the outside, instead of from the inside? (the opposite way to the intersection) There would be a "union for the outside" or exclusive union.

**Comment by Harvie** [comment]
@MARIOBASZ i know. but there's much more to milling PCBs. it's whole rabbit hol. starting with parsing gerbers. I think this is not gonna happen soon.

**Comment by MARIOBASZ** [comment]
it is not necessary to understand Gerber, only to handle figures, and the restriction to enlarge is like the posters "Prohibido Ingresar. Private property. The sentry will open fire "
or "Beware of the dog. You can piss her shoes "
