### ISSUE TITLE
Different versions and the latest master

### ISSUE THREAD

**Issue by galoopy** [vlachoudis/bCNC#995]
I have downloaded the latest master and it does not run.  I assume the rest of the installation is in order since 9.10 runs without a problem.  I have also downloaded 9.11 which repeats itself as 9.10 when the updates button in bCNC is used.  I might be missing something or has someone else experienced this?

**Comment by MARIOBASZ** [comment]
look at issue # 943, download the version of @harvie

**Comment by Harvie** [comment]
@vlachoudis
