### ISSUE TITLE
ERROR invalid command!

### ISSUE THREAD

**Issue by sfinexer** [vlachoudis/bCNC#997]
The signs "+" and "-" do not work.
Here's a video:
http://cnc.tiven.ru/ssr-2018-10-07_17.03.45.mp4

**Comment by Harvie** [comment]
try it like this: `G0 X-10` or `G1 X-10`

**Comment by Harvie** [comment]
Just checked using plain serial terminal and this IS bCNC fault, because in GRBL this works

**Comment by Harvie** [comment]
Try now!

**Comment by sfinexer** [comment]
@Harvie Yes, everything works now !!!
